// Monterey / Northeast-Pacific midwater representatives. Every anatomical
// measure remains separate from the complete authored pose and clearance.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius, origin) => ({
  x, y, z, horizontalRadiusUnits: radius, origin,
  axes: 'positive-x-heading; positive-y-up; transverse-z',
  status: 'uncalibrated-conservative-complete-display-pose-and-animation-clearance',
});
const capture = (point, part) => ({
  foodCapturePointLocal: point, feedingPointLocal: point,
  fixedCapturePart: part, rootAnimation: false,
});
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '蒙特雷湾与东北太平洋加州中层水体的区域代表，非同站共现普查',
  coOccurrenceStatus: 'regional-representatives-with-overlapping-depth-evidence-not-a-field-census',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  calibratedPopulationRates: null, populationDensityPerM3: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null,
  calibratedAgeSec: null, calibratedEnergyContent: null,
  bioluminescent: false,
  bioluminescenceStatus: 'source-reported-defensive-light-not-a-continuous-display-emission',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure,
    status: 'illustrative-selection-within-source-size-evidence-not-a-measured-local-size-distribution' },
  admissionDepthM: { range: data.depthSelectionM,
    status: 'selected-gate-for-whole-body-and-appendages-not-complete-natural-depth-range' },
  depthRangeM: data.depthSelectionM, sourceLinks: data.sources,
  preferredFoodPool: data.foodPool,
  feedingStockPath: 'region.deepMidwaterLife.channels[].parcels[].amount',
  foodProxyStatus: 'independent-bounded-midwater-selected-food-component',
  foodProxyNote: '独立有类型中层食物控制体，初始库存为零；有账外部输入、真实输运、食器接触扣减和输出，不挪用或重填原海床/岩附着/近底食物库存。',
  individualStatus: 'independent-animal-record-with-native-clock-and-relative-condition-account',
  motion: { pitchRangeRad: [-.12, .12], rootAnimation: false,
    status: 'authored-bounded-whole-pose-not-measured-natural-swimming-rate' },
  support: { mode: 'free-off-bottom-midwater', fixedAttachment: false,
    clearance: 'whole-body-appendages-and-bounded-animation-in-source-qualified-water-depth-band' },
  limitations: [
    '三条具名记录仅是来源支持的区域中层代表；展示数量不是自然密度，也不证明同站同刻共现。',
    '选定尺寸、水深门限、比例、附肢姿态、摄食距离、游速和相对状态率是有限展示选择，未经野外校准。',
    '食物只表示声明的未解析营养部分，不构成完整食物网、具名猎物捕杀或真实碳质量。',
    '未模拟繁殖、年龄、生长、自然死亡率、光适应或氧最低带生理；观察灯与昼夜不产生食物或能量。',
  ],
  ...data,
});

export const deepMidwaterLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'helmet-jelly', commonName: '冠水母', scientificName: 'Periphylla periphylla',
    nameNote: '中文为描述名称；以学名确定身份，不泛称所有深海水母。',
    kind: 'jellyfish', modelRole: 'helmet-jelly', family: 'Periphyllidae',
    guild: 'selected-zooplankton-capturing-medusa',
    lengthM: .225, sizeRangeM: [.20, .25], sizeMeasure: 'bell-diameter',
    measurementDefinition: '铃体横向最大直径；不含铃高、十二条触手或整套保守姿态包络。',
    depthSelectionM: [650, 750],
    referenceDepthM: { montereySurveyBand: [200, 1000], montereyDirectObservationM: 700,
      aquariumReportedRangeM: [0, 4000],
      note: '2007蒙特雷中层水母调查的200–1000米是调查带，不是假定本种在带内均匀分布；MBARI2025年11月6日直接记录约700米的具名冠水母。' },
    referenceSizeM: { aquariumMaximumBellDiameterM: .25,
      morphologyChapterMaximumBellDiameterM: .35,
      reportedTentacleLengthMaximumM: .50,
      note: 'MBA与JAMSTEC作者分类章节的铃径上限分别保留；WHOI触手上限仅作附肢尺度参考，不作蒙特雷实株的铃径-触手长度配对。' },
    normalizedEnvelope: envelope([-1.05, 1.05], [-2.15, 1.35], [-1.05, 1.05], 1.49,
      'bell-rim-centre-with-bell-diameter-one-and-bell-apex-positive-y'),
    foodPool: 'midwaterAnimalFood',
    diet: '浮游动物；本版仅采用未解析的悬浮动物性营养部分。',
    foodScope: 'selected-unresolved-suspended-zooplankton-component',
    feedingEvidenceLevel: 'official-aquarium-species-diet-with-tentacle-capture-anatomy',
    feedingProxy: { pool: 'midwaterAnimalFood', selectedComponent: 'zooplankton-animal-material',
      omitted: ['named-live-prey-capture', 'nematocyst-mechanics', 'tentacle-to-mouth-transfer'] },
    colors: ['#823334', '#b75248', '#50222e', '#d88267'],
    description: '高而尖的红褐色铃，冠沟和铃缘瓣明显；十二条完整边缘触手构成与浅海长口腕海蜇不同的轮廓。',
    behavior: '独立中层游动位置与有限铃脉动、触手姿态；固定一条真实触手末端作为捕获参考，不把中央口误作远端触手食点。',
    habitat: ['monterey-canyon-midwater', 'mesopelagic-water-column'],
    sourceBioluminescence: 'MBA记录受惊时铃体蓝色闪光；此包不模拟常亮发光或假定持续受惊。',
    motion: { pitchRangeRad: [0, 0], rootAnimation: false,
      status: 'authored-upright-medusa-display-pose-and-bounded-bell-pulse' },
    morphology: {
      form: 'high-conical-coronate-bell-twelve-solid-marginal-tentacles',
      tentacleCount: 12, lappetCount: 16, rhopaliumCount: 4,
      longOralArmCount: 0,
      sizeAxis: 'maximum-transverse-bell-diameter-normalized-to-one',
      ...capture({ x: .50, y: -1.90, z: 0 }, 'visible-terminal-point-of-connected-marginal-tentacle-zero'),
      authoredTentacleZeroLengthUnits: 1.90,
      clearanceIncludes: ['whole-pointed-bell', 'coronal-groove', 'all-sixteen-lappets',
        'all-four-rhopalia', 'mouth-region', 'all-twelve-complete-tentacles', 'bounded-bell-and-tentacle-poses'],
      reference: 'Lindsay等原作者分类51.3.2与Fig51.31给完整形态；其中日本751米样本只用于形态，不冒作蒙特雷地域证据。',
    },
    sources: [
      source('https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/helmet-jelly',
        'Monterey Bay Aquarium物种页：学名、浮游动物食性、铃径25厘米和防御闪光'),
      source('https://www.mbari.org/news/mbari-researchers-encounter-rarely-seen-deep-sea-seven-arm-octopus/',
        'MBARI直接观察2025-11-06：蒙特雷约700米的具名P.periphylla；此记录不是水母食谱'),
      source('https://www.sciencedirect.com/science/article/abs/pii/S0967063707001094',
        'The habitat of mesopelagic scyphomedusae in Monterey Bay, California（2007）：1990–1998、200–1000米原观察调查'),
      source('https://link.springer.com/chapter/10.1007/978-4-431-54865-2_51',
        'Lindsay等JAMSTEC作者开放章节：Periphylla全体形Fig51.31，十二触手/十六瓣/四感官；日本样本仅用于形态'),
      source('https://www.whoi.edu/ocean-learning-hub/ocean-facts/helmet-jellyfish/',
        'WHOI海洋机构说明：冠水母十二触手及触手最大约50厘米，非蒙特雷配对实测'),
    ],
  }),
  descriptor({
    id: 'vampire-squid', commonName: '吸血乌贼', scientificName: 'Vampyroteuthis infernalis',
    nameNote: '传统中文名称；本种是吸血乌贼目头足动物，不将名称解释为吸血或主动追猎。',
    kind: 'cephalopod', modelRole: 'vampire-squid', family: 'Vampyroteuthidae',
    guild: 'marine-snow-detritivore-with-retractile-feeding-filaments',
    lengthM: .115, sizeRangeM: [.10, .13], sizeMeasure: 'mantle-length',
    measurementDefinition: '外套后端至外套前缘的轴向外套长ML；头、八腕、蹼、鳍和两条采食丝完整另外纳入包络，不能把ML当全长。',
    depthSelectionM: [650, 750],
    referenceDepthM: { montereyCollectedSpecimensM: [600, 800],
      mbariReportedRangeM: [600, 900],
      note: 'Hoving/Robison2012原论文蒙特雷采集带与MBARI物种页范围各自保留；此包选择其交叠带内650–750米。' },
    referenceSizeM: { montereyCollectedMantleLengthsM: [.022, .150],
      mbariReportedMaximumTotalLengthM: .30,
      reportedExtendedFilamentMaximumBodyLengths: 8,
      note: '22–150毫米为原论文蒙特雷ML样本范围；30厘米是MBARI总长，不能拿来定义ML。八倍为来源报道的极展丝长，不是本包实际姿态比例。' },
    normalizedEnvelope: envelope([-2.20, 4.70], [-1, 1], [-1, 1], 4.81,
      'mantle-axis-midpoint-with-mantle-length-one-posterior-negative-x'),
    foodPool: 'midwaterOrganicParticles',
    diet: '以海洋雪中的死有机残屑、粪粒和废弃黏液结构为主要食物；此包选择有机碎屑部分，不假装追杀活体猎物。',
    foodScope: 'selected-marine-snow-detrital-organic-particle-component',
    feedingEvidenceLevel: 'original-monterey-rov-laboratory-gut-and-filament-study',
    feedingProxy: { pool: 'midwaterOrganicParticles', selectedComponent: 'marine-snow-organic-detritus',
      omitted: ['filament-retraction-sequence', 'arm-scraping-and-mucus-aggregation',
        'transfer-to-mouth', 'full-diet-composition', 'incidental-live-hitchhikers'] },
    colors: ['#693a43', '#8f5157', '#352d43', '#b7888b'],
    description: '圆软外套、两片侧鳍、八腕之间的深蹼和两条细长采食丝；整体为有鳍披风形，不添加十腕乌贼式两条粗触手棒。',
    behavior: '以有鳍缓慢游动和漂浮采食为代表；来源描述常静悬伸丝，所以此包不宣称积极追猎或测得自然游速。',
    habitat: ['monterey-mesopelagic-water', 'oxygen-minimum-zone-associated-midwater'],
    sourceBioluminescence: 'MBARI记录腕端及受惊排放的发光物；此包不模拟持续自发光，也不把它当墨汁。',
    morphology: {
      form: 'soft-rounded-mantle-two-adult-fins-eight-webbed-arms-two-retractile-filaments',
      armCount: 8, adultFinCount: 2, retractileFilamentCount: 2, clubTentacleCount: 0,
      sizeAxis: 'mantle-posterior-negative-half-to-anterior-positive-half',
      displayFilamentPose: 'two-complete-partly-extended-filaments-one-forward-one-curved-back',
      ...capture({ x: 4.50, y: 0, z: .20 }, 'visible-distal-point-on-one-connected-retractile-food-capture-filament'),
      clearanceIncludes: ['whole-mantle', 'head-and-large-eyes', 'both-adult-fins',
        'all-eight-arms', 'whole-interbrachial-web', 'cirri', 'both-complete-feeding-filaments',
        'bounded-fin-arm-web-animation'],
      reference: 'MBARI原研究配图与2012原论文；短于最大伸丝的完整展示姿态是作者选择，不是测得的自然极展包络。',
    },
    sources: [
      source('https://www.mbari.org/animal/vampire-squid/',
        'MBARI具名物种页：600–900米、最大总长30厘米、海洋雪、两丝/八腕/鳍与发光防御'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC3479720/',
        'Hoving/Robison2012原论文：蒙特雷600–800米、22–150毫米ML、ROV/实验/胃含物与采食丝'),
      source('https://www.mbari.org/news/mbari-researchers-discover-what-vampire-squids-eat-its-not-what-you-think/',
        '原研究机构2012原作者研究报道与全体/采食图：伸丝可达身体八倍、收丝刮取黏液转口、主要海洋雪'),
    ],
  }),
  descriptor({
    id: 'giant-red-mysid', commonName: '巨型红糠虾', scientificName: 'Neognathophausia ingens',
    sourceScientificName: 'Gnathophausia ingens',
    nameNote: '当前接受组合Neognathophausia ingens；旧原论文和MBARI说明常用Gnathophausia ingens。中文为描述名称，不称十足目龙虾。',
    kind: 'crustacean', modelRole: 'giant-red-mysid', family: 'Gnathophausiidae',
    guild: 'pelagic-lophogastrid-selected-sinking-animal-detritus-feeder',
    lengthM: .105, sizeRangeM: [.09, .12], sizeMeasure: 'rostrum-to-telson-length',
    measurementDefinition: 'DFO物种账户明确含额角的长度口径：额角尖至尾节尖；不把该全轴长度写成甲长CL，长触角和胸腹足另外纳入完整包络。',
    depthSelectionM: [650, 750],
    referenceDepthM: { californiaAdultDaytimeM: [650, 750],
      californiaAdultNighttimeDispersionM: [400, 900], montereyDirectObservationM: 900,
      region: 'Monterey外峡谷直接ROV观测；San Clemente Basin加州原研究日夜深度',
      note: 'Frank2017总结非幼体代表的加州日间650–750米；夜间400–900为扩散而非强制昼夜垂迁。900米照片与加州采样不是同站。' },
    referenceSizeM: { dfoMaximumIncludingRostrumM: .350,
      dfoTypicalCapturedUpperBoundM: .160,
      originalAdultCarapaceLengthsM: [.0197, .049],
      mbariCaptionLengthInches: [3, 4], mbariCaptionMeasure: null,
      note: 'DFO1986账户最大350毫米含额角、捕获常小于160毫米；Frank2017的19.7–49毫米是CL，未转换。MBARI照片说明3–4英寸未定义量尺，亦不据此伪造CL/TL换算。' },
    normalizedEnvelope: envelope([-.60, 1.30], [-.50, .40], [-.55, .55], 1.42,
      'rostrum-to-telson-axis-midpoint-with-rostrum-tip-positive-half-and-telson-tip-negative-half'),
    foodPool: 'midwaterOrganicParticles',
    diet: 'MBARI具名说明包括下沉碎屑和小型死亡动物；本版仅选择其中有机残屑部分，不宣称这就是所有地域、生命阶段的完整食谱。',
    foodScope: 'selected-sinking-organic-debris-and-small-dead-organism-component',
    feedingEvidenceLevel: 'mbari-authored-species-description-preserved-with-credited-regional-whole-animal-photo',
    feedingProxy: { pool: 'midwaterOrganicParticles', selectedComponent: 'sinking-organic-animal-detritus',
      omitted: ['complete-wild-diet', 'named-live-prey-kill', 'brooding-and-ontogenetic-migration',
        'mouthpart-processing-and-luminescent-defense'] },
    colors: ['#a53737', '#c34a42', '#632d38', '#322931'],
    description: '红色透明甲壳、前伸额角和柄眼、细长触角、分节腹部与完整尾扇；胸足和腹足形成离底游动的虾状轮廓，保留口器而不添大螯。',
    behavior: '以独立主动游动的非抱卵代表展示；腹足/胸足有限动作，真实固定腹前口器接近食点，不把同一虚影复制成群。',
    habitat: ['monterey-canyon-off-bottom-midwater', 'california-mesopelagic-adult-depth-band'],
    sourceBioluminescence: 'MBARI说明受惊排放发光液体；此包不实现常亮发光、持续喷液或已校准的惊扰反应。',
    morphology: {
      form: 'rostrate-carapace-stalked-eyes-segmented-abdomen-thoracic-and-pleopod-appendages-tail-fan',
      sizeAxis: 'rostrum-tip-positive-half-to-telson-tip-negative-half',
      carapaceLengthConversion: null,
      ...capture({ x: .17, y: -.14, z: 0 }, 'visible-connected-anterior-ventral-mouthpart-region'),
      clearanceIncludes: ['whole-rostrum', 'carapace-and-spines', 'both-stalked-eyes',
        'complete-long-antennal-appendages', 'all-abdominal-segments', 'thoracic-appendages',
        'pleopods', 'telson-and-uropod-tail-fan', 'bounded-appendage-and-tail-animation'],
      reference: 'DFO1986具名账户pp160–162与MBARI Tiburon全体照片；作者完整简化，不以CL推算身长。',
    },
    sources: [
      source('https://www.marinespecies.org/photogallery.php?album=675&pic=111872',
        'MBARI署名Tiburon直接全体照片与机构说明：Monterey外峡谷约900米、红色虾形、沉降碎屑/小死亡动物'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC5312021/',
        'Frank2017原加州研究：San Clemente Basin成体CL19.7–49毫米，日间650–750米、夜间400–900米扩散'),
      source('https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/12989.pdf',
        'Kathman等DFO1986东北太平洋官方鉴定手册pp160–162：全形/额角/柄眼/口器/尾扇、350毫米含额角、捕获常<160毫米'),
      source('https://www.marinespecies.org/aphia.php?id=220999&p=taxdetails',
        'WoRMS具名接受组合Neognathophausia ingens；与旧Gnathophausia文献映射'),
    ],
  }),
]);

export const deepMidwaterLifeSpeciesById = freeze(Object.fromEntries(
  deepMidwaterLifeSpeciesCatalog.map(species => [species.id, species]),
));
