// Northeast-Pacific near-bottom swimmers. Source anatomical measures are not
// interchangeable with total mesh extent or with conservative pose clearance.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius, origin) => ({
  x, y, z, horizontalRadiusUnits: radius,
  axes: 'positive-x-forward; positive-y-up; transverse-z', origin,
  status: 'uncalibrated-conservative-whole-display-and-animation-clearance',
});
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '东北太平洋深海近底代表；Oregon深海平原与加州近底观测，非单站重建',
  coOccurrenceStatus: 'regional-representatives-not-a-co-occurrence-census',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  populationDensityPerM2: null, calibratedPopulationRates: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null,
  calibratedAgeSec: null, verifiedBioluminescence: null,
  bioluminescent: false, bioluminescenceStatus: 'not-verified-no-emission',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM,
    status: 'selected-display-gate-applied-to-whole-body-not-complete-natural-range' },
  depthRangeM: data.depthSelectionM, sourceLinks: data.sources,
  foodPool: 'benthicAnimalFood', preferredFoodPool: 'benthicAnimalFood',
  foodProxyStatus: 'existing-native-benthic-animal-food-selected-component',
  foodProxyNote: '只在真实食器接近原生benthicPatches食点时扣除现有benthicAnimalFood；未解析的底栖动物性食物选定部分，不新建食物或冒称可视具名猎物。',
  feedingStockPath: 'region.sim.benthicPatches[].benthicAnimalFood',
  individualStatus: 'independent-animal-record-with-native-clock-and-relative-energy-account',
  motion: { pitchRangeRad: [-.12, .12],
    status: 'authored-bounded-poses-not-measured-natural-swimming-rate', rootAnimation: false },
  support: { mode: 'free-swimming-near-actual-native-seafloor', fixedAttachment: false,
    clearance: 'complete-body-and-appendages-clear-native-floor-rocks-and-other-animals' },
  limitations: [
    '两种记录是同一区域的生境代表，未证明当前3500米同站共现；显示数量不是自然密度或种群普查。',
    '尺寸选择、体形比例、碰撞包络、游速、摄食距离和能量阈值为展示模型，未经野外校准。',
    '相对能量账不是动物碳质量；未模拟年龄、繁殖、生长或具名个体捕杀。观察灯和昼夜不提供食物。',
  ],
  ...data,
});

export const deepWaterLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'abyssal-dumbo-octopus', commonName: '深渊小飞象章鱼',
    scientificName: 'Grimpoteuthis bathynectes',
    nameNote: '中文为描述名称；以Voss与Pearcy1990具名种确定身份，不以泛小飞象属代替深度依据。',
    kind: 'octopus', modelRole: 'near-bottom-finned-octopus', family: 'Grimpoteuthidae',
    guild: 'selected-epibenthic-animal-feeder', lengthM: .075,
    sizeRangeM: [.065, .085], sizeMeasure: 'mantle-length',
    measurementDefinition: '外套后端至外套前缘的轴向外套长ML；不含头、八腕、腕间膜和鳍。',
    depthSelectionM: [3400, 3600],
    referenceDepthM: { range: [2816, 3932], typeDepthM: 3932,
      region: '东北太平洋Oregon外海Tufts与Cascadia深海平原',
      note: 'FAO2014的具名种标本范围；作者ToL转录原始正模3932米。选择3400–3600米，不用泛属最深值扩展本种。' },
    referenceSizeM: { maximumMantleLengthM: .085, maximumTotalLengthM: .240,
      measure: 'mantle-length-and-total-length-kept-separate',
      sourceSpecimenMantleLengthsM: [.029, .031, .0465, .048, .050, .053, .057, .085],
      note: '作者ToL原表来自Voss/Pearcy1990；FAO2014分别报告ML85毫米与TL240毫米。这不是整套保守包络的实测大小。' },
    normalizedEnvelope: envelope([-.55, 2.60], [-1.30, .75], [-1.30, 1.30], 2.91,
      'mantle-axis-midpoint-with-mantle-length-normalized-to-one'),
    colors: ['#8f8b8c', '#65545e', '#46333b', '#c5aca0'],
    description: '圆钝柔软外套、两片侧鳍、八条亚等长腕与延至近腕尖的厚腕间膜，口面具单行吸盘和成对短须；保持伞形腕冠与鳍的整体差别。',
    diet: '本种食谱未核定。以同属G.boylei原始胃含物中的多毛类和小甲壳类，推断选取底栖动物性食物部分；不把同属记录写成本种实测。',
    behavior: '采用有鳍章鱼的近底游泳代表行为；真实位置移动配有限鳍/腕膜动作，不把鳍称耳朵，不添长鼻或乌贼式两条捕食触手。',
    feedingEvidenceLevel: 'explicit-congener-diet-inference-species-gut-contents-unverified',
    habitat: ['abyssal-near-bottom-water', 'continental-slope-and-abyssal-plain'],
    morphology: { form: 'rounded-mantle-two-fins-eight-subequal-arms-deep-primary-web',
      armCount: 8, finCount: 2, feedingTentacleCount: 0,
      suckers: 'single-longitudinal-row-on-each-arm-with-short-paired-cirri',
      displayTotalAxialLengthMaxUnits: 2.8,
      sizeAxis: 'mantle-posterior-negative-half-to-anterior-positive-half',
      feedingPointLocal: { x: .65, y: -.55, z: 0 },
      fixedFeedingPart: 'visible-mouth-at-connected-ventral-arm-crown-centre',
      clearanceIncludes: ['whole-mantle', 'head-and-eyes', 'both-fins', 'all-eight-arms',
        'entire-primary-web', 'suckers-and-cirri', 'bounded-fin-arm-web-animation'],
      reference: 'Voss/Pearcy1990 Figures4–5 reproduced by Young/Vecchione ToL; conservative authored complete geometry, not a scanned specimen' },
    sources: [
      source('https://www.fao.org/4/i3489e/i3489e.pdf',
        'Hochberg/Norman/Finn2014 FAO原作者图鉴p261：具名东北太平洋种、2816–3932米、ML85与TL240毫米'),
      source('https://tolweb.org/Grimpoteuthis_bathynectes/20118',
        'Young/Vecchione作者ToL：原标本全体图、八腕/厚膜/吸盘短须和Oregon正模3932米'),
      source('https://tolweb.org/notes/?note_id=1547',
        'Young/Vecchione原标本计量表：来自Voss/Pearcy1990，ML、TL、臂与鳍长度各自分列'),
      source('https://tolweb.org/notes/?note_id=1546',
        'Young/Vecchione续述原分类：灰褐外套头、紫褐腕膜口面及喙形'),
      source('https://zenodo.org/records/5438036',
        'Collins2003原始分类p110：同属G.boylei单标本胃内多毛类/端足类/等足类等，作为明确推断而非本种实测食性'),
      source('https://www.marinespecies.org/aphia.php?id=342082&p=taxdetails',
        'WoRMS/MolluscaBase接受G.bathynectes；原分类p57与Figures4–5的索引'),
    ],
  }),
  descriptor({
    id: 'giant-cusk-eel', commonName: '巨型鼬鳚', scientificName: 'Spectrunculus grandis',
    nameNote: '中文为描述名称；鼬鳚科鱼，并非鳗鲡目真鳗。',
    kind: 'fish', modelRole: 'near-bottom-cusk-eel', family: 'Ophidiidae',
    guild: 'benthic-invertebrate-predator-and-scavenger', lengthM: .80,
    sizeRangeM: [.70, .90], sizeMeasure: 'standard-length',
    measurementDefinition: '吻端至尾部脊柱/尾鳍基部的标准长SL；不包括尾鳍末端。显示完整尾鳍另计入全体包络，不能把SL标签写成TL。',
    depthSelectionM: [3400, 3600],
    referenceDepthM: { range: [2000, 4300],
      region: 'MBARI加州外海近底观测与深海资料',
      note: 'MBARI物种页的2000–4300米范围支持展示选择；不是当前窗口3500米的实测普查。' },
    referenceSizeM: { maximum: 1.30, measure: 'standard-length',
      mbariReportedMaximumM: 1.30, mbariMaximumMeasure: null,
      note: '2023原始分类检索表对真S.grandis给130厘米SL；MBARI另列最大1.3米但没有注明量尺，不据此声称1.3米TL。' },
    identityCaveat: '采用Uiblein等2023重新界定的太平洋S.grandis；旧全球/大西洋记录部分属于S.stenostio等，不把这些地域与尺寸混入本版。展示体不能完成耳石/鳍条物种鉴定。',
    normalizedEnvelope: envelope([-.60, .55], [-.23, .23], [-.23, .23], .65,
      'standard-length-axis-midpoint-snout-positive-half-tail-base-negative-half'),
    colors: ['#b6a99d', '#82766d', '#5c514b'],
    description: '粗短圆吻头接长而渐细的鱼体，连续背侧/腹侧鳍带汇至尾端、低位胸鳍和腹鳍；下侧口与明显鼻部形成近底探食轮廓。',
    diet: '底栖无脊椎动物及动物腐肉；本版仅选未解析的底栖动物性食物部分，不把它当远离海床的浮游滤食者。',
    behavior: '在实际海床上方缓慢游动并接近底层食点；尾与鳍做有限动作，取食时由真实下侧口接触。',
    feedingEvidenceLevel: 'mbari-regional-observations-of-benthic-invertebrates-and-carrion',
    habitat: ['abyssal-near-bottom-water', 'muddy-seafloor-and-coral-garden-edge'],
    morphology: { form: 'robust-rounded-subterminal-mouth-head-elongate-tapered-body-continuous-unpaired-fins',
      sizeAxis: 'snout-positive-half-to-tail-base-negative-half-standard-length-one',
      tailFinExtentNegativeX: -.57,
      feedingPointLocal: { x: .47, y: -.16, z: 0 },
      fixedFeedingPart: 'visible-subterminal-mouth-connected-to-ventral-snout',
      clearanceIncludes: ['entire-head-and-body', 'nostril-region', 'both-pectoral-fins',
        'pelvic-fins', 'full-dorsal-anal-and-caudal-fins', 'bounded-tail-fin-animation'],
      reference: 'MBARI California living animal whole form plus Uiblein/Møller/Nielsen2023 genus/species diagnosis; approximate authored geometry, not a scan' },
    sources: [
      source('https://www.mbari.org/animal/giant-cusk-eel/',
        'MBARI一手加州近底动物页：2000–4300米、完整体形、底栖无脊椎/腐肉及加州研究点'),
      source('https://bioone.org/journalArticle/Download?urlId=10.1643%2Fi2023005',
        'Uiblein/Møller/Nielsen2023原分类：真太平洋S.grandis检索表130厘米SL，四种区分与全体形诊断'),
      source('https://researchprofiles.ku.dk/en/publications/the-systematics-of-the-ophidiid-genus-ispectrunculusi-teleostei-o/',
        '原作者机构发表记录与全文：2023修订将旧Atlantic等记录分出S.stenostio，S.grandis限太平洋'),
      source('https://zenodo.org/records/13285128',
        '2023原分类属处理：粗圆吻、下侧口、低位腹鳍和近底成体；这些是属级形态证据'),
    ],
  }),
]);
export const deepWaterLifeSpeciesById = freeze(Object.fromEntries(
  deepWaterLifeSpeciesCatalog.map(species => [species.id, species]),
));
