// A finite northeast-Pacific hard-substrate representative catalog. Anatomical
// measurements, selected display sizes and complete mesh clearance are distinct.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius, footprint) => ({
  x, y, z, horizontalRadiusUnits: radius, footprintRadiusUnits: footprint,
  axes: 'positive-x-support-tangent; positive-y-support-normal; transverse-z',
  origin: 'fixed-holdfast-contact-on-actual-native-rock-surface',
  status: 'uncalibrated-conservative-whole-display-and-animation-clearance',
});
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '东北太平洋深海硬底代表；Gorda Ridge与美国西海岸生物地理资料，非单站重建',
  coOccurrenceStatus: 'representative-community-not-a-survey-reconstruction',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  populationDensityPerM2: null, calibratedPopulationRates: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null,
  calibratedAgeSec: null, verifiedBioluminescence: null,
  bioluminescent: false, bioluminescenceStatus: 'not-verified-no-emission',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM, status: 'selected-display-gate-not-complete-natural-range' },
  depthRangeM: data.depthSelectionM,
  sourceLinks: data.sources,
  support: { mode: 'fixed-attached-to-actual-native-rock-surface',
    rootLocal: { x: 0, y: 0, z: 0 }, upwardAxis: 'positive-y-support-normal',
    contact: 'complete-holdfast-footprint-on-a-native-rock-triangle',
    simulatedLocomotion: false, measuredHoldfastSizeM: null },
  foodProxyStatus: 'new-external-flow-food-control-volume-selected-component-not-complete-natural-diet',
  individualStatus: 'independent-animal-record-with-native-clock-and-relative-energy-account',
  limitations: [
    '两种代表的文献范围重叠不证明3500米同站共现；显示数量和布局不是真实样方或自然密度。',
    '全体几何、底座、食点、流速、摄食、能量和死亡阈值为未校准展示选择；不推导年龄、繁殖或生长。',
    '食物粒子只代表选定悬浮食性部分，不是完整自然食谱或测得的碳通量；观察灯和昼夜不供能。',
  ],
  ...data,
});

export const deepHardLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'sea-lily-thalassocrinus', commonName: '深海长柄海百合',
    scientificName: 'Thalassocrinus alvinae', nameNote: '中文为描述名称，以拉丁学名确定身份。',
    kind: 'crinoid', modelRole: 'attached-sea-lily', family: 'Hyocrinidae',
    guild: 'passive-suspension-feeder', lengthM: .135,
    sizeRangeM: [.12, .15], sizeMeasure: 'arm-length',
    measurementDefinition: '单条臂从臂基到臂尖的中心线弧长；不含双侧羽枝、杯体、柄和底座。',
    depthSelectionM: [3400, 3500],
    referenceSizeM: { maximum: null, measure: 'arm-length', reportedArmLengthM: [.12, .15],
      reportedLongestPinnuleM: .038, measuredCompleteHeightM: null,
      note: 'Roux2002完整臂达12或15厘米；标本柄为不完整片段，不能把这些臂长或片段长度当成整株高度上限。' },
    referenceDepthM: { observedCollectionDepths: [3100, 3500], range: null,
      note: '原始正模3100米；副模与Figure4活体照片3500米。两点不等于本种连续完整自然深度范围。' },
    normalizedEnvelope: envelope([-1.30, 1.30], [0, 2.70], [-1.30, 1.30], 1.84, .12),
    colors: ['#b2a28b', '#d8cbb5', '#7c7668'],
    description: '细长关节柄托起小锥形杯体，五条简单长臂各有双侧细羽枝；保持海百合的长柄和羽状冠形。',
    diet: '被动悬浮摄食。海百合类群能捕获有机碎屑、粪粒、原生生物及小动物等颗粒；本种胃含物和各分量未核定。',
    behavior: '固定附着，在外部水流中以臂及羽枝接触悬浮颗粒；本版只做有限冠部姿态，不假造游走或扩繁。',
    foodPool: 'particulateOrganicFood', preferredFoodPool: 'particulateOrganicFood',
    foodProxyNote: '独立新控制体中有营养的悬浮有机颗粒选定分量；不把所有无机颗粒当食物，也不把DOM或灯光转成食物。',
    feedingEvidenceLevel: 'crinoid-group-functional-evidence-species-diet-unmeasured',
    substrate: ['hard-rock', 'exposed-basalt'], habitat: ['abyssal-hard-substrate', 'non-vent-rock-community'],
    morphology: { form: 'slender-stalk-small-conical-cup-five-simple-pinnulated-arms',
      armCount: 5, branchedArms: false, cirriStatus: 'not-added',
      sizeAxis: 'one-arm-centreline-arc-normalized-to-one',
      stalkRatioStatus: 'author-display-ratio-not-measured-whole-height',
      holdfastStatus: 'uncalibrated-contact-base-not-a-measured-complete-type-specimen',
      feedingPointLocal: { x: .80, y: 2.05, z: 0 },
      fixedFeedingPart: 'terminal-contact-on-first-positive-x-arm',
      clearanceIncludes: ['holdfast', 'entire-stalk', 'cup', 'all-five-arms', 'all-pinnules', 'bounded-crown-animation'],
      reference: 'Roux2002 Figures1/3/4; five-armed Hyocrinidae and suspension-feeding mechanics in Messing et al.2021; approximate native geometry, not a scan' },
    sources: [
      source('https://www.jstage.jst.go.jp/article/specdiv/7/2/7_KJ00003893337/_pdf/-char/en',
        'Roux2002原始分类：Gorda Ridge正副模、3100/3500米、完整臂12–15厘米及Figure4的3500米活体照片'),
      source('https://pubs.oregon.gov/dogami/ofr/O-87-05.pdf',
        'Carey等1987原始Gorda Ridge调查：岩质海百合群落、Thalassocrinus新种和悬浮摄食；后由Roux定名'),
      source('https://journals.ku.edu/treatiseonline/article/download/15390/13797/34864',
        'Messing等2021作者Treatise：五臂Hyocrinidae、外部水流、臂/羽枝接触粒子与类群食性，不是本种速率'),
    ],
  }),
  descriptor({
    id: 'alternating-quill-black-coral', commonName: '交替羽枝黑珊瑚',
    scientificName: 'Alternatipathes alternata', nameNote: '中文为形态描述；DFO资料保留cf.比较鉴定，见身份局限。',
    kind: 'black-coral', modelRole: 'attached-black-coral', family: 'Schizopathidae',
    guild: 'animal-suspension-feeder', lengthM: .275,
    sizeRangeM: [.25, .30], sizeMeasure: 'colony-height',
    measurementDefinition: '底座接触点到完整展开群体最高点的高度；不以弯曲主轴弧长或横羽枝长度替代高度。',
    depthSelectionM: [3400, 3600],
    referenceSizeM: { maximum: null, measure: 'colony-height',
      fieldGuideHeightToM: .30, californiaObservedHeightM: [.25, .35],
      reportedLongestPinnuleM: [.10, .12],
      note: 'DFO2021高度至30厘米；Graiff等2025北中加州观测25–35厘米。选择25–30厘米不宣称全种上限。' },
    referenceDepthM: { taxonomicReportedRange: [2670, 5089],
      regionalCompiledRange: [412, 4881], californiaObservedRange: [3296, 3313],
      range: [2670, 5089],
      note: '真种原分类范围2670–5089米；NOAA2022(v2021) Oregon Province汇编412–4881米，浅端不据以扩展本版；2025加州直接观测3296–3313米，未把它冒称3500米采样。' },
    identityCaveat: '以真A.alternata形态作具名代表；DFO保留cf.且历史Bathypathes alternata有误鉴。未做遗传鉴定，不移用pseudoalternata或venusta的体形、深度和尺寸。',
    normalizedEnvelope: envelope([-.16, 1.10], [0, 1.08], [-.60, .60], 1.26, .10),
    colors: ['#3d302b', '#bdab90', '#e7d6bf'],
    description: '黑色简单主轴上部向侧面弯至近水平，两列简单羽枝交替排列、下长上短并向下回弯，形成风筒状轮廓；轴羽枝旁有浅色小珊瑚虫。',
    diet: '黑珊瑚类群以刺细胞和黏液捕获悬浮小动物，动物性浮游生物是重要食物部分；本种胃含物与份额未知。',
    behavior: '底座固定在硬底，珊瑚虫触及随外部流移动的悬浮小动物；本版不模拟增长、繁殖或具名猎物捕杀。',
    foodPool: 'smallSuspendedAnimals', preferredFoodPool: 'smallSuspendedAnimals',
    foodProxyNote: '独立新控制体中的小型悬浮动物选定部分；没有具名猎物、真实自然密度或直接可视捕杀关系。',
    feedingEvidenceLevel: 'antipatharia-group-functional-evidence-species-diet-unmeasured',
    substrate: ['hard-rock'], habitat: ['abyssal-hard-substrate', 'deep-non-photosynthetic-coral'],
    morphology: { form: 'curved-near-horizontal-monopodial-axis-alternate-bilateral-simple-recurved-pinnules',
      branchOrders: 1, polypTentacleCount: 6,
      sizeAxis: 'complete-colony-highest-positive-y-normalized-to-one',
      feedingPointLocal: { x: .35, y: .35, z: .42 },
      fixedFeedingPart: 'visible-polyp-terminal-on-a-connected-positive-z-recurved-pinnule',
      clearanceIncludes: ['holdfast', 'entire-curved-axis', 'all-recurved-pinnules', 'all-polyps-and-tentacles', 'bounded-branch-animation'],
      reference: 'Molodtsova/Opresko2017 diagnosis reproduced by Lima et al.2019; DFO2021 p82; Warner2005 Antipatharia six-tentacle/holdfast functional description; approximate geometry, not a scan' },
    sources: [
      source('https://repository.library.noaa.gov/view/noaa/17609/noaa_17609_DS13.pdf',
        'Everett等2022 NOAA西海岸名录(v2021)：Oregon Province涵盖北中加州，A.alternata汇编深度412–4881米'),
      source('https://zenodo.org/records/5688370',
        'Lima等2019作者分类处理引用2017真种诊断：2670–5089米、交替羽枝、弯轴近水平与向下回弯风筒形'),
      source('https://publications.gc.ca/collections/collection_2021/mpo-dfo/Fs97-6-3433-eng.pdf',
        'DFO2021不列颠哥伦比亚珊瑚指南p82：Alternatipathes cf.alternata、高度至30厘米、羽枝与浅色珊瑚虫'),
      source('https://repository.library.noaa.gov/view/noaa/71007/noaa_71007_DS1.pdf',
        'Graiff等2025原始北中加州调查：具名A.alternata实际3296–3313米记录及25–35厘米高度'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC8833236/',
        'Molodtsova等2022原始分类：历史Bathypathes alternata误鉴及B.pseudoalternata的区别'),
      source('https://archivo.revistas.ucr.ac.cr/index.php/rbt/article/download/26620/26825/70777',
        'Warner2005原始黑珊瑚调查的目级功能描述：硬底holdfast、六触手与动物性悬浮摄食；非本种站点速率'),
      source('https://doi.org/10.1016/B978-0-12-394282-1.00002-8',
        'Wagner等2012作者黑珊瑚生物学综述：刺细胞/黏液和动物性浮游食物；本种完整食谱未知'),
    ],
  }),
]);
export const deepHardLifeSpeciesById = freeze(Object.fromEntries(
  deepHardLifeSpeciesCatalog.map(species => [species.id, species]),
));
