// One finite northeast-Pacific soft-bottom representative catalog. Source
// ranges, selected display dimensions and mesh clearance are separate facts.
// In particular the two genus representatives are not identified species.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius) => ({ x, y, z, horizontalRadiusUnits: radius,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-conservative-display-clearance-not-measured-anatomy' });
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '东北太平洋深海泥底代表组合；加州外海与北太平洋资料参考，非单一站位重建',
  coOccurrenceStatus: 'representative-community-not-a-survey-reconstruction',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  populationDensityPerM2: null, calibratedPopulationRates: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null,
  calibratedAgeSec: null, verifiedBioluminescence: null,
  bioluminescent: false, bioluminescenceStatus: 'not-verified-no-emission',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM, status: 'illustrative-selection-not-complete-taxon-range' },
  depthRangeM: data.depthSelectionM,
  foodProxyStatus: 'existing-relative-food-pool-selected-component-not-complete-natural-diet',
  limitations: ['显示尺寸、水深、数量、步速、摄食、代谢和几何包络是未校准选择，不是当地样方或体长年龄曲线。',
    '深度范围重叠只支持类群准入，不能证明3500米同地共现；不增加光合生产、自由食物、繁殖或具名猎物关系。'],
  ...data,
});

export const deepBenthicLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'abyssal-brittle-star', commonName: '深渊长臂蛇尾', scientificName: 'Ophiosphalma glabrum',
    nameNote: '中文为描述性名称，分类身份由拉丁学名确定。',
    kind: 'brittle-star', guild: 'opportunistic-omnivore', lengthM: .14,
    sizeRangeM: [.10, .18], sizeMeasure: 'arm-span', depthSelectionM: [3400, 3600],
    referenceSizeM: { maximum: null, measure: 'arm-span',
      note: '本轮未核定全臂展开跨距上限；10–18厘米是作者展示选择，盘径与完整跨距不能互换。' },
    referenceDepthM: { range: [878, 5203],
      note: '2025年原始名录汇总范围覆盖3500米；2000年原始调查记录于Monterey及Pioneer峡谷，调查本身未到3500米。' },
    normalizedEnvelope: envelope([-.55, .55], [0, .12], [-.55, .55], .62),
    colors: ['#a58e77', '#c2b19b', '#746756'],
    description: '小而明确的中央盘与五条细长渐尖关节臂，臂缘有短棘，保持蛇尾轮廓；不是浅礁粗臂海星。',
    diet: '机会型杂食；2025年原始食性研究支持植物性沉降碎屑、细菌、甲壳类及有孔虫等来源。',
    behavior: '以臂在泥面推进或探寻食物；自然也有掩埋及与其他底栖体关联，本版只实现受支撑的短距离泥面活动。',
    preferredFoodPool: 'surfaceDetritus',
    foodProxyNote: '现有表面碎屑池只代表自然食谱中的一个部分，未模拟真实有孔虫、海绵、甲壳猎物或全套微生物食性。',
    substrate: ['soft-mud', 'sediment-surface'], habitat: ['abyssal-soft-bottom'],
    morphology: { form: 'small-distinct-disc-five-long-articulated-tapered-arms', armCount: 5,
      sizeAxis: 'whole-arm-span-xz', footRootY: 0, clearanceIncludes: ['disc', 'all-five-arms', 'arm-spines'],
      reference: 'Seid et al. 2025 Figure 64A/B, identified live specimen E7046; approximate representative, not scan' },
    sources: [
      source('https://www.sciencedirect.com/org/science/article/pii/S1313298925000011',
        'Seid等（2025）原始名录：O. glabrum东北太平洋分布、878–5203米及标注活体背腹面Figure64A/B'),
      source('https://darwinweb.africamuseum.be/echinodermata_v2/index.php/docman0/documents-public/894-summers-and-nybakken-2000/file',
        'Summers与Nybakken（2000）原始Monterey/Pioneer调查Table1：当地记录与参考深度分别'),
      source('https://www.vliz.be/imisdocs/publications/419159.pdf',
        'Stratmann等（2025）原始食性研究：东部CCZ蛇尾杂食与泥面/掩埋行为，非本场实测速率'),
    ],
  }),
  descriptor({
    id: 'pyramid-urchin', commonName: '深海金字塔海胆', scientificName: 'Echinocrepis rostrata',
    kind: 'urchin', guild: 'sediment-deposit-feeder', lengthM: .06,
    sizeRangeM: [.045, .075], sizeMeasure: 'test-length', depthSelectionM: [3400, 3600],
    referenceSizeM: { maximum: null, measure: 'test-length',
      note: '本轮不采用未经核定的尺寸上限；4.5–7.5厘米为壳体前后长选择，短棘和管足另计净空。' },
    referenceDepthM: { range: [3315, 5020],
      note: '2024年原始论文列北太平洋3315–5020米；参考标本与Station M摄食研究并非本场3500米调查。' },
    normalizedEnvelope: envelope([-.58, .60], [0, .90], [-.52, .52], .80),
    colors: ['#ae8f78', '#8c6c58', '#c7ae93'],
    description: '非规则高耸金字塔形壳体，前后不对称，表面有细短棘，底部具支撑管足；不用浅海海胆的球形长刺轮廓。',
    diet: '摄取软泥中的沉降有机碎屑；原始同位素研究还强调肠道微生物加工提供的营养，不能把动物体等同未经加工的碎屑。',
    behavior: '贴近泥面缓慢推进摄食，自然可扰动浅层沉积物；本版不修改海床网格、不凭空预铺痕迹。',
    preferredFoodPool: 'surfaceDetritus',
    foodProxyNote: '扣除现有表面碎屑相对库存，未建立实测沉积层、肠道微生物或碳通量模型。',
    substrate: ['soft-mud', 'sediment-surface'], habitat: ['abyssal-soft-bottom'],
    morphology: { form: 'high-pyramidal-irregular-test-fine-short-spines-and-basal-tube-feet',
      sizeAxis: 'test-long-axis-x-excluding-spines', footRootY: 0,
      clearanceIncludes: ['test', 'short-spines', 'tube-feet'],
      reference: '2024 original mitogenome paper Figure 1A, labeled SIO-BIC E4015 aboral/lateral reference' },
    sources: [
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC10962292/',
        '2024年原始线粒体论文：E. rostrata北太平洋3315–5020米、高金字塔壳体与标本Figure1A'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC8206261/',
        '2021年原始Station M营养研究：沉积摄食与肠道微生物营养，约4000米并非本场实测'),
    ],
  }),
  descriptor({
    id: 'acorn-worm-group', commonName: '背帷肠鳃类（属代表）', scientificName: 'Tergivelum spp.',
    identityLevel: 'genus-group', taxonomicLevel: 'genus', kind: 'worm', guild: 'surface-deposit-feeder', lengthM: .18,
    sizeRangeM: [.12, .24], sizeMeasure: 'body-length', depthSelectionM: [3400, 3600],
    referenceSizeM: { range: [.09, .28], measure: 'body-length',
      note: '2009年T. baldwinae活体参考标本9–28厘米；这里只用其参考形态，不推广全属尺寸或确认本场种身份。' },
    referenceDepthM: { range: [2712, 3954], referenceTaxon: 'Tergivelum baldwinae',
      note: '2012年原始论文Table1记录加州中部至华盛顿海域沉积底参考种范围；4000米Station M照片是独立实例。' },
    normalizedEnvelope: envelope([-.58, .62], [0, .16], [-.20, .20], .69),
    colors: ['#705746', '#ab927c', '#c7b599'],
    description: '浅圆穹形吻部、宽领和一对向后覆在前躯上的侧背帷，深褐前端接米褐长软躯；无脚、无眼和无分节环。',
    diet: '沿泥面摄取沉降有机物；不是光合动物，不能用观察灯强度生成营养。',
    behavior: '贴泥面缓慢摄食与短距离推进。参考类群自然可能借底流漂移，本版不模拟浮游、迁入或预铺螺旋粪痕。',
    preferredFoodPool: 'surfaceDetritus',
    foodProxyNote: '使用现有表面碎屑相对池；未模拟真实沉积层、排泄物质量或完整生物扰动轨迹。',
    substrate: ['soft-mud', 'sediment-surface'], habitat: ['deep-epibenthic-sediment'],
    morphology: { form: 'dome-proboscis-broad-collar-paired-back-veils-long-unsegmented-trunk',
      sizeAxis: 'complete-body-long-axis-x', footRootY: 0, legs: false,
      clearanceIncludes: ['proboscis', 'collar', 'both-back-veils', 'complete-trunk'],
      reference: 'Holland et al. 2009 T. baldwinae Figures 2/3 and MBARI labeled 15cm Station M photograph; genus representative' },
    sources: [
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC3282343/',
        'Osborn等（2012）原始论文Table1：T. baldwinae沉积底2712–3954米与地理/分类证据'),
      source('https://doi.org/10.5252/z2009n2a6',
        'Holland等（2009）原始分类描述：活体长、前后颜色、吻/领/成对背帷；Figures2/3'),
      source('https://www.mbari.org/news/a-bountiful-harvest-of-deep-sea-acorn-worms/',
        'MBARI标注实例：Station M约4000米、15厘米T. baldwinae照片与泥面摄食；不冒充3500米本场个体'),
    ],
  }),
  descriptor({
    id: 'deep-amphipod-group', commonName: '深海端足类（属代表）', scientificName: 'Eurythenes spp.',
    identityLevel: 'genus-group', taxonomicLevel: 'genus', kind: 'crustacean', guild: 'animal-scavenger', lengthM: .06,
    sizeRangeM: [.04, .075], sizeMeasure: 'body-length', depthSelectionM: [3400, 3600],
    referenceSizeM: { historicalComplexMaximum: .154, measure: 'body-length',
      note: '2015年原始修订引述旧E. gryllus广义复合群最大154毫米；不能作为任何现代命名种统一上限。' },
    referenceDepthM: { range: [550, 7800], referenceTaxon: 'historical-Eurythenes-gryllus-sensu-lato-complex',
      northPacificSampleDepthsM: [3193, 3982, 4920, 5178, 5770],
      note: '2013年原始论文Table1的北太平洋样本与旧复合群范围，另有加州至中北太平洋调查；未核得加州3500米同地记录。' },
    normalizedEnvelope: envelope([-.70, .84], [0, .44], [-.26, .26], .90),
    colors: ['#bca68c', '#9c8067', '#d1bda2'],
    description: '侧扁弯曲的分节体、两对触角、七对胸肢（前两对为颚足）、三对腹部游泳肢和后端尾肢；没有对虾式背甲或螃蟹双螯。',
    diet: '参考复合群以动物腐肉为主要食物，具游泳和食物搜索能力；本场未识别现代具名种或指定真实尸体来源。',
    behavior: '本版限定在实际泥面附近短距离探寻和停食，保持与库存代理的空间联系；不模拟自然长距离游泳聚集或快速繁殖。',
    preferredFoodPool: 'benthicAnimalFood',
    foodProxyNote: '现有底层动物性食物池是未分辨营养代理，不代表可见尸体、鱼/海参被捕杀或完整自然腐食链。',
    substrate: ['soft-mud', 'sediment-surface'], habitat: ['deep-near-bottom'],
    morphology: { form: 'laterally-compressed-segmented-amphipod-paired-antennae-pereiopods-pleopods-uropods',
      sizeAxis: 'body-rostrum-to-telson-x-excluding-antennae-and-uropods', footRootY: 0,
      antennaPairs: 2, thoracicLimbPairs: 7, gnathopodPairs: 2, pleopodPairs: 3,
      clearanceIncludes: ['body', 'both-antenna-pairs', 'thoracic-limbs', 'pleopods', 'uropods'],
      reference: 'Stoddart & Lowry 2004 E. gryllus sensu lato treatment/Figures1–11; morphology-only genus reference, not E. gryllus sensu stricto identification' },
    sources: [
      source('https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0074218',
        'Havermans等（2013）原始遗传/形态论文：北太平洋深度样本、腐食与多个谱系，阻止误标具名种'),
      source('https://www.sciencedirect.com/science/article/abs/pii/0198014987900549',
        'Bucklin等（1987）原始调查：加州外海至中北太平洋复合群样本，非本场同地记录'),
      source('https://mapress.com/zootaxa/2015/f/z03971p080f.pdf',
        'd’Udekem d’Acoz与Havermans（2015）原始修订摘要：旧复合群分化、现代E. gryllus与深渊种不可混用'),
      source('https://tb.plazi.org/GgServer/html/2D09EC23E90EFFADFFDDFDE9FF75FAA6',
        'Stoddart与Lowry（2004）原始形态处理数字转录：两对触角、胸肢/尾肢与标注Figures1–11；采用属级轮廓'),
    ],
  }),
]);

export const deepBenthicLifeSpeciesById = freeze(Object.fromEntries(
  deepBenthicLifeSpeciesCatalog.map(row => [row.id, row])));
