import { deepMidwaterLifeSpeciesCatalog, deepMidwaterLifeSpeciesById } from './deepMidwaterLifeSpecies.js';

const freeze = x => { if (x && typeof x === 'object' && !Object.isFrozen(x)) { Object.values(x).forEach(freeze); Object.freeze(x); } return x; };
export const DEEP_MIDWATER_LIFE_VERSION = 1;
export const DEEP_MIDWATER_LIFE_IDS = Object.freeze(deepMidwaterLifeSpeciesCatalog.map(s => s.id));
export const DEEP_MIDWATER_LIFE_FOOD_POOLS = Object.freeze([...new Set(deepMidwaterLifeSpeciesCatalog.map(s => s.foodPool))]);
export const DEEP_MIDWATER_LIFE_FOOD_SCOPE = 'Independent initially-zero bounded midwater suspension control volumes: selected animal plankton or organic-particle nutrition as specified in the species catalog. Fixed seeded upstream sources, foodSupply/current-dependent external input, constant-Y positive-X transport, actual saved capture-organ contact and accounted outlet/support export. No bottom-food lift, original-stock transfer, visible kill, full natural diet, calibrated food flux, biomass, observer-light or hour input.';
export const DEEP_MIDWATER_LIFE_MODEL = freeze({ maximumAdded: 3, allocationProbability: .80, centreRadiusM: 2, maximumHomeExtentM: 3,
  wholeBodyClearanceM: .015, maximumPitchRad: .12, maximumTurnRadSec: .6, maximumPitchTurnRadSec: .15, pathProbeSpacingM: .02,
  maximumChannels: 3, maximumParcels: 32, maximumParcelsPerChannel: 4, maximumParcelAmount: .0016, sourceDistanceM: .6,
  outletDistanceM: 2.6, sourceReleaseIntervalTicks: 20, sourceInputUnitsPerSec: .00004, referenceFlowMps: .18, transportProbeSpacingM: .01,
  captureDistanceM: .12, biteAmount: .00012, biteIntervalSec: 6, decisionIntervalSec: 1.5,
  energyGainPerUnit: 2, maintenanceDebitPerSec: .000025, motionDebitPerM: .00015, flowDebitPerSec: .00002,
  traits: Object.fromEntries(deepMidwaterLifeSpeciesCatalog.map(s => [s.id, { speedMps: s.kind === 'jellyfish' ? .04 : s.kind === 'cephalopod' ? .065 : .075 }])),
  note: 'Three independent source-qualified complete-form swimmers in a compact owner-local midwater community. Sizes, speeds, capture distances, nutrition units, source flux and relative-condition rates are authored and uncalibrated. The whole body, appendages, turn and bounded path use actual water depth and seabed clearance. Existing bottom populations, generation RNG, native and hard food ledgers are untouched. No recruitment, migration, vertical diel migration, offline evolution or refill; no global collision proof. A fixed representative capture structure accounts selected nutrition, not a calibrated full feeding sequence.',
});
const M = DEEP_MIDWATER_LIFE_MODEL, SIZE = 64, TAU = Math.PI * 2, CONDITION = 'dimensionless relative condition in independent energy ledger; not biomass or organic food stock';
const FIELDS = ['deepMidwaterLifeVersion', 'deepMidwaterLifeInitializedAtSec', 'deepMidwaterLife', 'deepMidwaterLifeAgents', 'deepMidwaterEnergyLedger'];
const AGENT_FIELDS = ['deepMidwaterIndividualVersion', 'deepMidwaterSiteId', 'deepMidwaterFoodChannelId'];
const clone = x => structuredClone(x), vector = p => p && ['x', 'y', 'z'].every(k => Number.isFinite(p[k]));
const nonnegative = n => Number.isFinite(n) && n >= 0, close = (a, b, e = 1e-8) => Number.isFinite(a) && Number.isFinite(b) && Math.abs(a - b) <= e;
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z), clamp = (n, lo, hi) => Math.max(lo, Math.min(hi, n));
const marked = x => x && Object.keys(x).some(k => k.startsWith('deepMidwater'));
const olderMarked = x => x && Object.keys(x).some(k => k.startsWith('deepBenthic') || k.startsWith('deepHard') || k.startsWith('deepWater') || k.startsWith('predator') || k.startsWith('kelp'));
export const isDeepMidwaterLifeAgent = a => DEEP_MIDWATER_LIFE_IDS.includes(a?.speciesId);
const disguised = x => marked(x) || isDeepMidwaterLifeAgent(x) || typeof x?.id === 'string' && x.id.startsWith('deep-midwater-');
const sourceOf = a => deepMidwaterLifeSpeciesById[a?.speciesId];
const exactKeys = (x, keys) => x && Object.keys(x).length === keys.length && keys.every(k => Object.hasOwn(x, k));
const boundedText = x => typeof x === 'string' && x.trim().length > 0 && x.length <= 240;
function hash(text) { let h = 2166136261; for (const c of String(text)) h = Math.imul(h ^ c.charCodeAt(0), 16777619); h ^= h >>> 16; h = Math.imul(h, 0x7feb352d); h ^= h >>> 15; h = Math.imul(h, 0x846ca68b); return (h ^ h >>> 16) >>> 0; }
const randomFor = (g, r) => salt => hash(`deep-midwater-life-v1|${typeof g.seed}:${g.seed}|${r.id}|${salt}`) / 4294967296;
const geometryOwner = (g, r) => g?.surfaceY === 3500 && typeof g.heightAt === 'function' && Number.isSafeInteger(r?.cx) && Number.isSafeInteger(r?.cz) && r.id === `${r.cx},${r.cz}`;
const nativeOwner = (g, r) => geometryOwner(g, r) && r.sim && Array.isArray(r.sim.agents) && Number.isSafeInteger(r.sim._ticks) && r.sim._ticks >= 0 && close(r.sim.timeSec, r.sim._ticks * .1);
const oldResidents = r => [...(r.sim?.agents ?? []), ...(r.predatorAgents ?? []), ...(r.deepBenthicAgents ?? []), ...(r.deepHardLifeAgents ?? []), ...(r.deepWaterLifeAgents ?? [])];
const owns = (r, p, margin = .5) => vector(p) && p.x >= r.cx * SIZE + margin && p.x <= (r.cx + 1) * SIZE - margin && p.z >= r.cz * SIZE + margin && p.z <= (r.cz + 1) * SIZE - margin && Math.hypot(p.x, p.z) > 46;
function frame(h, p) { const c = Math.cos(h), s = Math.sin(h), cp = Math.cos(p), sp = Math.sin(p); return { forward: { x: c * cp, y: sp, z: s * cp }, up: { x: -c * sp, y: cp, z: -s * sp }, side: { x: -s, y: 0, z: c } }; }
function offset(a, point, heading = a.heading, pitch = a.pitch) { const f = frame(heading, pitch); return Object.fromEntries(['x', 'y', 'z'].map(k => [k, a.sizeM * (f.forward[k] * point.x + f.up[k] * point.y + f.side[k] * point.z)])); }
export function deepMidwaterLifeBodyPoints(a, root = a?.position, heading = a?.heading, pitch = a?.pitch) {
  const e = sourceOf(a)?.normalizedEnvelope; if (!e || !vector(root) || !(a.sizeM > 0) || !Number.isFinite(heading) || !Number.isFinite(pitch)) return [];
  const points = []; for (const x of [e.x[0], (e.x[0] + e.x[1]) / 2, e.x[1]]) for (const y of [e.y[0], (e.y[0] + e.y[1]) / 2, e.y[1]]) for (const z of [e.z[0], (e.z[0] + e.z[1]) / 2, e.z[1]]) { const q = offset(a, { x, y, z }, heading, pitch); points.push({ x: root.x + q.x, y: root.y + q.y, z: root.z + q.z }); } return points;
}
export function deepMidwaterLifeFeedingPosition(a) { const ref = sourceOf(a)?.morphology?.foodCapturePointLocal ?? sourceOf(a)?.morphology?.feedingPointLocal;
  if (!vector(a?.position) || !vector(ref) || !Number.isFinite(a.heading) || !Number.isFinite(a.pitch)) return null; const q = offset(a, ref); return Object.fromEntries(['x', 'y', 'z'].map(k => [k, a.position[k] + q[k]])); }
function bounds(a) { const points = isDeepMidwaterLifeAgent(a) ? deepMidwaterLifeBodyPoints(a) : []; return Object.fromEntries(['x', 'y', 'z'].map(k => [k, points.length ? [Math.min(...points.map(p => p[k])), Math.max(...points.map(p => p[k]))] : [a.position[k] - (a.sizeM ?? .3) * .8, a.position[k] + (a.sizeM ?? .3) * .8]])); }
function peersClear(r, a, extra = []) { const b = bounds(a); return [...oldResidents(r), ...(r.deepMidwaterLifeAgents ?? []), ...extra].every(p => p.id === a.id || !p.alive || !vector(p.position) || ['x', 'y', 'z'].some(k => b[k][1] + .02 <= bounds(p)[k][0] || bounds(p)[k][1] + .02 <= b[k][0])); }
export function deepMidwaterLifePositionValid(g, r, a, position = a?.position, heading = a?.heading, pitch = a?.pitch, { occupancy = false, extra = [] } = {}) {
  if (!geometryOwner(g, r) || !isDeepMidwaterLifeAgent(a) || !vector(position) || !(a.sizeM > 0) || !Number.isFinite(heading) || !Number.isFinite(pitch) || Math.abs(pitch) > M.maximumPitchRad + 1e-10 || (sourceOf(a).kind === 'jellyfish' && pitch !== 0) || vector(a.home) && distance(position, a.home) > M.maximumHomeExtentM + 1e-8) return false;
  const points = deepMidwaterLifeBodyPoints(a, position, heading, pitch), [lo, hi] = sourceOf(a).depthSelectionM;
  if (points.length !== 27 || points.some(p => !owns(r, p) || !Number.isFinite(g.heightAt(p.x, p.z)) || p.y < g.heightAt(p.x, p.z) + M.wholeBodyClearanceM || g.surfaceY - p.y < lo || g.surfaceY - p.y > hi)) return false;
  return !occupancy || peersClear(r, { ...a, position, heading, pitch }, extra);
}
function birthAt(g, r, s, index) { const random = randomFor(g, r), angle = index * TAU / deepMidwaterLifeSpeciesCatalog.length + random('group-heading') * TAU, sizeM = s.sizeRangeM[0] + random(`${s.id}:size`) * (s.sizeRangeM[1] - s.sizeRangeM[0]), heading = (random(`${s.id}:heading`) - .5) * .7,
    depth = (Math.max(...deepMidwaterLifeSpeciesCatalog.map(s => s.depthSelectionM[0])) + Math.min(...deepMidwaterLifeSpeciesCatalog.map(s => s.depthSelectionM[1]))) / 2,
    position = { x: (r.cx + .5) * SIZE + Math.cos(angle) * M.centreRadiusM, y: g.surfaceY - depth + (random(`${s.id}:height`) - .5) * 1.2, z: (r.cz + .5) * SIZE + Math.sin(angle) * M.centreRadiusM },
    a = { id: `deep-midwater-life:${r.id}:${s.id}`, speciesId: s.id, deepMidwaterSiteId: `deep-midwater-site:${r.id}:${index}`, deepMidwaterFoodChannelId: `deep-midwater-channel:${r.id}:${s.id}`, sizeM, heading, pitch: 0, position,
      nutritionPool: s.foodPool, habitat: 'native-deep-water-column', alive: true };
  if (!deepMidwaterLifePositionValid(g, r, a)) return null; const referencePosition = deepMidwaterLifeFeedingPosition(a), sourcePosition = { x: referencePosition.x - M.sourceDistanceM, y: referencePosition.y, z: referencePosition.z };
  if (!owns(r, sourcePosition, .8) || g.heightAt(sourcePosition.x, sourcePosition.z) >= sourcePosition.y - M.wholeBodyClearanceM) return null;
  return { ...a, sourcePosition, referencePosition };
}
/** Pure role depends only on the original geometry, catalog and salted owner coordinates. */
export function deepMidwaterLifeRole(g, cx, cz) { const r = { id: `${cx},${cz}`, cx, cz }; return Boolean(geometryOwner(g, r) && randomFor(g, r)('role') < M.allocationProbability && deepMidwaterLifeSpeciesCatalog.some((s, i) => birthAt(g, r, s, i))); }
export function createDeepMidwaterLifePlan(g, r, { availableSlots = 0, maxAdded = 3 } = {}) {
  const placements = [], channels = [], role = deepMidwaterLifeRole(g, r?.cx, r?.cz), limit = Math.min(M.maximumAdded, Math.max(0, Math.floor(Number.isFinite(availableSlots) ? availableSlots : 0)), Math.max(0, Math.floor(Number.isFinite(maxAdded) ? maxAdded : 0)));
  if (nativeOwner(g, r) && role) for (const [i, s] of deepMidwaterLifeSpeciesCatalog.entries()) { if (placements.length >= limit) break; const a = birthAt(g, r, s, i); if (!a || !peersClear(r, a, placements)) continue; placements.push(a);
    channels.push({ id: a.deepMidwaterFoodChannelId, agentId: a.id, pool: a.nutritionPool, sourcePosition: clone(a.sourcePosition), referencePosition: clone(a.referencePosition), sourceDistanceM: M.sourceDistanceM,
      releaseChecks: 0, nextReleaseTick: 1, inputPulses: 0, inputUnits: 0, ingestedUnits: 0, exportedUnits: 0, parcels: [] }); }
  return freeze({ version: 1, role, placements, channels });
}
const blank = () => ({ initial: 0, input: 0, ingested: 0, exported: 0 });
export function initializeDeepMidwaterLife(g, r, { fresh = false, capacity = 20, maxAdded = 3 } = {}) {
  if (!fresh || !nativeOwner(g, r) || r.sim._ticks !== 0 || r.sim.timeSec !== 0 || marked(r) || oldResidents(r).some(disguised) || !Number.isSafeInteger(capacity) || capacity < 0 || capacity > 20 || oldResidents(r).length > capacity || !Number.isSafeInteger(maxAdded) || maxAdded < 0 || maxAdded > M.maximumAdded) return false;
  const p = createDeepMidwaterLifePlan(g, r, { availableSlots: capacity - oldResidents(r).length, maxAdded }), random = randomFor(g, r);
  r.deepMidwaterLifeAgents = p.placements.map(a => ({ ...clone(a), deepMidwaterIndividualVersion: 1, regionId: r.id, createdAtSec: 0, timeSec: 0, stateSince: 0, state: 'drifting', energy: .68 + random(`${a.id}:condition`) * .12,
    home: clone(a.position), target: clone(a.position), targetHeading: a.heading, targetPitch: 0, velocity: { x: 0, y: 0, z: 0 }, nextDecision: 0, decisions: 0, nextBite: 0, travelledM: 0, feedingCount: 0, consumedUnits: 0,
    lastFeedAt: null, lastMidwaterIntake: null, foodScope: DEEP_MIDWATER_LIFE_FOOD_SCOPE, conditionScope: CONDITION, localEnvironment: clone(r.sim.environment) }));
  r.deepMidwaterLifeVersion = 1; r.deepMidwaterLifeInitializedAtSec = 0; r.deepMidwaterLife = { version: 1, role: p.role, allocation: { capacity, maxAdded }, scope: M.note, foodScope: DEEP_MIDWATER_LIFE_FOOD_SCOPE, birthPlacements: clone(p.placements), addedIds: p.placements.map(a => a.id), channels: clone(p.channels), nextParcelId: 0, lastTickSec: 0,
    foodLedger: { ...blank(), byPool: Object.fromEntries(DEEP_MIDWATER_LIFE_FOOD_POOLS.map(pool => [pool, blank()])) }, counters: { ticks: 0, inputPulses: 0, feedings: 0, consumedUnits: 0, deaths: 0 }, events: [] };
  r.deepMidwaterEnergyLedger = { initial: r.deepMidwaterLifeAgents.reduce((n, a) => n + a.energy, 0), feedingGain: 0, maintenanceAndMotionDebit: 0, clampCorrection: 0, deathLoss: 0 }; return true;
}
export function captureDeepMidwaterLife(r) { return Object.hasOwn(r, 'deepMidwaterLifeVersion') ? Object.fromEntries(FIELDS.map(k => [k, clone(r[k])])) : {}; }
const parcels = r => (r.deepMidwaterLife?.channels ?? []).flatMap(c => c.parcels);
const resources = r => Object.fromEntries(DEEP_MIDWATER_LIFE_FOOD_POOLS.map(pool => [pool, parcels(r).filter(p => p.pool === pool).reduce((n, p) => n + p.amount, 0)]));
export function deepMidwaterLifeFoodBudgetError(r) { const d = r?.deepMidwaterLife; if (!d) return 0; const stock = resources(r), l = d.foodLedger; let error = Math.abs(Object.values(stock).reduce((a, b) => a + b, 0) - (l.initial + l.input - l.ingested - l.exported));
  for (const [pool, amount] of Object.entries(stock)) { const p = l.byPool[pool]; error = Math.max(error, Math.abs(amount - (p.initial + p.input - p.ingested - p.exported))); }
  for (const c of d.channels) error = Math.max(error, Math.abs(c.parcels.reduce((n, p) => n + p.amount, 0) - (c.inputUnits - c.ingestedUnits - c.exportedUnits))); return error; }
export const deepMidwaterLifeBudgetError = deepMidwaterLifeFoodBudgetError;
export function deepMidwaterLifeEnergyBudgetError(r) { const l = r?.deepMidwaterEnergyLedger; return l ? (r.deepMidwaterLifeAgents ?? []).reduce((n, a) => n + a.energy, 0) - (l.initial + l.feedingGain - l.maintenanceAndMotionDebit + l.clampCorrection - l.deathLoss) : 0; }
function ledgerDelta(d, c, kind, amount) { d.foodLedger[kind] += amount; d.foodLedger.byPool[c.pool][kind] += amount; c[`${kind}Units`] += amount; }
function state(a, next, time) { if (a.state !== next) { a.state = next; a.stateSince = time; } }
function move(g, r, a, dt) { const old = clone(a.position), turn = Math.atan2(Math.sin(a.targetHeading - a.heading), Math.cos(a.targetHeading - a.heading)), h = a.heading + clamp(turn, -M.maximumTurnRadSec * dt, M.maximumTurnRadSec * dt), t = a.pitch + clamp(a.targetPitch - a.pitch, -M.maximumPitchTurnRadSec * dt, M.maximumPitchTurnRadSec * dt), gap = distance(old, a.target), length = Math.min(gap, M.traits[a.speciesId].speedMps * dt);
  for (const fraction of [1, .5, 0]) { const p = Object.fromEntries(['x', 'y', 'z'].map(k => [k, old[k] + (gap > 0 ? (a.target[k] - old[k]) / gap * length * fraction : 0)])); let valid = true;
    for (const step of [0, .5, 1]) { const q = Object.fromEntries(['x', 'y', 'z'].map(k => [k, old[k] + (p[k] - old[k]) * step])); if (!deepMidwaterLifePositionValid(g, r, a, q, a.heading + (h - a.heading) * step, a.pitch + (t - a.pitch) * step, { occupancy: true })) { valid = false; break; } }
    if (!valid) continue; a.heading = h; a.pitch = t; a.position = p; a.velocity = Object.fromEntries(['x', 'y', 'z'].map(k => [k, (p[k] - old[k]) / dt])); const moved = distance(p, old); a.travelledM += moved; return moved;
  } a.velocity = { x: 0, y: 0, z: 0 }; return 0;
}
function decide(g, r, a, c, clock, flow) { const random = randomFor(g, r), birth = r.deepMidwaterLife.birthPlacements.find(p => p.id === a.id); a.decisions++; a.nextDecision = clock + M.decisionIntervalSec;
  let position, heading = birth.heading, pitch = 0;
  if (clock >= a.nextBite && c.parcels.length) { const p = [...c.parcels].sort((p, q) => distance(p.position, c.referencePosition) - distance(q.position, c.referencePosition) || p.ordinal - q.ordinal)[0], q = offset(a, sourceOf(a).morphology.foodCapturePointLocal ?? sourceOf(a).morphology.feedingPointLocal, heading, pitch), targetX = clamp(p.position.x + flow * .8, c.referencePosition.x - .6, c.referencePosition.x + .6);
    position = { x: targetX - q.x, y: p.position.y - q.y, z: p.position.z - q.z }; state(a, 'seeking-suspension', clock);
  } else { const angle = random(`${a.id}:decision:${a.decisions}:angle`) * TAU, radius = .5 + random(`${a.id}:decision:${a.decisions}:radius`) * .25;
    position = { x: a.home.x + Math.cos(angle) * radius, y: a.home.y + (random(`${a.id}:decision:${a.decisions}:height`) - .5) * .3, z: a.home.z + Math.sin(angle) * radius }; state(a, 'drifting', clock); }
  if (deepMidwaterLifePositionValid(g, r, a, position, heading, pitch, { occupancy: true })) { a.target = position; a.targetHeading = heading; a.targetPitch = pitch; }
}
function intakeValid(a, r) { const w = a.lastMidwaterIntake; if (w === null) return a.lastFeedAt === null && a.feedingCount === 0 && a.consumedUnits === 0; const d = r.deepMidwaterLife, c = d.channels.find(c => c.id === a.deepMidwaterFoodChannelId);
  if (!w || !c || w.ownerId !== r.id || w.channelId !== c.id || w.pool !== c.pool || w.unit !== 'relative-organic-food-proxy-unit' || w.scope !== DEEP_MIDWATER_LIFE_FOOD_SCOPE || w.allowedDistanceM !== M.captureDistanceM || !nonnegative(w.timeSec) || w.timeSec !== a.lastFeedAt || w.timeSec > a.timeSec || !['stockBefore', 'stockAfter', 'removedUnits', 'energyBefore', 'energyAfter', 'contactDistanceM', 'parcelTravelM', 'parcelCreatedAtSec'].every(k => nonnegative(w[k])) || !(w.removedUnits > 0) || w.removedUnits > M.biteAmount + 1e-10 || w.stockBefore > M.maximumParcelAmount + 1e-10 || !close(w.stockBefore - w.stockAfter, w.removedUnits) || !close(w.energyAfter, Math.min(1, w.energyBefore + w.removedUnits * M.energyGainPerUnit)) || w.parcelCreatedAtSec > w.timeSec || !['sourcePosition', 'foodPosition', 'agentPosition', 'feedingPosition'].every(k => vector(w[k])) || !Number.isFinite(w.agentHeading) || !Number.isFinite(w.agentPitch) || w.contactDistanceM > M.captureDistanceM + 1e-10 || !close(distance(w.foodPosition, w.feedingPosition), w.contactDistanceM) || !Number.isSafeInteger(w.parcelOrdinal) || w.parcelOrdinal < 1 || w.parcelOrdinal > d.nextParcelId || w.parcelId !== `deep-midwater-parcel:${r.id}:${w.parcelOrdinal}` || !['x', 'y', 'z'].every(k => close(w.sourcePosition[k], c.sourcePosition[k])) || !close(w.foodPosition.x, c.sourcePosition.x + w.parcelTravelM) || !close(w.foodPosition.y, c.sourcePosition.y) || !close(w.foodPosition.z, c.sourcePosition.z)) return false;
  const historical = { ...a, position: w.agentPosition, heading: w.agentHeading, pitch: w.agentPitch }, organ = deepMidwaterLifeFeedingPosition(historical);
  return deepMidwaterLifePositionValid(r._midwaterValidationGenerator, r, historical) && ['x', 'y', 'z'].every(k => close(w.feedingPosition[k], organ[k]));
}
function validate(raw, r, g, capacity, pending, allocation) {
  const old = [...(raw?.state?.agents ?? r?.sim?.agents ?? []), ...(raw?.predatorAgents ?? r?.predatorAgents ?? []), ...(raw?.deepBenthicAgents ?? r?.deepBenthicAgents ?? []), ...(raw?.deepHardLifeAgents ?? r?.deepHardLifeAgents ?? []), ...(raw?.deepWaterLifeAgents ?? r?.deepWaterLifeAgents ?? [])];
  if (marked(raw?.state) || old.some(disguised) || ['surfacePatches', 'benthicPatches', 'suspendedPatches'].some(k => (raw?.state?.[k] ?? r?.sim?.[k] ?? []).some(disguised))) return false;
  if (!marked(raw)) return true;
  if (!nativeOwner(g, r) || !Number.isSafeInteger(capacity) || capacity < 0 || capacity > 20 || Object.keys(raw).some(k => k.startsWith('deepMidwater') && !FIELDS.includes(k)) || !FIELDS.every(k => Object.hasOwn(raw, k)) || raw.deepMidwaterLifeVersion !== 1 || raw.deepMidwaterLifeInitializedAtSec !== 0 || !Array.isArray(raw.deepMidwaterLifeAgents) || raw.deepMidwaterLifeAgents.length > M.maximumAdded || old.length + raw.deepMidwaterLifeAgents.length > capacity) return false;
  const d = raw.deepMidwaterLife, agents = raw.deepMidwaterLifeAgents, energy = raw.deepMidwaterEnergyLedger, tick = r.sim._ticks - (pending ? 1 : 0), clock = tick * .1, candidate = { ...r, deepMidwaterLife: d, deepMidwaterLifeAgents: agents, deepMidwaterEnergyLedger: energy, _midwaterValidationGenerator: g };
  if (!exactKeys(d?.allocation, ['capacity', 'maxAdded']) || !exactKeys(allocation, ['capacity', 'maxAdded']) || d.allocation.capacity !== allocation.capacity || d.allocation.maxAdded !== allocation.maxAdded || !Number.isSafeInteger(d.allocation.capacity) || d.allocation.capacity < old.length || d.allocation.capacity > capacity || !Number.isSafeInteger(d.allocation.maxAdded) || d.allocation.maxAdded < 0 || d.allocation.maxAdded > M.maximumAdded) return false;
  const expected = createDeepMidwaterLifePlan(g, { ...r, deepMidwaterLifeAgents: [] }, { availableSlots: d.allocation.capacity - old.length, maxAdded: d.allocation.maxAdded });
  if (JSON.stringify(d.birthPlacements) !== JSON.stringify(expected.placements) || JSON.stringify(d.addedIds) !== JSON.stringify(expected.placements.map(a => a.id))) return false;
  if (tick < 0 || !d || marked(d) || d.version !== 1 || d.role !== deepMidwaterLifeRole(g, r.cx, r.cz) || d.scope !== M.note || d.foodScope !== DEEP_MIDWATER_LIFE_FOOD_SCOPE || d.lastTickSec !== clock || !Array.isArray(d.birthPlacements) || !Array.isArray(d.addedIds) || d.birthPlacements.length !== agents.length || d.addedIds.length !== agents.length || new Set(d.addedIds).size !== agents.length || new Set(agents.map(a => a?.id)).size !== agents.length || (!d.role && agents.length) || !Array.isArray(d.channels) || d.channels.length !== agents.length || !Number.isSafeInteger(d.nextParcelId) || d.nextParcelId < 0 || !Array.isArray(d.events) || d.events.length > 40 || !['ticks', 'inputPulses', 'feedings', 'deaths'].every(k => Number.isSafeInteger(d.counters?.[k]) && d.counters[k] >= 0) || d.counters.ticks !== tick || !nonnegative(d.counters.consumedUnits) || d.counters.deaths !== agents.filter(a => a?.alive === false).length || !energy || !['initial', 'feedingGain', 'maintenanceAndMotionDebit', 'deathLoss'].every(k => nonnegative(energy[k])) || !Number.isFinite(energy.clampCorrection) || energy.clampCorrection > 0 || !close(energy.feedingGain, d.counters.consumedUnits * M.energyGainPerUnit) || Math.abs(deepMidwaterLifeEnergyBudgetError(candidate)) > 1e-8) return false;
  const l = d.foodLedger; if (!l || l.initial !== 0 || !['input', 'ingested', 'exported'].every(k => nonnegative(l[k])) || !l.byPool || Object.keys(l.byPool).length !== DEEP_MIDWATER_LIFE_FOOD_POOLS.length || !close(l.ingested, d.counters.consumedUnits) || DEEP_MIDWATER_LIFE_FOOD_POOLS.some(pool => l.byPool[pool]?.initial !== 0 || !['input', 'ingested', 'exported'].every(k => nonnegative(l.byPool[pool]?.[k])))) return false;
  if (!nonnegative(r.sim.environment.foodSupply) || r.sim.environment.foodSupply > 3 || !nonnegative(r.sim.environment.currentMps) || r.sim.environment.currentMps > 1.2) return false;
  const ids = new Set(old.map(a => a?.id)), channelIds = new Set(), parcelIds = new Set(), checks = tick < 1 ? 0 : 1 + Math.floor((tick - 1) / M.sourceReleaseIntervalTicks), random = randomFor(g, r); let feedingCount = 0, consumed = 0;
  for (const a of agents) { const s = sourceOf(a), index = deepMidwaterLifeSpeciesCatalog.findIndex(s => s.id === a?.speciesId), original = s && birthAt(g, r, s, index), birth = d.birthPlacements.find(p => p?.id === a?.id), c = d.channels.find(c => c.id === a?.deepMidwaterFoodChannelId);
    if (!s || !original || !birth || !exactKeys(birth, Object.keys(original)) || ids.has(a.id) || !d.addedIds.includes(a.id) || olderMarked(a) || Object.keys(a).some(k => k.startsWith('deepMidwater') && !AGENT_FIELDS.includes(k)) || a.deepMidwaterIndividualVersion !== 1 || a.regionId !== r.id || a.createdAtSec !== 0 || ['id', 'speciesId', 'deepMidwaterSiteId', 'deepMidwaterFoodChannelId', 'sizeM', 'nutritionPool', 'habitat'].some(k => a[k] !== original[k] || birth[k] !== original[k]) || birth.heading !== original.heading || birth.pitch !== 0 || !['position', 'home', 'target', 'velocity', 'sourcePosition', 'referencePosition'].every(k => vector(a[k])) || !['x', 'y', 'z'].every(k => close(a.home[k], original.position[k]) && close(birth.position?.[k], original.position[k]) && ['sourcePosition', 'referencePosition'].every(field => close(a[field][k], original[field][k]) && close(birth[field]?.[k], original[field][k]))) || !nonnegative(a.timeSec) || a.timeSec > clock || !nonnegative(a.stateSince) || a.stateSince > a.timeSec || !nonnegative(a.energy) || a.energy > 1 || typeof a.alive !== 'boolean' || (a.alive ? a.timeSec !== clock || !['drifting', 'seeking-suspension', 'capturing-suspension'].includes(a.state) : a.state !== 'dead' || a.energy !== 0 || a.stateSince !== a.timeSec || distance(a.velocity, { x: 0, y: 0, z: 0 }) !== 0) || Math.hypot(a.velocity.x, a.velocity.y, a.velocity.z) > M.traits[a.speciesId].speedMps + 1e-8 || !['nextDecision', 'nextBite', 'travelledM', 'consumedUnits'].every(k => nonnegative(a[k])) || !['decisions', 'feedingCount'].every(k => Number.isSafeInteger(a[k]) && a[k] >= 0) || a.foodScope !== DEEP_MIDWATER_LIFE_FOOD_SCOPE || a.conditionScope !== CONDITION || !deepMidwaterLifePositionValid(g, candidate, a) || !deepMidwaterLifePositionValid(g, candidate, a, a.target, a.targetHeading, a.targetPitch) || !intakeValid(a, candidate)) return false;
    if (!c || marked(c) || channelIds.has(c.id) || c.agentId !== a.id || c.pool !== s.foodPool || c.sourceDistanceM !== M.sourceDistanceM || !['sourcePosition', 'referencePosition'].every(k => vector(c[k]) && ['x', 'y', 'z'].every(axis => close(c[k][axis], original[k][axis]))) || c.releaseChecks !== checks || c.nextReleaseTick !== 1 + checks * M.sourceReleaseIntervalTicks || !Number.isSafeInteger(c.inputPulses) || c.inputPulses < 0 || c.inputPulses > checks || !['inputUnits', 'ingestedUnits', 'exportedUnits'].every(k => nonnegative(c[k])) || c.inputUnits > c.inputPulses * M.maximumParcelAmount + 1e-8 || !Array.isArray(c.parcels) || c.parcels.length > M.maximumParcelsPerChannel) return false;
    for (const p of c.parcels) { if (marked(p) || !Number.isSafeInteger(p.ordinal) || p.ordinal < 1 || p.ordinal > d.nextParcelId || p.id !== `deep-midwater-parcel:${r.id}:${p.ordinal}` || parcelIds.has(p.id) || p.channelId !== c.id || p.pool !== c.pool || !(p.amount > 0) || p.amount > M.maximumParcelAmount + 1e-10 || !vector(p.position) || !vector(p.sourcePosition) || !owns(r, p.position) || !nonnegative(p.travelM) || p.travelM > M.sourceDistanceM + M.outletDistanceM + 1e-10 || !nonnegative(p.createdAtSec) || p.createdAtSec > clock || p.lastTransportSec !== clock || !['x', 'y', 'z'].every(k => close(p.sourcePosition[k], c.sourcePosition[k])) || !close(p.position.x, c.sourcePosition.x + p.travelM) || !close(p.position.y, c.sourcePosition.y) || !close(p.position.z, c.sourcePosition.z) || g.heightAt(p.position.x, p.position.z) >= p.position.y - M.wholeBodyClearanceM) return false; parcelIds.add(p.id); }
    channelIds.add(c.id); ids.add(a.id); feedingCount += a.feedingCount; consumed += a.consumedUnits;
  }
  if (parcelIds.size > M.maximumParcels || feedingCount !== d.counters.feedings || !close(consumed, d.counters.consumedUnits) || !close(energy.initial, agents.reduce((n, a) => n + .68 + random(`${a.id}:condition`) * .12, 0)) || d.counters.inputPulses !== d.channels.reduce((n, c) => n + c.inputPulses, 0) || ['input', 'ingested', 'exported'].some(k => !close(l[k], d.channels.reduce((n, c) => n + c[`${k}Units`], 0)) || !close(l[k], DEEP_MIDWATER_LIFE_FOOD_POOLS.reduce((n, pool) => n + l.byPool[pool][k], 0))) || deepMidwaterLifeFoodBudgetError(candidate) > 1e-8) return false;
  return d.events.every(e => nonnegative(e?.timeSec) && e.timeSec <= clock && agents.some(a => a.id === e.agentId) && ['feeding', 'death'].includes(e.type) && boundedText(e.label) && boundedText(e.cause));
}
export function validateDeepMidwaterLifeRecord(raw, r, { generator, capacity = 20, pending = false, allocation = { capacity: 20, maxAdded: 3 } } = {}) { try { return validate(raw, r, generator, capacity, pending, allocation); } catch { return false; } }
export function tickDeepMidwaterLife(r, g, dt) {
  if (!nativeOwner(g, r) || dt !== .1 || r.deepMidwaterLifeVersion !== 1 || r.sim._ticks !== (r.deepMidwaterLife?.counters?.ticks ?? -2) + 1 || !validateDeepMidwaterLifeRecord(r, r, { generator: g, pending: true })) return false;
  const d = r.deepMidwaterLife, energy = r.deepMidwaterEnergyLedger, clock = r.sim._ticks * .1, flow = r.sim.environment.currentMps, supply = r.sim.environment.foodSupply; d.lastTickSec = clock; d.counters.ticks++;
  for (const a of r.deepMidwaterLifeAgents) { if (!a.alive) continue; a.timeSec = clock; a.localEnvironment = clone(r.sim.environment); const c = d.channels.find(c => c.id === a.deepMidwaterFoodChannelId);
    if (clock >= a.nextDecision) decide(g, r, a, c, clock, flow); const moved = move(g, r, a, dt), debit = Math.min(a.energy, dt * (M.maintenanceDebitPerSec + flow * flow * M.flowDebitPerSec) + moved * M.motionDebitPerM); a.energy -= debit; energy.maintenanceAndMotionDebit += debit;
    if (a.energy <= 1e-9) { energy.deathLoss += a.energy; a.energy = 0; a.alive = false; a.velocity = { x: 0, y: 0, z: 0 }; state(a, 'dead', clock); d.counters.deaths++; d.events.push({ type: 'death', agentId: a.id, timeSec: clock, label: `${sourceOf(a).commonName ?? a.speciesId} relative condition exhausted`, cause: 'Independent relative-condition maintenance and motion depleted available condition.' }); }
  }
  function capture(a, p, c) { const organ = a && deepMidwaterLifeFeedingPosition(a); if (!a?.alive || !(p.amount > 0) || clock < a.nextBite || distance(p.position, organ) > M.captureDistanceM) return;
    const before = p.amount, energyBefore = a.energy, removed = Math.min(before, M.biteAmount); p.amount -= removed; ledgerDelta(d, c, 'ingested', removed); a.energy = Math.min(1, energyBefore + removed * M.energyGainPerUnit);
    energy.feedingGain += removed * M.energyGainPerUnit; energy.clampCorrection += Math.min(0, 1 - energyBefore - removed * M.energyGainPerUnit); a.lastFeedAt = clock; a.nextBite = clock + M.biteIntervalSec; a.feedingCount++; a.consumedUnits += removed; d.counters.feedings++; d.counters.consumedUnits += removed; state(a, 'capturing-suspension', clock);
    a.lastMidwaterIntake = { timeSec: clock, ownerId: r.id, channelId: c.id, pool: c.pool, parcelId: p.id, parcelOrdinal: p.ordinal, parcelCreatedAtSec: p.createdAtSec, parcelTravelM: p.travelM, sourcePosition: clone(c.sourcePosition),
      stockBefore: before, stockAfter: p.amount, removedUnits: removed, energyBefore, energyAfter: a.energy, agentPosition: clone(a.position), agentHeading: a.heading, agentPitch: a.pitch,
      feedingPosition: clone(organ), foodPosition: clone(p.position), contactDistanceM: distance(p.position, organ), allowedDistanceM: M.captureDistanceM, unit: 'relative-organic-food-proxy-unit', scope: DEEP_MIDWATER_LIFE_FOOD_SCOPE };
    d.events.push({ type: 'feeding', agentId: a.id, timeSec: clock, amount: removed, label: `${sourceOf(a).commonName ?? a.speciesId} captured selected suspended nutrition`, cause: 'Actual saved capture structure contacted an accounted parcel in its owner-local suspension channel.' });
  }
  for (const c of d.channels) { const a = r.deepMidwaterLifeAgents.find(a => a.id === c.agentId);
    for (const p of c.parcels) { const travel = flow * dt, oldTravel = p.travelM, probes = Math.max(1, Math.ceil(travel / M.transportProbeSpacingM)); capture(a, p, c);
      for (let i = 1; i <= probes && p.amount > 0; i++) { p.travelM = oldTravel + travel * i / probes; p.position.x = p.sourcePosition.x + p.travelM;
        if (!owns(r, p.position) || p.travelM > M.sourceDistanceM + M.outletDistanceM || g.heightAt(p.position.x, p.position.z) >= p.position.y - M.wholeBodyClearanceM) { ledgerDelta(d, c, 'exported', p.amount); p.amount = 0; break; } capture(a, p, c);
      } p.lastTransportSec = clock;
    } c.parcels = c.parcels.filter(p => p.amount > 0);
    if (r.sim._ticks < c.nextReleaseTick) continue; c.releaseChecks++; c.nextReleaseTick = 1 + c.releaseChecks * M.sourceReleaseIntervalTicks; const input = M.sourceInputUnitsPerSec * M.sourceReleaseIntervalTicks * .1 * supply * flow / M.referenceFlowMps; if (!(input > 0)) continue;
    ledgerDelta(d, c, 'input', input); c.inputPulses++; d.counters.inputPulses++; if (parcels(r).length >= M.maximumParcels || c.parcels.length >= M.maximumParcelsPerChannel) { ledgerDelta(d, c, 'exported', input); continue; }
    const ordinal = ++d.nextParcelId; c.parcels.push({ id: `deep-midwater-parcel:${r.id}:${ordinal}`, ordinal, channelId: c.id, pool: c.pool, amount: input, position: clone(c.sourcePosition), sourcePosition: clone(c.sourcePosition), travelM: 0, createdAtSec: clock, lastTransportSec: clock });
  } d.events = d.events.slice(-40); return true;
}
export function deepMidwaterLifeSnapshot(r) { if (r?.deepMidwaterLifeVersion !== 1) return null; const d = r.deepMidwaterLife; return { version: 1, resources: resources(r), foodLedger: clone(d.foodLedger), energyLedger: clone(r.deepMidwaterEnergyLedger), counters: clone(d.counters),
  channels: clone(d.channels), agents: clone(r.deepMidwaterLifeAgents), lastTickSec: d.lastTickSec, foodScope: DEEP_MIDWATER_LIFE_FOOD_SCOPE, scope: M.note }; }
