// Monterey understory and attached representatives; not a field census.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius, footprintRadiusUnits) => ({
  x, y, z, horizontalRadiusUnits: radius, footprintRadiusUnits,
  origin: 'fixed-native-rock-attachment-base-local-zero',
  axes: 'positive-y-native-support-normal; positive-x-native-surface-tangent; z-transverse',
  status: 'authored-conservative-complete-form-including-bounded-local-animation-not-specimen-morphometry',
});
const footprint = radius => [[radius, 0], [-radius, 0], [0, radius], [0, -radius]]
  .map(([x, z]) => ({ x, y: 0, z }));
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'named-regional-representative', taxonomicLevel: 'species',
  referenceRegion: 'Monterey / central-California native rocky kelp-forest understory',
  coOccurrenceStatus: 'regional-representative-combination-not-reconstructed-single-field-plot',
  ecologicalRateStatus: 'uncalibrated-display-and-selected-nutrition-proxy',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null, calibratedPopulationRates: null,
  populationDensityPerM2: null, naturalAgeSec: null, calibratedFiltrationM3PerSec: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  calibratedCurrentMPerS: null, temperatureRangeC: null, salinityRangePSU: null, oxygenRangeMgPerL: null,
  renderEmissionEnabled: false,
  depthRangeM: data.depthSelectionM,
  admissionDepthM: { range: data.depthSelectionM,
    status: 'chosen-complete-form-actual-water-depth-not-seabed-depth-or-complete-natural-range' },
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'authored-display-selection' },
  support: { mode: 'actual-positive-normal-native-hard-rock-attachment', rootFixed: true,
    wholeBodyDepthRequired: true, terrainClearanceRequired: true, kelpClearanceRequired: true,
    footprintContactPointsLocal: footprint(data.normalizedEnvelope.footprintRadiusUnits) },
  limitations: [
    '代表组合不证明同一现场全部共存；计数、尺寸选择、包络比例与局部动作未作自然密度或标本扫描校准。',
    '根与实际摄入孔参考固定，只有局部远端形体作有限展示动作；不宣称完整水动力或全局动物碰撞证明。',
    '植物记录是持久化景观描述符，不是藻类碳库存、真实光合、成长、繁殖或被摄食模拟。',
    '动物采用独立零初库存的悬浮有机营养分量；输入、摄入、输出记账，不转义或移动任何旧食点或库存。',
    '过滤孔不是嘴，海绵出水孔与海鞘出水虹吸不能当作摄食口；未模拟完整自然食物网、DOM全谱或可见个体捕杀。',
    '自然温盐、溶氧、流速耐受、年龄、密度与生态速率未知项保留null。',
  ],
  ...data,
  sourceLinks: data.sources,
});

export const kelpUnderstoryLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'pterygophora-californica', commonName: '加州翼柄藻', englishName: 'Stalked understory kelp',
    scientificName: 'Pterygophora californica', scientificAuthor: 'Ruprecht', family: 'Alariaceae',
    kind: 'kelp', modelRole: 'stalked-understory-kelp-scenery', sceneryRole: 'persistent-native-rock-rooted-understory',
    individualStatus: 'persistent-scenery-descriptor-not-simulated-biomass',
    firstTimeSpeciesAddition: false,
    existingRepresentation: 'pterygophora-californica-scenery in the earlier independent understory scenery',
    implementationScope: 'source-named-catalogue-representative-and-new-independent-roots-on-natural-free-rock; earlier-scenery-unchanged',
    lengthM: 1.25, sizeRangeM: [1, 1.5], sizeMeasure: 'thallus-height',
    sizeMeasureDefinition: '直立完整藻体从岩面固着器基部到最高叶尖的高度；不是只量柄长、叶长或弯曲中心线弧长。',
    referenceSizeM: { maximumThallusHeight: 2.3, maximumStipeLength: 1.5,
      note: 'UBC E-Flora官方账户分别列完整高2.3m、木质柄长1.5m；本版1–1.5m为展示选择。' },
    depthSelectionM: [7, 20], maximumDisplayPitchRad: 0,
    referenceDepthM: { actualMontereyCollectionM: 8.5, actualOtherRegionObservationM: 10.9,
      selectedContext: 'subtidal-Monterey-understory-with-7-to-20m-display-selection',
      note: 'Stillwater Cove原研究8.5m；USGS原记录10.9m来自Washington，地域不混称Monterey样方。' },
    normalizedEnvelope: envelope([-.72, .72], [0, 1.08], [-.58, .58], .93, .12),
    morphology: { wholeForm: 'short-hapterous-holdfast; stiff-unbranched-woody-stipe; one-terminal-midrib-blade; opposite-upper-sporophyll-rows',
      foodCapturePointLocal: null, feedingPointLocal: null, fixedRoot: { x: 0, y: 0, z: 0 },
      actualUprightThallusHeightUnits: 1, stipeHeightUnits: .56,
      animationScope: 'bounded-distal-blade-sway-only; no-root-or-whole-stipe-translation' },
    foodPool: null, foodCapturePointLocal: null, feedingProxy: null,
    photosynthesisSimulated: false, biomassStockSimulated: false, herbivorySimulated: false,
    habitat: ['native-hard-rock-understory', 'giant-kelp-forest-understory'],
    diet: '景观藻类；本包不赋动物食物池、不做营养吸收、光合或碳质量账。',
    description: '有固着器的直立木质柄，上部两侧叶列与一片末端叶，形成独立低层树冠；保留既有同类景观，不称首次新增物种。',
    colors: ['#78602d', '#9b7937', '#4c4525'],
    sources: [
      source('https://linnet.geog.ubc.ca/Atlas/Atlas.aspx?noTransfer=0&sciname=Pterygophora+californica', 'UBC E-Flora: named whole form, stipe and total height'),
      source('https://sanctuaries.noaa.gov/science/condition/monterey-bay-2015/mbnms-cr-2015-lowres.pdf', 'NOAA Monterey sanctuary: 12-site Monterey/Point Lobos understory monitoring'),
      source('https://www.calstate.edu/impact-of-the-csu/research/coast/students/Documents/Cooper%20V3.pdf', 'Original Stillwater Cove research: tagged plants at 8.5m'),
      source('https://www.usgs.gov/media/videos/3ms18-l1-west-transect-2008', 'USGS original Washington native transect: named plant at 10.9m'),
      source('https://www.sciencedirect.com/science/article/pii/002209819290039D', 'Original Monterey Bay canopy-removal/understory study'),
    ],
  }),
  descriptor({
    id: 'calliarthron-cheilosporioides', commonName: '宽翼分节珊瑚藻', englishName: 'Winged articulated coralline alga',
    scientificName: 'Calliarthron cheilosporioides', scientificAuthor: 'Manza', family: 'Corallinaceae',
    kind: 'kelp', modelRole: 'articulated-coralline-scenery', sceneryRole: 'persistent-native-rock-rooted-low-branching-alga',
    individualStatus: 'persistent-scenery-descriptor-not-simulated-biomass',
    firstTimeSpeciesAddition: true,
    lengthM: .11, sizeRangeM: [.08, .14], sizeMeasure: 'branched-thallus-height',
    sizeMeasureDefinition: '从基部岩附着面至直立分枝最高点的完整藻体高度；不把所有分枝长度相加或使用藻体宽度作高度。',
    referenceSizeM: null,
    sizeSelectionEvidence: 'small-authored-height-selection-with-original-C.cheilosporioides-lectotype-whole-frond-reference-Fig3-1cm-bar; not-measured-natural-size-range',
    depthSelectionM: [7, 25], maximumDisplayPitchRad: 0,
    referenceDepthM: { actualMontereyCollectionM: 27.62, actualCatalinaCollectionM: [19, 25],
      specimenIds: ['UBC A87297', 'UBC A87298'],
      note: '原2011 Table1: Monterey/Pacific Grove/Hopkins两份具名标本2008-06-01、epilithic27.62m；19/25m为Catalina。7–25m为展示选择，不是完整自然范围。' },
    normalizedEnvelope: envelope([-.65, .65], [0, 1.05], [-.55, .55], .86, .18),
    morphology: { wholeForm: 'fixed-encrusting-base; flattened-thin-apical-calcified-intergenicula-with-broad-wings; narrow-flexible-genicula; branched-pink-frond',
      foodCapturePointLocal: null, feedingPointLocal: null, fixedRoot: { x: 0, y: 0, z: 0 },
      actualUprightThallusHeightUnits: 1,
      animationScope: 'bounded-small-distal-joint-flexion-only; calcified-segments-retain-form; fixed-base' },
    foodPool: null, foodCapturePointLocal: null, feedingProxy: null,
    photosynthesisSimulated: false, biomassStockSimulated: false, calcificationSimulated: false, herbivorySimulated: false,
    habitat: ['native-rock-epilithic-low-understory', 'shallow-giant-kelp-forest'],
    diet: '景观红藻；本版不实现光合、钙化、碳库存或藻食摄入。',
    description: '粉红至浅紫、薄扁且有宽翼的顶端钙化节段与窄柔关节组成低层分枝；本种独立Monterey深岩标本支持，不借近似种的深度记录。',
    colors: ['#b87886', '#cf9ba4', '#906977'],
    sources: [
      source('https://www3.botany.ubc.ca/martone/Gabrielson%20et%20al%202011%20Calliarthron%20morphometrics.pdf', 'Original Table1: Monterey Hopkins epilithic27.62m; Catalina19/25m separately; Fig3 lectotype whole frond with 1cm bar; thin broad-winged apical segments'),
    ],
  }),
  descriptor({
    id: 'orange-puffball-sponge', commonName: '加州橙球海绵', englishName: 'Orange puffball sponge',
    scientificName: 'Tethya californiana', scientificAuthor: null, family: 'Tethyidae',
    kind: 'sponge', modelRole: 'fixed-rock-ostium-filter-feeder',
    individualStatus: 'independent-fixed-animal-native-clock-relative-condition-and-actual-intake-receipt',
    firstTimeSpeciesAddition: true,
    lengthM: .07, sizeRangeM: [.06, .08], sizeMeasure: 'body-diameter',
    sizeMeasureDefinition: '近球体完整外径D；不是高度、出水孔口径或海绵内部滤水面积。',
    referenceSizeM: { selectedNamedReferenceDiameter: [.06, .08], note: 'Stanford Hopkins SeaNet具名岩生橙球海绵6–8cm外径。' },
    depthSelectionM: [3, 20], maximumDisplayPitchRad: 0,
    referenceDepthM: { actualMontereyCollectionM: 8, broadAccountRangeM: [0, 440],
      note: '原研究2006 Monastery Beach约8m真实采集；SIMoN广域0–440m不是本片密度/耐受标定。本版选3–20m。' },
    normalizedEnvelope: envelope([-.56, .56], [0, 1.06], [-.56, .56], .80, .25),
    foodCapturePointLocal: { x: .40, y: .80, z: 0 },
    morphology: { wholeForm: 'orange-to-golden-globular-textured-sponge; fixed-basal-attachment; distinct-inhalant-ostium-and-flush-exhalant-osculum',
      foodCapturePointLocal: { x: .40, y: .80, z: 0 }, feedingPointLocal: { x: .40, y: .80, z: 0 },
      captureStructure: 'actual-fixed-visible-surface-inhalant-ostium; not-mouth-or-exhalant-osculum',
      bodySphereCenterLocal: { x: 0, y: .5, z: 0 }, bodySphereRadiusUnits: .5,
      actualUprightBodyDiameterUnits: 1,
      animationScope: 'bounded-surface-detail-only; fixed-root-and-capture-point; not-calibrated-whole-body-contraction' },
    foodPool: 'suspendedOrganicFood',
    feedingProxy: { stock: 'suspendedOrganicFood', owner: 'independent-kelp-understory-suspended-organic-control-volume',
      resourcePath: 'region.kelpUnderstoryLife.foodParcels[].amount',
      initialStock: 0, selectedDietComponent: 'unresolved-suspended-microalgal-and-small-organic-particle-nutrition',
      scope: 'selected-suspension-feeding-component-not-complete-DOM-microbial-spectrum-or-resolved-biomass',
      sourcePosition: 'authored-local-upstream-suspension-source-near-actual-native-rock-fixed-inhalant-reference',
      actualIntakeContactRequired: true, originalFoodStocksModified: false, sourceCalibratedFlux: null,
      note: '原海绵滤水机制与本种Rhodomonas富集响应支持所选微藻/颗粒营养代理；不把共生菌组成当自然食谱普查。' },
    habitat: ['native-hard-rock-kelp-forest', 'rock-surface-understory'],
    diet: '通过入水小孔和内部水沟系统滤水；本版只选未解析悬浮微藻与微小有机颗粒营养，不声称完整DOM或野外微生物谱。',
    description: '小型橙金近球体、有细皱凸表面与岩根；食物接触实际表面入水孔，另保留独立出水孔。',
    colors: ['#bc6525', '#df8a36', '#905124'],
    sources: [
      source('https://seanet.stanford.edu/Demospongiae', 'Stanford Hopkins named whole form: 6–8cm globular orange textured sponge on kelp-forest rocks'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC3873019/', 'Original Sipkema/Blanch 2009-online/2010-issue study: Monastery Beach specimens at approximately 8m'),
      source('https://sanctuarysimon.org/dbtools/species-database/species-info-ajax.php?sID=42', 'NOAA-sanctuary SIMoN named sponge range and full form'),
      source('https://scholarworks.sjsu.edu/etd_theses/5648/', 'Original 2025 T.californiana filtration/contractions thesis abstract; full text embargoed to 2028'),
    ],
  }),
  descriptor({
    id: 'monterey-stalked-tunicate', commonName: '蒙特雷柄海鞘', englishName: 'Monterey stalked tunicate',
    scientificName: 'Styela montereyensis', scientificAuthor: '(Dall, 1872)', family: 'Styelidae',
    kind: 'tunicate', modelRole: 'fixed-rock-incurrent-siphon-filter-feeder',
    individualStatus: 'independent-fixed-animal-native-clock-relative-condition-and-actual-intake-receipt',
    firstTimeSpeciesAddition: true,
    lengthM: .17, sizeRangeM: [.12, .22], sizeMeasure: 'total-attached-height-including-stalk',
    sizeMeasureDefinition: '从岩附着基部至完整直立个体最高端的带柄总高度；含细柄、柱状体与两个虹吸口，不是仅体长或水沟长。',
    referenceSizeM: { wholeNamedReferenceLengthM: .25, aquariumApproximateMaximumLengthM: .3048,
      note: 'Stanford具名个体长至25cm、Oregon aquarium近12英寸完整长度；本版12–22cm总高度/制作比例为选择，并非标本扫描。' },
    depthSelectionM: [3, 20], maximumDisplayPitchRad: 0,
    referenceDepthM: { broadAccountMaximumM: 30.48, actualRegionalSurvey: 'Monterey ASBS19 rocky-subtidal occurrence on 1979-04-01',
      note: '官方水族馆低潮至100feet；加州WaterBoards名录的19是ASBS编号，不是19m水深。' },
    normalizedEnvelope: envelope([-.12, .24], [0, 1.05], [-.14, .14], .28, .07),
    foodCapturePointLocal: { x: .14, y: .86, z: 0 },
    morphology: { wholeForm: 'leathery-longitudinally-ridged-cylindrical-body-on-thin-stalk; separate-four-lobed-down-curved-inhalant-and-upright-exhalant-siphons',
      foodCapturePointLocal: { x: .14, y: .86, z: 0 }, feedingPointLocal: { x: .14, y: .86, z: 0 },
      captureStructure: 'actual-fixed-visible-down-curved-incurrent-branchial-siphon-end; not-mouth-or-upright-excurrent-siphon',
      actualUprightTotalHeightUnits: 1, siphonLobeCount: 4,
      stalkToBodyReference: 'at-least-body-length-in-original-description; specimen-variable-not-calibrated-model-ratio',
      animationScope: 'bounded-distal-surface-details-only; fixed-root-and-capture-reference; no-physically-calibrated-whole-stalk-bending' },
    foodPool: 'suspendedOrganicFood',
    feedingProxy: { stock: 'suspendedOrganicFood', owner: 'independent-kelp-understory-suspended-organic-control-volume',
      resourcePath: 'region.kelpUnderstoryLife.foodParcels[].amount',
      initialStock: 0, selectedDietComponent: 'unresolved-suspended-microplankton-and-organic-particle-nutrition',
      scope: 'selected-filter-feeding-component-not-complete-plankton-spectrum-or-resolved-biomass',
      sourcePosition: 'authored-local-upstream-suspension-source-near-actual-native-rock-fixed-incurrent-siphon',
      actualIntakeContactRequired: true, originalFoodStocksModified: false, sourceCalibratedFlux: null },
    habitat: ['native-rock-attached-kelp-understory', 'rock-reef-boulder-attached'],
    diet: '悬浮滤食者，以入水虹吸进入鳃篮过滤微型浮游生物和有机颗粒，水从另一个上向出水虹吸排出。',
    description: '细柄支撑红褐纵棱柱状体，完整呈现向下回弯的入水口与直立出水口；不套用海绵出水孔作摄食参考。',
    colors: ['#8b4b37', '#ad6950', '#583829'],
    sources: [
      source('https://seanet.stanford.edu/Urochordata', 'Stanford Hopkins named Monterey form: stalk, ridged tunic and recurved oral siphon'),
      source('https://aquarium.org/animals/stalked-tunicate/', 'Oregon Coast Aquarium: hard attachment, depth, complete length, plankton diet and separate flow directions'),
      source('https://www.waterboards.ca.gov/water_issues/programs/ocean/docs/asbs/mba_app_2011jan.pdf', 'California WaterBoards original regional species-survey appendix: Monterey rocky-subtidal occurrence'),
      source('https://www.vliz.be/imisdocs/publications/ocrd/408087.pdf', 'Original Ritter/Forsyth 1917 description: stalk/body, longitudinal ridges, separate 4-lobed siphons'),
      source('https://doi.org/10.2307/1541105', 'Original Young/Braithwaite 1980: orientation and current-induced branchial flow'),
    ],
  }),
]);

export const kelpUnderstoryLifeSpeciesById = freeze(Object.fromEntries(
  kelpUnderstoryLifeSpeciesCatalog.map(species => [species.id, species]),
));
