// Finite Monterey / central-California bed-edge representatives, not a census.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius, origin) => ({
  x, y, z, horizontalRadiusUnits: radius, origin,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-conservative-complete-form-and-bounded-animation-clearance',
});
const crabFeet = [-.34, -.13, .09, .28].flatMap(x => [-.80, .80].map(z => ({ x, y: 0, z })));
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '蒙特雷及加州中部巨藻林岩底、林缘与相邻砂底的有限代表组合',
  coOccurrenceStatus: 'regional-representatives-not-a-single-field-plot-or-universal-kelp-residents',
  individualStatus: 'independent-animal-with-native-clock-relative-condition-and-actual-intake-receipt',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  calibratedPopulationRates: null, populationDensityPerM2: null, naturalSchoolSize: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  calibratedCurrentMPerS: null, calibratedAgeSec: null,
  temperatureRangeC: null, salinityRangePSU: null, oxygenRangeMgPerL: null,
  environmentToleranceStatus: 'unknown-not-a-species-tolerance-calibration',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  depthRangeM: data.depthSelectionM,
  admissionDepthM: { range: data.depthSelectionM,
    status: 'chosen-whole-individual-water-depth-not-bed-depth-or-complete-natural-range' },
  foodPool: 'benthicAnimalFood', foodScope: 'selected-unresolved-bed-animal-nutrition-component',
  feedingProxy: {
    owner: 'independent-kelp-near-bottom-bed-control-volume', stock: 'benthicAnimalFood',
    resourcePath: 'region.kelpNearBottomLife.foodPatches[].amount',
    positionPath: 'region.kelpNearBottomLife.foodPatches[].position',
    ledgerPath: 'region.kelpNearBottomLife.foodLedger.byPool.benthicAnimalFood',
    sourcePosition: 'actual-native-sim-rockPatches-or-floorPatches-support-plus-authored-small-bed-height',
    initialStock: 0, input: 'bounded-external-bed-animal-proxy-input-controlled-by-foodSupply',
    selectedDietComponent: 'unresolved-benthic-invertebrate-animal-organic-nutrition',
    status: 'selected-natural-diet-component-with-own-input-ingested-exported-ledger-not-complete-diet',
    originalFoodStocksUnchangedAtAdmission: true, originalHostPreyRelocated: false,
    speciesResolvedFoodStock: false, visiblePreyKillImplemented: false,
  },
  renderEmissionEnabled: false,
  limitations: [
    '这些记录是区域生境代表；未证明四类在同一时刻、同一巨藻区块必然共存。',
    '展示个体数、所选尺寸、水深、体形比例、动作、摄食距离与相对能量均未作野外校准。',
    'CW、TL和DW保持独立量尺；完整螯、行走足、鳍、盘、尾及尾刺仍计入全部净空。',
    '独立床食代理从零开始，只在实际口部接触时扣账；不改变旧藻、碎屑或原host水层smallPrey的含义、位置和出生库存。',
    '床食外部输入不是原生可见猎物出生，不模拟可见个体捕杀、完整食物网或动物碳质量。',
    '自然温盐、溶氧耐受、流速耐受、密度、年龄和生态速率未知项保留null。',
  ],
  ...data,
  sourceLinks: data.sources,
});

export const kelpNearBottomLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'red-rock-crab', commonName: '红岩蟹', englishName: 'Red rock crab',
    scientificName: 'Cancer productus', scientificAuthor: null, family: 'Cancridae',
    kind: 'crab', modelRole: 'grounded-red-rock-crab', motionMode: 'grounded',
    guild: 'bed-invertebrate-predator-selected-component',
    lengthM: .12, sizeRangeM: [.10, .14], sizeMeasure: 'carapace-width',
    sizeMeasureDefinition: '甲壳最宽处横向甲宽CW；不包括螯与行走足，也不是甲长或全部足展宽。',
    depthSelectionM: [3, 20], maximumDisplayPitchRad: 0,
    referenceSizeM: { maximum: .16, measure: 'carapace-width',
      note: 'DFO官方账户的甲宽160mm；本版10–14cm为选定尺寸，不声称Monterey尺寸分布。' },
    referenceDepthM: { lowIntertidal: true, reportedAtLeastMaximumM: 90,
      actualRegionalCollectionDepthM: [8, 10],
      note: 'DFO参考生境低潮间至至少90m；Jester等原研究于2004–2005年在Santa Cruz Wharf约8–10m真实捕获C.productus。' },
    support: { mode: 'whole-grounded-crab-on-actual-native-rock-or-floor-support',
      localUp: 'native-support-normal', wholeBodyDepthRequired: true,
      terrainClearanceRequired: true, kelpClearanceRequired: true,
      footContactPointsLocal: crabFeet },
    habitat: ['native-rock-and-gravel-bed', 'kelp-forest-bed-edge', 'adjacent-sand-and-boulder-edge'],
    diet: '以大螯处理蛤、螺、贻贝、藤壶和较小蟹等底栖动物；本版只选未解析的床面动物营养分量。',
    feedingEvidenceLevel: 'government-species-account-and-regional-original-collection',
    behavior: '在实际支持面爬行与转向，用螯形成整体轮廓；摄入由前部腹侧真实口完成，不能把螯尖当成嘴。',
    description: '砖红宽甲、浅腹面、两只黑尖大螯与四对行走足；区别于已有细长足的北方藻蟹。',
    colors: ['#8c3d30', '#53251f', '#191b19', '#d6bd9e'],
    normalizedEnvelope: envelope([-.48, .86], [0, .52], [-.86, .86], 1.22, 'ground-foot-plane-centre-carapace-width-normalized-along-z'),
    morphology: { form: 'wide-brick-red-carapace-two-black-tipped-claws-four-pairs-of-walking-legs',
      sizeAxis: 'carapace-widest-z-extent-one-excluding-all-appendages',
      neutralMeasuredZ: [-.5, .5], normalizedMeasuredSize: 1,
      rootReference: 'actual-support-foot-plane-centre', walkingLegCount: 8, clawCount: 2,
      footContactPointsLocal: crabFeet, feedingPointLocal: { x: .25, y: .12, z: 0 },
      feedingOrgan: 'visible-mouth-at-front-ventral-carapace',
      clearanceIncludes: ['whole-carapace', 'eyes-and-stalks', 'both-claws', 'all-eight-walking-legs', 'bounded-limb-motion'],
      wholeFormReference: { url: 'https://www.dfo-mpo.gc.ca/species-especes/profiles-profils/red-rock-crab-tourteau-rouge-pac-eng.html',
        location: 'DFO labelled whole red-rock-crab and morphological account' } },
    sources: [
      source('https://www.dfo-mpo.gc.ca/species-especes/profiles-profils/red-rock-crab-tourteau-rouge-pac-eng.html', 'DFO官方种账户：巨藻/岩砾生境、独立甲宽、砖红宽甲与黑尖双螯'),
      source('https://www.fisheries.noaa.gov/s3/2021-07/Southwest-Region-Observer-Program-Field-Manual.pdf', 'NOAA西南区观测员手册C.productus条目：完整鉴别及蛤/螺/贻贝/藤壶/小蟹捕食'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC7477862/', 'Jester等2009原始Monterey研究：2004–2005 Santa Cruz Wharf约8–10m捕获具名红岩蟹；不采用毒素或密度作为本版生态参数'),
    ],
  }),
  descriptor({
    id: 'gopher-rockfish', commonName: '褐斑岩鱼', englishName: 'Gopher rockfish',
    scientificName: 'Sebastes carnatus', scientificAuthor: '(Jordan & Gilbert, 1880)', family: 'Scorpaenidae',
    nameNote: '中文为描述名称，以具名S.carnatus为准，不把既有S.mystinus蓝岩鱼改名。',
    kind: 'fish', modelRole: 'free-near-bed-gopher-rockfish', motionMode: 'free',
    guild: 'rock-edge-benthic-animal-predator-selected-component',
    lengthM: .285, sizeRangeM: [.25, .32], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端的全长TL；不替换为标准长SL或尾叉长FL。',
    depthSelectionM: [3, 20], maximumDisplayPitchRad: .12,
    referenceSizeM: { measuredRange: [.167, .329], mean: .264, measure: 'total-length',
      note: 'Loury等2015中加州原始胃含物研究实测1018条鱼TL16.7–32.9cm；本版不借其密度或体重换算。' },
    referenceDepthM: { lowIntertidal: true, maximumM: 88,
      commonRegionalDepthM: [9, 37],
      note: 'Love等2021参考范围潮间至88m；PFMC2019岩礁账户常见9–37m。展示3–20m不称当前Monterey实测频度峰值。' },
    support: { mode: 'whole-free-form-near-actual-native-rock-bed', localUp: 'world-up',
      wholeBodyDepthRequired: true, terrainClearanceRequired: true, kelpClearanceRequired: true },
    habitat: ['native-rock-reef', 'giant-kelp-bed-and-forest-edge'],
    diet: '中加州实测食谱含多种蟹、虾、糠虾、蛇尾及其他底栖动物，地点分量不同；本版只选择床面动物营养分量。',
    feedingEvidenceLevel: 'original-central-california-stomach-contents',
    behavior: '作为单体、近岩底活动的代表，不套用已有竹荚鱼群行为；实际口部接近床食点才摄入。',
    description: '深而厚的褐色鱼体、乳白至粉白不规则斑块、相连的棘条与软条背鳍、完整胸腹鳍和浅凹尾；整体区别于银蓝细长群游鱼。',
    colors: ['#78644c', '#cdbfac', '#493f34'],
    normalizedEnvelope: envelope([-.55, .55], [-.30, .35], [-.24, .24], .61, 'total-length-axis-midpoint'),
    morphology: { form: 'deep-mottled-rockfish-connected-spiny-soft-dorsal-and-shallowly-concave-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', neutralMeasuredX: [-.5, .5], normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', feedingPointLocal: { x: .48, y: -.065, z: 0 },
      feedingOrgan: 'visible-terminal-mouth-connected-to-snout',
      clearanceIncludes: ['head', 'whole-body', 'spiny-and-soft-dorsal', 'anal-fin', 'paired-fins', 'entire-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://sanctuarysimon.org/dbtools/species-database/id/209/sebastes/carnatus/gopher-rockfish/',
        location: 'SIMoN named gopher-rockfish morphology and photo; authored geometry not specimen scan' } },
    sources: [
      source('https://repository.library.noaa.gov/view/noaa/23850/noaa_23850_DS1.pdf', 'Burton/Lea2019原始Monterey名录p57：Monterey原描述、Carmel及当地馆藏'),
      source('https://www.ccfrp.org/_files/ugd/daae59_27fc49392bc94222a6eaf5ffeb598c9f.pdf', 'Loury等2015原始中加州食性：TL16.7–32.9cm、各地蟹/虾/蛇尾等真实食谱'),
      source('https://escholarship.org/content/qt26n4k816/qt26n4k816_noSplash_fe996ccfe7edd20d76837c6a59b8f3d3.pdf', 'Love等2021原作者名录p107：S.carnatus量尺与潮间至88m参考分布；不使用排版英寸错误'),
      source('https://www.pcouncil.org/documents/2019/09/agenda-item-h-5-attachment-11-2.pdf/', 'PFMC2019具名评估：巨藻岩礁近底、常见9–37m、单体领地与动物食物；不搬用种群预测'),
      source('https://sanctuarysimon.org/dbtools/species-database/id/209/sebastes/carnatus/gopher-rockfish/', 'SIMoN具名全体形：厚褐体与白粉色不规则斑块'),
    ],
  }),
  descriptor({
    id: 'horn-shark', commonName: '加州角鲨', englishName: 'Horn shark',
    scientificName: 'Heterodontus francisci', scientificAuthor: '(Girard, 1855)', family: 'Heterodontidae',
    kind: 'shark', modelRole: 'free-near-bed-horn-shark', motionMode: 'free',
    guild: 'near-bed-hard-bodied-animal-predator-selected-component',
    lengthM: .75, sizeRangeM: [.65, .85], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端全长TL，尾鳍包括在计量轴和完整包络中。',
    depthSelectionM: [3, 18], maximumDisplayPitchRad: .12, maximumHeightAboveBedM: 2,
    referenceSizeM: { atLeastMaximum: 1.21, measure: 'total-length',
      note: 'Love等2021核到至少121cm TL；广传122cm来自about4feet，不能写成精确实测最大。65–85cm为本版选择。' },
    referenceDepthM: { lowIntertidal: true, maximumM: 201, commonUpperDepthM: 20,
      note: 'Love等2021广域深度；AOP物种账户典型浅于20m。完整个体选择3–18m，近床高度最多2m是展示约束，非垂向频度调查。' },
    support: { mode: 'whole-free-form-near-actual-native-rock-sand-bed', localUp: 'world-up',
      wholeBodyDepthRequired: true, terrainClearanceRequired: true, kelpClearanceRequired: true },
    habitat: ['kelp-forest-bed-edge', 'rock-reef-and-adjacent-sand-bed'],
    diet: '甲壳动物、海胆、软体动物及小鱼；本版选择未解析的近底动物营养部分，不使其捕殺可视已有海胆或鱼。',
    feedingEvidenceLevel: 'authoritative-aquarium-species-diet-and-regional-original-identity',
    behavior: '偏夜间活动、白天多休息于有掩蔽处的近底代表；展示时刻不是精确自然节律或每日摄食率。',
    description: '粗短钝头、高眉脊、灰褐深斑体、两枚背鳍各有前棘、宽胸鳍和完整异尾；不加臀鳍棘，不复制豹鲨细长身体。',
    colors: ['#82755d', '#4a4033', '#c0b199'],
    normalizedEnvelope: envelope([-.55, .55], [-.18, .34], [-.32, .32], .64, 'total-length-axis-midpoint'),
    morphology: { form: 'blunt-ridged-head-two-spined-dorsals-broad-pectorals-heterocercal-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', neutralMeasuredX: [-.5, .5], normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', dorsalSpineCount: 2, analSpineCount: 0,
      feedingPointLocal: { x: .34, y: -.12, z: 0 }, feedingOrgan: 'visible-ventral-mouth-behind-blunt-snout',
      clearanceIncludes: ['whole-head-and-body', 'both-dorsal-fins-and-spines', 'paired-fins', 'anal-fin', 'entire-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/horn-shark',
        location: 'MBA named whole horn-shark live photo and benthic kelp account' } },
    sources: [
      source('https://repository.library.noaa.gov/view/noaa/23850/noaa_23850_DS1.pdf', 'Burton/Lea2019原Monterey名录p27：H.francisci由Monterey原描述，USNM112106当地馆藏'),
      source('https://escholarship.org/content/qt26n4k816/qt26n4k816_noSplash_fe996ccfe7edd20d76837c6a59b8f3d3.pdf', 'Love等2021原作者名录p13：至少121cm TL、底栖与潮间至201m广域参考范围'),
      source('https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/horn-shark', 'MBA官方全形：巨藻林、底层生活与甲壳类/海胆/软体动物/小鱼饮食'),
      source('https://www.aquariumofpacific.org/reportcard/info/horn_shark', 'AOP官方物种报告：两枚背鳍前棘、典型浅于20m、岩礁/巨藻/砂底'),
      source('https://www.aquariumofpacific.org/onlinelearningcenter/species/horn_shark', 'AOP夜间觅食与通常距底不超过2m的描述；不沿用其误写臀鳍棘的句子'),
    ],
  }),
  descriptor({
    id: 'round-stingray', commonName: '哈氏圆魟', englishName: 'Round stingray',
    scientificName: 'Urobatis halleri', scientificAuthor: '(Cooper, 1863)', family: 'Urotrygonidae',
    kind: 'ray', modelRole: 'free-near-bed-round-stingray', motionMode: 'free',
    guild: 'soft-bed-invertebrate-predator-selected-component',
    lengthM: .21, sizeRangeM: [.18, .24], sizeMeasure: 'disc-width',
    sizeMeasureDefinition: '胸鳍盘最宽处的横向盘宽DW；不含尾长和尾刺，也不是全长TL或盘长。',
    depthSelectionM: [3, 15], maximumDisplayPitchRad: 0, maximumHeightAboveBedM: 2,
    referenceSizeM: { measuredRegionalRange: [.095, .240], measure: 'disc-width',
      separateMaximumDiscWidthM: .33, separateMaximumTotalLengthM: .58,
      note: 'Jordan等2009实际Catalina Harbor样本DW9.5–24cm；Love等2021另列DW33cm与TL58cm，不线性换算、不称Monterey当地尺寸统计。' },
    referenceDepthM: { range: [.3, 91],
      note: 'Love等2021广域范围。Monterey当地身份由Elkhorn Slough馆藏与原始发表支持，不称常见林内常驻。' },
    regionalOccurrenceStatus: 'documented-adjacent-Elkhorn-Slough-soft-bottom-not-universal-kelp-forest-resident',
    support: { mode: 'whole-free-form-close-to-actual-native-soft-floor-edge', localUp: 'world-up',
      selectedSubstrate: 'native-floor-only-not-perched-on-rock', wholeBodyDepthRequired: true,
      terrainClearanceRequired: true, kelpClearanceRequired: true },
    habitat: ['adjacent-sand-and-soft-bed-edge', 'nearshore-soft-bottom-and-estuarine-edge'],
    diet: '主要选择底栖甲壳动物、多毛类等动物部分；原始食性样本来自墨西哥大陆架，不能称Monterey当地比例已实测。',
    feedingEvidenceLevel: 'original-same-species-benthic-diet-with-region-explicit',
    behavior: '靠近砂底游动，以腹面口接近实际床食点；不作为巨藻林冠群游动物，不强演示埋砂或大群聚集。',
    description: '近圆且横向稍宽的浅褐盘、浅斑小点、背面眼和眼后呼吸孔、腹面口、完整较短尾与圆尾鳍/尾刺；不是菱形长鞭尾魟。',
    colors: ['#9a8667', '#c0ae8b', '#5d513f', '#d3c8b1'],
    normalizedEnvelope: envelope([-1.50, .55], [-.10, .20], [-.56, .56], 1.61, 'disc-centre-disc-width-normalized-along-z'),
    morphology: { form: 'rounded-disc-dorsal-eyes-spiracles-ventral-mouth-short-tail-with-rounded-caudal-fin-and-sting',
      sizeAxis: 'widest-pectoral-disc-z-one-excluding-tail-and-sting', neutralMeasuredZ: [-.5, .5], normalizedMeasuredSize: 1,
      rootReference: 'disc-centre', feedingPointLocal: { x: .27, y: -.065, z: 0 },
      feedingOrgan: 'visible-mouth-connected-to-anterior-ventral-disc',
      tailDirection: 'negative-x', tailStingIncluded: true,
      clearanceIncludes: ['whole-disc', 'eyes', 'spiracles', 'pelvic-fins', 'complete-tail', 'rounded-tail-fin', 'tail-sting', 'bounded-disc-tail-motion'],
      wholeFormReference: { url: 'https://biogeodb.stri.si.edu/sftep/en/thefishes/species/231',
        location: 'Smithsonian STRI named whole images and diagnostic rounded disc / short rounded-fin tail' } },
    sources: [
      source('https://repository.library.noaa.gov/view/noaa/23850/noaa_23850_DS1.pdf', 'Burton/Lea2019原Monterey名录p33：Elkhorn Slough三个馆藏及Herald/Yoklavich当地原发表'),
      source('https://www.fau.edu/science/documents/jkg09a.pdf', 'Jordan/Kajiura/Gordon2009原实验：Catalina Harbor真实DW9.5–24cm、腹面口与实际靠底定位摄食'),
      source('https://escholarship.org/content/qt26n4k816/qt26n4k816_noSplash_fe996ccfe7edd20d76837c6a59b8f3d3.pdf', 'Love等2021原作者名录p27：DW33cm、TL58cm分别计量；0.3–91m参考深度'),
      source('https://biogeodb.stri.si.edu/sftep/en/thefishes/species/231', 'Smithsonian STRI具名全形与鉴别：近圆稍宽盘、较短尾、圆尾鳍、砂/砾/岩边生境'),
      source('https://cienciasmarinas.com.mx/index.php/cmarinas/article/view/375', 'Valadez-González等2001原始同种胃含物：Jalisco/Colima床栖甲壳动物、多毛类等；不移用当地比例'),
    ],
  }),
]);
export const kelpNearBottomLifeSpeciesById = freeze(Object.fromEntries(
  kelpNearBottomLifeSpeciesCatalog.map(species => [species.id, species]),
));
