// Finite Monterey giant-kelp / forest-edge representatives. Display admission,
// geometry, group size and rates are selections, not a reconstructed census.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (name, url) => ({ name, label: name, url });
const fishEnvelope = () => ({
  x: [-.55, .55], y: [-.25, .25], z: [-.25, .25], horizontalRadiusUnits: .61,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-whole-form-and-bounded-animation-clearance',
});
const animalProxy = () => ({
  owner: 'existing-kelp-simulation', stock: 'smallPrey',
  resourcePath: 'region.sim.preyPatches[].smallPrey',
  positionPath: 'region.sim._preyPosition(patch)',
  selectedDietComponent: 'unresolved-small-animal-organic-nutrition',
  status: 'selected-natural-diet-component-at-existing-native-food-point-not-complete-diet',
  speciesResolvedFoodStock: false, visiblePreyKillImplemented: false,
});
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '蒙特雷及加州中部巨藻林、林缘与相邻近岸水层的有限代表组合',
  coOccurrenceStatus: 'regional-representatives-not-a-single-field-plot-or-permanent-resident-community',
  individualStatus: 'independent-simulated-individual-with-own-relative-condition-clock-and-intake-receipt',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  calibratedPopulationRates: null, populationDensityPerM2: null, naturalSchoolSize: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  calibratedCurrentMPerS: null, calibratedAgeSec: null,
  temperatureRangeC: null, salinityRangePSU: null, oxygenRangeMgPerL: null,
  environmentToleranceStatus: 'unknown-not-a-species-tolerance-calibration',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM,
    status: 'chosen-whole-individual-water-depth-not-seabed-depth-or-complete-species-range' },
  support: { mode: 'whole-freewater-form-in-native-kelp-environment',
    wholeBodyDepthRequired: true, terrainClearanceRequired: true,
    kelpClearanceRequired: true, pitchClearanceRequired: true },
  foodProxyStatus: 'selected-diet-component-in-existing-relative-stock-not-complete-natural-diet',
  renderEmissionEnabled: false,
  limitations: [
    '使用同区域命名代表，未证明四类在同一时刻、同一海床单元必然共存。',
    '每个新动物是独立个体；4–5条鱼等有限展示数量不是自然群规模、密度或普查。',
    '全身净空包含尾、鳍、头腕、口腕和触手及有界动作；不把外套膜长或伞径当作动物总长度。',
    '自然温度、盐度、溶氧、流速耐受和人口速率未知项保留null；模拟行为与相对状态未校准，未建立动物身体碳库存。',
    '前三取已有smallPrey点位的选定动物营养分量，青眼鱼取已有岩面algae分量；未复原完整食物网或捕杀可见个体。',
  ],
  ...data,
  sourceLinks: data.sources.map(item => item.url),
});

export const kelpWaterLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'pacific-jack-mackerel', commonName: '太平洋竹荚鱼',
    englishName: 'Pacific jack mackerel', scientificName: 'Trachurus symmetricus',
    scientificAuthor: '(Ayres, 1855)', family: 'Carangidae',
    kind: 'fish', modelRole: 'jack-mackerel', guild: 'kelp-edge-schooling-animal-feeder',
    lengthM: .155, sizeRangeM: [.14, .17], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端的全长TL；不把尾叉长FL换算成TL。',
    depthSelectionM: [3, 15], maximumDisplayPitchRad: .12,
    referenceSizeM: { measuredRange: [.09, .176], measure: 'total-length',
      context: 'Hunter1971实验游泳鱼的原始测量；仅用作尺寸口径与选定尺寸依据，不借用实验速度、温度或分组数。' },
    referenceDepthM: { reportedMinimum: 0, reportedAtLeastMaximum: 182.88,
      sourceMeasure: 'surface-to-at-least-100-fathoms',
      note: 'ODFW账户的表层至至少100英寻为广域范围；3–15米是本版水层选择，未称为蒙特雷实测常见深度。' },
    schooling: { enabled: true, naturalBehavior: 'juvenile-schools-occasionally-enter-Monterey-kelp-beds',
      naturalCount: null, displayGroupSizeStatus: 'four-to-five-independent-agents-not-field-density' },
    habitat: ['giant-kelp-forest-edge-water-column', 'nearshore-kelp-canopy-water-column'],
    diet: '自然食甲壳动物、其他浮游动物和小鱼；本版仅消费已有smallPrey选定动物营养分量。',
    feedingProxy: animalProxy(), foodScope: 'small-prey',
    description: '细长金属蓝至橄榄背、银腹，两段背鳍、鳃盖上后黑点、细尾柄与深叉尾，侧线后段具棱鳞。',
    colors: ['#477a7f', '#c5d8d6', '#364d50'],
    normalizedEnvelope: fishEnvelope(),
    morphology: { form: 'slender-jack-with-two-dorsals-narrow-peduncle-and-deeply-forked-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5],
      feedingPointLocal: { x: .5, y: 0, z: 0 }, feedingOrgan: 'mouth-at-snout',
      clearanceIncludes: ['head', 'body', 'two-dorsal-fins', 'anal-fin', 'paired-fins', 'forked-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://www.dfw.state.or.us/MRP/finfish/sp/other.asp',
        location: 'ODFW-labelled complete Jack Mackerel photo and diagnostic account' } },
    sources: [
      source('Hunter1971原始测量：9.0–17.6cm TL；未采用强迫游泳速率', 'https://swfsc-publications.fisheries.noaa.gov/publications/CR/1971/7113.PDF'),
      source('California原始巨藻生物表印刷p134：Monterey Pier/Cannery Row偶入巨藻的幼鱼群', 'https://escholarship.org/content/qt12w6k1j1/qt12w6k1j1_noSplash_8a079655d1a9d98c966554bba0379c62.pdf?t=lnpeub'),
      source('ODFW：完整命名形态、近巨藻幼鱼群、广域深度与动物食物', 'https://www.dfw.state.or.us/MRP/finfish/sp/other.asp'),
      source('Burton与Lea2019原创蒙特雷保护区鱼类名录：T.symmetricus当地记录', 'https://repository.library.noaa.gov/view/noaa/23850/noaa_23850_DS1.pdf'),
    ],
  }),
  descriptor({
    id: 'california-market-squid', commonName: '加州市售鱿鱼',
    englishName: 'California market squid', scientificName: 'Doryteuthis opalescens',
    scientificAuthor: '(Berry, 1911)', family: 'Loliginidae',
    kind: 'cephalopod', modelRole: 'market-squid', guild: 'kelp-edge-swimming-animal-feeder',
    taxonomicNote: '旧来源Loligo opalescens为此命名种的历史组合，不是已有印太Sepioteuthis lessoniana复合群。',
    lengthM: .16, sizeRangeM: [.14, .18], sizeMeasure: 'dorsal-mantle-length',
    sizeMeasureDefinition: '外套膜背缘前端至外套膜后尖的背侧外套膜长DML；头、八腕和两条摄食触手在计量轴之外但仍须完整净空。',
    depthSelectionM: [3, 15], maximumDisplayPitchRad: .12,
    referenceSizeM: { commonlyReportedRange: [.13, .19], measure: 'mantle-length',
      separateMaximumReportedTotalLength: .305,
      note: 'FAO2010明确13–19cm ML；FAO1984另明确背侧ML，展示14–18cm不转换为TL。' },
    referenceDepthM: { reportedRange: [0, 500],
      note: 'FAO自然近岸大陆架水层范围；3–15米是自由游动访客选择，不是卵场或产卵海床范围。' },
    schooling: { enabled: false, naturalBehavior: 'schooling-with-seasonal-spawning-aggregations',
      naturalCount: null, displayGroupSizeStatus: 'optional-single-representative-not-a-complete-squid-school' },
    activity: { naturalEvidence: 'adults-generally-deeper-by-day-and-near-surface-at-night',
      calibratedHourGate: null, status: 'natural-diel-migration-described-not-calibrated-or-fully-simulated' },
    habitat: ['nearshore-shelf-water-column', 'giant-kelp-forest-edge-water-column'],
    diet: '自然动物食物含磷虾、其他甲壳动物、软体动物和鱼；已有smallPrey仅代理选定的小动物营养分量。',
    feedingProxy: animalProxy(), foodScope: 'small-prey',
    description: '细长尖尾外套膜、后半部成对菱形鳍、紧凑头部、八条短腕及两条窄端摄食触手；天然颜色可变。',
    colors: ['#c4b6a2', '#a58272', '#d8d0c1'],
    normalizedEnvelope: { x: [-.55, 1.6], y: [-.4, .4], z: [-.4, .4], horizontalRadiusUnits: 1.65,
      axes: 'head-and-arms-positive-x; up-positive-y; transverse-z',
      status: 'uncalibrated-whole-mantle-head-eight-arms-two-tentacles-and-bounded-fin-motion-clearance' },
    morphology: { form: 'slender-market-squid-with-short-posterior-rhomboid-fins-and-narrow-tentacle-clubs',
      sizeAxis: 'dorsal-mantle-front-edge-to-posterior-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'mantle-length-midpoint', neutralMeasuredX: [-.5, .5],
      arms: 8, feedingTentacles: 2,
      feedingPointLocal: { x: 1.50, y: .025, z: 0 }, feedingOrgan: 'extended-feeding-tentacle-club',
      clearanceIncludes: ['mantle', 'two-fins', 'head', 'eight-arms', 'two-feeding-tentacles', 'bounded-appendage-motion'],
      wholeFormReference: { url: 'https://www.fao.org/4/i1920e/i1920e02.pdf',
        location: 'Jereb与Roper2010 printedp62 Fig91 named whole dorsal/ventral views and narrow tentacle club' } },
    sources: [
      source('Jereb与Roper2010 FAO原作者种账户pp62–64/Fig91：ML、完整形态、加州流分布与0–500m', 'https://www.fao.org/4/i1920e/i1920e02.pdf'),
      source('Roper等1984 FAO印刷p96：背侧ML与小动物食物；不搬用历史日摄食率', 'https://www.fao.org/docrep/pdf/009/ac479e/ac479e16.pdf'),
      source('Monterey Bay Aquarium官方账户：命名种、蒙特雷浅水聚集与动物食物', 'https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/common-market-squid'),
      source('Young等2011蒙特雷原始海床研究：卵场与巨藻林关系不同于水层访客', 'https://seafloor.otterlabs.org/publications/Youngetal_JEMBE2011.pdf'),
    ],
  }),
  descriptor({
    id: 'pacific-sea-nettle', commonName: '太平洋海荨麻',
    englishName: 'Pacific sea nettle', scientificName: 'Chrysaora fuscescens',
    scientificAuthor: 'Brandt, 1835', family: 'Pelagiidae',
    kind: 'jellyfish', modelRole: 'sea-nettle', guild: 'kelp-edge-drifting-animal-feeder',
    lengthM: .21, sizeRangeM: [.18, .24], sizeMeasure: 'bell-diameter',
    sizeMeasureDefinition: '伞铃的横向直径；长口腕和边缘触手不属于伞径，不能省略或把伞径标成全身长度。',
    depthSelectionM: [3, 12], maximumDisplayPitchRad: 0,
    referenceSizeM: { observedMontereyBellDiameterRange: [.16, .25], maximumBellDiameter: .45,
      measure: 'bell-diameter', separateReportedMouthArmLengthRange: [3.6, 4.6],
      note: 'Fannjiang等2019实际蒙特雷采集个体伞径16–25cm；MBA45cm伞径与3.6–4.6m口腕分别记录，未建立线性长度换算。' },
    referenceDepthM: { reportedRange: null, habitat: 'near-surface-coastal-and-epipelagic-water',
      note: '所选来源支持近表层沿岸水层和蒙特雷野外个体；3–12米是展示选择，不以系绳允许30–39米或其他水母的1097米迁移当作自然水深范围。' },
    schooling: { enabled: false, naturalBehavior: 'pelagic-drifting-and-pulsing-medusa',
      naturalCount: null, displayGroupSizeStatus: 'optional-single-representative-not-a-calibrated-bloom' },
    habitat: ['nearshore-pelagic-water', 'giant-kelp-forest-edge-adjacent-water-column'],
    diet: '自然食浮游动物、幼鱼和其他水母；已有smallPrey仅代理选定的小动物营养分量，不复原全部胶质食物网。',
    feedingProxy: animalProxy(), foodScope: 'small-prey',
    description: '浅碟状黄褐半透明伞铃、四条长褶皱口腕及24条较细边缘触手；以脉动和漂流共同移动，不发光。',
    colors: ['#c79a67', '#d3b998', '#a87851'],
    normalizedEnvelope: { x: [-.8, .8], y: [-8.5, .6], z: [-.8, .8], horizontalRadiusUnits: 1.14,
      axes: 'bell-axis-positive-y; transverse-x-z; upright-display',
      status: 'uncalibrated-whole-bell-four-oral-arms-twenty-four-tentacles-and-bounded-sway-clearance' },
    morphology: { form: 'shallow-disc-nettle-bell-with-four-frilly-oral-arms-and-twenty-four-marginal-tentacles',
      sizeAxis: 'bell-transverse-diameter-x-z', normalizedMeasuredSize: 1,
      rootReference: 'bell-centre', neutralMeasuredX: [-.5, .5],
      oralArms: 4, marginalTentacles: 24,
      feedingPointLocal: { x: .47, y: -7.5, z: 0 }, feedingOrgan: 'distal-marginal-stinging-tentacle',
      appendageProportionStatus: 'selected-uncalibrated-not-a-linear-bell-to-arm-length-law',
      clearanceIncludes: ['bell', 'four-oral-arms', 'twenty-four-marginal-tentacles', 'bell-pulse', 'bounded-arm-and-tentacle-sway'],
      wholeFormReference: { url: 'https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/sea-nettle',
        location: 'labelled full live medusa with separate frilly mouth-arms and fine trailing tentacles' } },
    sources: [
      source('Fannjiang等2019原始蒙特雷野外生物记录：命名个体、伞径与脉动/漂流；系绳限制不可等同自然分布', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6739807/'),
      source('Monterey Bay Aquarium官方账户：伞径与口腕分别计量、完整活体与动物食物', 'https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/sea-nettle'),
      source('Aquarium of the Pacific官方账户：浅碟铃、四口腕/24触手和近表层沿岸生境', 'https://www.aquariumofpacific.org/onlinelearningcenter/species/pacific_sea_nettle'),
    ],
  }),
  descriptor({
    id: 'opaleye', commonName: '青眼鱼', englishName: 'Opaleye',
    scientificName: 'Girella nigricans', scientificAuthor: '(Ayres, 1860)',
    family: 'Kyphosidae', familyClassificationStatus: 'source-classification-in-Love2021-and-BurtonLea2019',
    kind: 'fish', modelRole: 'opaleye', guild: 'kelp-rock-associated-omnivore-selected-algae-component',
    lengthM: .28, sizeRangeM: [.24, .32], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端的全长TL；Behrens与Lafferty2012的标准体长SL独立保留，不换算。',
    depthSelectionM: [3, 15], maximumDisplayPitchRad: .12,
    referenceSizeM: { maximum: .66, measure: 'total-length',
      separateDietStudyMeasure: 'standard-length',
      note: 'Love等2021明确66cm TL；24–32cm为展示选择，原食性研究的SL不能被冒称TL。' },
    referenceDepthM: { reportedRange: [0, 32], separateDietStudySamplingRange: [3, 15],
      dietStudyRegion: 'Southern-California-and-northern-Baja-rocky-reefs',
      note: 'Love等2021广域潮间带至约32米；食性研究3–15米不是蒙特雷当地普查，区域存在另由原蒙特雷馆藏记录支持。' },
    schooling: { enabled: false, naturalBehavior: 'schooling-in-kelp-and-shallow-rocky-water',
      naturalCount: null, displayGroupSizeStatus: 'optional-single-rock-associated-forager-not-a-complete-school' },
    habitat: ['native-rock-face-algal-patch', 'rocky-subtidal-giant-kelp-forest'],
    diet: '自然杂食，藻与动物分量随地点、栖息地和温度改变；本版只消费真实既有岩面algae，不能声称蒙特雷纯藻食已能满足完整营养。',
    feedingProxy: { owner: 'existing-kelp-simulation', stock: 'algae',
      resourcePath: 'region.sim.rockPatches[].algae', positionPath: 'region.sim.rockPatches[].position',
      selectedDietComponent: 'native-rock-algal-organic-nutrition',
      status: 'selected-component-of-natural-omnivorous-diet-at-actual-rock-patch',
      speciesResolvedFoodStock: false, visiblePreyKillImplemented: false,
      completeAlgalOnlyNutritionClaimed: false, kelpPlantOrSeagrassRemovalImplemented: false },
    foodScope: 'rock-algae',
    description: '深椭圆压扁鱼体，暗橄榄背腹、蓝绿色大眼，背上常见一至两块浅白斑，连续背鳍与浅凹叉尾。',
    colors: ['#4f6252', '#97bbad', '#d3d8c1'],
    normalizedEnvelope: fishEnvelope(),
    support: { mode: 'whole-freewater-body-near-actual-native-rock-algal-patch',
      rootReference: 'total-length-midpoint', wholeBodyDepthRequired: true,
      terrainClearanceRequired: true, kelpClearanceRequired: true, pitchClearanceRequired: true },
    morphology: { form: 'deep-oval-opaleye-with-large-blue-green-eyes-and-pale-upper-back-spots',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5],
      feedingPointLocal: { x: .5, y: 0, z: 0 }, feedingOrgan: 'mouth-at-snout-near-rock-algae',
      clearanceIncludes: ['head', 'deep-body', 'continuous-dorsal-fin', 'anal-fin', 'paired-fins', 'concave-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://aquarium.org/animals/opaleye-perch/',
        location: 'Oregon Coast Aquarium labelled whole opaleye live form and diagnostic account' } },
    sources: [
      source('Love等2021原作者鱼类名录：明确66cm TL、广域分布与潮间带至约32米', 'https://escholarship.org/content/qt26n4k816/qt26n4k816_noSplash_fe996ccfe7edd20d76837c6a59b8f3d3.pdf'),
      source('Burton与Lea2019原创蒙特雷名录：Pacific Grove/Mussel Point馆藏与当地发表记录', 'https://repository.library.noaa.gov/view/noaa/23850/noaa_23850_DS1.pdf'),
      source('Behrens与Lafferty2012原始杂食研究：3–15米采样、藻/动物分量与明确SL口径', 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0045901'),
      source('Oregon Coast Aquarium官方账户：完整眼斑体形、岩岸巨藻生境、群游与藻/小动物食物', 'https://aquarium.org/animals/opaleye-perch/'),
    ],
  }),
]);

export const kelpWaterLifeSpeciesById = freeze(Object.fromEntries(
  kelpWaterLifeSpeciesCatalog.map(species => [species.id, species]),
));
