// A separate, finite cold northeast-Pacific benthic representative catalog.
// Selected sizes, depths and mesh envelopes are implementation choices; they
// are not a measured Monterey census or calibrated ecological parameters.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius) => ({ x, y, z, horizontalRadiusUnits: radius,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-conservative-display-clearance-not-measured-anatomy' });
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '蒙特雷及东北太平洋温带巨藻林岩底的代表性组合',
  coOccurrenceStatus: 'representative-community-not-a-survey-reconstruction',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  populationDensityPerM2: null, calibratedPopulationRates: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM, status: 'illustrative-selection-not-complete-species-range' },
  depthRangeM: data.depthSelectionM,
  foodProxyStatus: 'unresolved-relative-organic-food-pool-not-complete-natural-diet',
  limitations: ['数量、位移、摄食、代谢、年龄、温度、盐度和种群参数未校准；不能解释为实测密度或完整自然食物网。',
    '尺寸、水深与几何包络是有限展示选择；不同资料的壳长、甲宽、身体长、柱高和完整展开高不能混用。'],
  ...data,
});

export const kelpBenthicLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'red-abalone', commonName: '红鲍', scientificName: 'Haliotis rufescens',
    kind: 'mollusk', guild: 'macroalgal-grazer', lengthM: .15,
    sizeRangeM: [.12, .18], sizeMeasure: 'shell-length', depthSelectionM: [3, 20],
    referenceSizeM: { commonlyTo: .20, maximum: .30, measure: 'shell-length',
      note: '太平洋水族馆给当前常见壳长约20厘米、报告上限30厘米；本场12–18厘米不是当地年龄或尺寸分布。' },
    referenceDepthM: { range: [0, 180], habitatRange: 'low-intertidal-to-subtidal',
      note: 'SIMoN资料汇编范围；本场只选浅潮下巨藻林岩底，不据此生成深海种群。' },
    normalizedEnvelope: envelope([-.56, .74], [0, .38], [-.42, .42], .87),
    colors: ['#8b4938', '#b65e46', '#373b32'],
    description: '低矮耳形砖红壳，壳缘偏红，左侧有三或四个开放隆起的呼吸孔；黑色宽足、外套膜缘和感觉触须露在壳外。',
    diet: '草食，较大个体主要利用附着或漂来的大型海藻，常摄食漂落巨藻；幼体的表面微藻饮食不能替代本场较大个体的饮食。',
    behavior: '用宽大的肌肉足附着在岩面或缝隙附近，可缓慢短距离爬行和接住漂落藻叶；不模拟繁殖、采捕或海獭捕食。',
    substrate: ['hard-rock', 'stable-rock-cap'], habitat: ['temperate-kelp-forest', 'rocky-subtidal'],
    morphology: { form: 'low-ear-shaped-red-shell-with-respiratory-pores-and-dark-foot',
      sizeAxis: 'shell-long-axis-x', respiratoryPoreCount: [3, 4], footRootY: 0,
      clearanceIncludes: ['shell', 'foot', 'epipodial-tentacles'] },
    sources: [
      source('https://www.aquariumofpacific.org/onlinelearningcenter/species/red_abalone',
        '太平洋水族馆：H. rufescens身份、壳长、冷水巨藻林、壳孔与大型藻类饮食'),
      source('https://sanctuarysimon.org/dbtools/species-database/species-info-ajax.php?sID=120',
        '蒙特雷湾SIMoN：东北太平洋范围、岩面附着、浅潮间至180米参考分布与漂落藻叶摄食'),
    ],
  }),
  descriptor({
    id: 'northern-kelp-crab', commonName: '北方藻蟹', scientificName: 'Pugettia producta',
    nameNote: '中文采用描述性译名，分类身份由拉丁学名确定。',
    kind: 'crustacean', guild: 'macroalgal-omnivore', lengthM: .06,
    sizeRangeM: [.045, .075], sizeMeasure: 'carapace-width', depthSelectionM: [3, 20],
    referenceSizeM: { maximumBySex: { male: .093, female: .078 }, measure: 'carapace-width',
      note: 'Walla Walla大学列雄9.3厘米、雌7.8厘米甲宽；腿钳展开范围不是甲宽，也不是蟹总长。' },
    referenceDepthM: { range: [0, 73], habitatRange: 'intertidal-to-subtidal',
      note: '大学自然史资料的参考范围；本场仅选巨藻林底层岩面附近。' },
    normalizedEnvelope: envelope([-1.35, 1.45], [0, .72], [-1.65, 1.65], 2.15),
    colors: ['#77734c', '#8c634c', '#3e4939'],
    description: '较平滑的角盾形甲壳略长于宽，前端双叉额角、侧缘有尖齿，绿色至褐红体色；八条细长步足和两只螯构成完整展开轮廓。',
    diet: '主要吃海藻，也可摄食小螺及其他小型动物；2017年原始试验确认既吃牛海带也吃Lacuna小螺，不应称为专性草食。',
    behavior: '可在林底或藻体上活动；本版限定在真实岩底短距离行走，不模拟攀爬活藻叶、季节迁移、蜕壳或繁殖。昼夜规则为展示参数，资料未给可靠的专一夜活节律。',
    substrate: ['hard-rock', 'stable-rock-cap'], habitat: ['temperate-kelp-forest', 'rocky-subtidal'],
    morphology: { form: 'smooth-angular-shield-with-bifid-rostrum-long-legs-and-paired-claws',
      sizeAxis: 'carapace-width-z', walkingLegPairs: 4, clawPairs: 1, footRootY: 0,
      clearanceIncludes: ['carapace', 'all-eight-walking-legs', 'both-claws'] },
    sources: [
      source('https://aquarium.org/animals/kelp-crab/',
        '俄勒冈海岸水族馆：巨藻林生境、长足、甲宽口径及藻类/小动物杂食'),
      source('https://inverts.wallawalla.edu/Arthropoda/Crustacea/Malacostraca/Eumalacostraca/Eucarida/Decapoda/Brachyura/Family_Majidae/Pugettia_producta.html',
        'Walla Walla大学现场自然史：平滑盾形/双叉额角、雌雄甲宽、底层/藻体活动与0–73米'),
      source('https://pubmed.ncbi.nlm.nih.gov/28560113/',
        'Dobkowski（2017）原始摄食试验：P. producta摄食牛海带及Lacuna小螺；Salish Sea研究不是本场实测'),
      source('https://peerj.com/articles/3372.pdf',
        'Dobkowski（2017）全文：昼夜摄食试验，未建立可靠的专一夜活节律'),
    ],
  }),
  descriptor({
    id: 'california-sea-hare', commonName: '加州褐海兔', scientificName: 'Aplysia californica',
    nameNote: '与黑海兔Aplysia vaccaria分别；本场不采用黑海兔的大体型上限。',
    kind: 'mollusk', guild: 'macroalgal-grazer', lengthM: .14,
    sizeRangeM: [.10, .18], sizeMeasure: 'body-length', depthSelectionM: [3, 15],
    referenceSizeM: { maximum: .40, typicalApproximation: .20, measure: 'body-length',
      note: '太平洋水族馆给身体长最多40厘米，多数约其一半；本场10–18厘米不能反推出实测年龄。' },
    referenceDepthM: { juvenileMaximum: 18.3, adultHabitat: 'middle-and-lower-shallow-tidal-zones',
      note: '成人与幼体生境不同。本场3–15米采用较小幼体生境代表，未校准尺寸与年龄关系；不声称20米成体群落。' },
    displayLifeStage: { stage: 'smaller-juvenile-habitat-representative', calibratedAgeSec: null,
      status: 'illustrative-stage-selection-not-inferred-from-measured-size-age-curve' },
    normalizedEnvelope: envelope([-.51, .66], [0, .50], [-.36, .36], .76),
    colors: ['#77664e', '#63734c', '#aa8f68'],
    description: '褐绿斑驳软体动物，背部有一对折起的侧足叶，头部两对触角含耳形嗅角；没有外露螺壳，身体沿宽足爬行。',
    diet: '草食，食谱随生长改变，幼体可在红藻上取食，较浅水较大个体会利用更多褐藻和绿藻；不把未分辨库存称作完整自然食谱。',
    behavior: '在藻类覆盖的受庇护岩底缓慢爬行，头部和嗅角轻微活动；本版不模拟喷墨、交配串、卵团或浮游幼生。',
    substrate: ['vegetated-hard-rock', 'stable-rock-cap'], habitat: ['sheltered-temperate-coast', 'kelp-understory-edge'],
    morphology: { form: 'mottled-shell-less-sea-hare-with-folded-parapodia-and-four-head-tentacles',
      sizeAxis: 'body-long-axis-x', externalShell: false, headTentaclePairs: 2, footRootY: 0,
      clearanceIncludes: ['body', 'parapodia', 'head-tentacles'] },
    sources: [
      source('https://www.aquariumofpacific.org/onlinelearningcenter/species/california_brown_sea_hare/',
        '太平洋水族馆：A. californica身份、成/幼体生境、40厘米身体长、侧足/触角及生长阶段藻类饮食'),
      source('https://www.montereybayaquarium.org/visit/exhibits/kelp-forest',
        '蒙特雷湾水族馆巨藻林展示：Sea hare为该生态展示中的类群，单独不证明物种或野外同地密度'),
    ],
  }),
  descriptor({
    id: 'giant-plumose-anemone', commonName: '巨羽状海葵', scientificName: 'Metridium farcimen',
    nameNote: '与较小的Metridium senile分别；1989年前混称资料不能直接作为本种速率校准。',
    kind: 'anemone', guild: 'suspension-feeder', lengthM: .25,
    sizeRangeM: [.18, .32], sizeMeasure: 'expanded-column-height', depthSelectionM: [3, 25],
    referenceSizeM: { reportedHeightTo: .50, exceptionalMaximumHeight: 1, crownDiameterTo: .25,
      measure: 'complete-expanded-height',
      note: '资料50厘米常见参考高/最高1米与冠径25厘米；本场柱高18–32厘米为展示选择，冠部另含在1.4倍柱高包络内，不把柱高等同资料完整展开高。' },
    referenceDepthM: { maximumAtLeast: 200, observedExample: 15,
      note: '大学自然史：潮下至少200米，含2019年15米小个体现场照片；本场只选浅潮下岩底。' },
    normalizedEnvelope: envelope([-.72, .72], [0, 1.40], [-.72, .72], .84),
    colors: ['#c9c8b5', '#dad8c4', '#8f8c77'],
    description: '真实附着动物：宽足盘、较高平滑圆柱体和深分叶口盘，冠缘有大量细密触手呈羽状花冠；浅乳白至棕色，整体不是植物或珊瑚装饰。',
    diet: '用刺细胞触手捕捉水流带来的浮游及其他悬浮小动物；2022年原始DNA研究支持多样动物性食物，不能把它当作光合生产者。',
    behavior: '附着在稳定岩面，保持同一个体和根部位置，柱体与触手有有限展开活动；自然可极慢移动，本版未模拟迁移、无性繁殖或具体浮游猎物捕获。',
    substrate: ['hard-rock', 'stable-rock-cap'], habitat: ['temperate-rocky-subtidal', 'kelp-forest-rock-edge'],
    morphology: { form: 'attached-pedal-disc-smooth-column-lobed-oral-disc-and-fine-plumose-crown',
      sizeAxis: 'expanded-column-height-y', columnHeightEndsAt: 'oral-column-shoulder-excluding-crown',
      maximumCompleteHeightUnits: 1.40, footRootY: 0, clearanceIncludes: ['pedal-disc', 'column', 'expanded-crown'] },
    sources: [
      source('https://inverts.wallawalla.edu/Cnidaria/Class-Anthozoa/Subclass_Zoantharia/Order_Actiniaria/Metridium_farcimen.html',
        'Walla Walla大学现场自然史：身份、完整高/冠径、岩面附着、15米个体与旧分类局限'),
      source('https://onlinelibrary.wiley.com/doi/10.1002/edn3.225',
        'Wells等（2022）原始DNA食谱研究：东北太平洋M. farcimen为悬浮摄食动物，记录多样动物性食物'),
      source('https://sanctuarysimon.org/dbtools/species-database/species-info-ajax.php?sID=108',
        '蒙特雷湾SIMoN：巨藻林/岩底代表、深分叶冠、展开形态与1米完整高上限；表格0–0水深占位不作分布数据'),
    ],
  }),
]);

export const kelpBenthicLifeSpeciesById = freeze(Object.fromEntries(
  kelpBenthicLifeSpeciesCatalog.map(row => [row.id, row])));
