// Six genuinely new v5 representatives. Chosen sizes and full display bounds
// describe this finite implementation, not calibrated wild densities or rates.
const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) {
  Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, horizontalRadiusUnits) => ({ x, y, z, horizontalRadiusUnits,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'conservative-display-whole-form-and-bounded-animation-not-measured-anatomy' });
const support = (bottom = false, footContacts = []) => ({ mode: bottom ? 'whole-foot-supported-reef-margin' : 'whole-freewater-body-near-real-reef',
  rootReference: bottom ? 'neutral-foot-plane' : 'total-length-midpoint', pitchLimitRad: bottom ? 0 : .10,
  minimumNormalY: .92, footContacts, wholeBodyDepthRequired: true, terrainClearanceRequired: true });
const food = (pool, component) => ({ owner: pool.split('.')[0], stock: pool.split('.')[1], resourcePath: `region.${pool}`,
  selectedFoodComponent: component, status: 'existing-selected-organic-proxy-not-complete-natural-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false });
const descriptor = data => freeze({ regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带西太平洋浅礁、礁边沙底与潟湖的有限代表组合', coOccurrenceStatus: 'representatives-not-a-local-field-survey',
  ecologicalRateStatus: 'uncalibrated-demonstration', calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  naturalPopulationDensity: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM ?? [3, 18], status: 'chosen-whole-model-depth-not-complete-natural-range' },
  depthSelectionM: data.depthSelectionM ?? [3, 18], depthRangeM: data.depthSelectionM ?? [3, 18],
  limitations: ['程序造型、出生数量、运动和摄食速率未作野外校准；不是完整食物网或种群预测。',
    '只扣除当地已存在的选定营养代理，不出生食物、不捕杀具体动物，也不代表完整天然食谱。'],
  ...data, sourceLinks: data.sources.map(item => ({ ...item })) });
const fishForm = form => ({ form, normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5], sizeAxis: 'snout-to-farthest-caudal-tip-x',
  clearanceIncludes: ['body', 'head-form', 'mouth', 'eyes', 'complete-caudal-fin', 'all-other-fins', 'bounded-fin-motion'] });
const crabFeet = [-.23, -.10, .03, .16].flatMap(x => [-.62, .62].map(z => ({ x, y: 0, z })));
const sole = halfWidth => [-.30, 0, .30].flatMap(x => [-halfWidth, halfWidth].map(z => ({ x, y: 0, z })));

export const OCEAN_REEF_FAUNA_SPECIES = freeze([
  descriptor({ id: 'humphead-wrasse', commonName: '曲纹唇鱼（隆头鱼）', scientificName: 'Cheilinus undulatus', scientificAuthor: 'Rüppell, 1835',
    kind: 'fish', guild: 'large-reef-animal-consumer', lengthM: 1, sizeRangeM: [.85, 1.15], sizeMeasure: 'total-length', depthSelectionM: [10, 18],
    sizeMeasureDefinition: '吻端至圆尾最远端全长；选择有额隆和厚唇的成年形态，不推定所有该长度个体的性别或成熟年龄。',
    lifeStageSelection: 'adult-form-with-hump-and-thick-lips; chosen-size-not-a-maturity-threshold',
    referenceSizeM: { maximum: 2.30, measure: 'total-length' }, referenceDepthM: { reportedRange: [2, 100], largerIndividualsUsually: [10, 100], completeNaturalRange: false },
    colors: ['#638b64', '#4c6d46', '#738d5c'], normalizedEnvelope: envelope([-.54, .54], [-.30, .34], [-.20, .20], .58),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06 }, morphology: fishForm('large-deep-thick-green-wrasse-with-bulbous-forehead-thick-lips-and-rounded-tail'),
    description: '大型厚体、明显额隆、厚唇、圆尾、眼后两条曲线及绿色波纹体色，轮廓区别于小型裂唇鱼和石斑鱼。',
    diet: '自然食软体动物、甲壳动物、鱼和棘皮动物等；本版只使用现有未解析动物营养的选定分量，不实现对海胆、海星或鱼的具体捕杀。',
    behavior: '在10–18米实际近礁水层有限巡游与停留，保持整个额隆、厚体与鳍尾净空；不模拟性转换、繁殖聚集或野外数量。',
    habitat: ['outer-coral-reef', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-mollusc-crustacean-fish-and-echinoderm-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2962', 'Museums Victoria：C.undulatus身份、成年额隆厚唇、动物食性及230cm TL、2–100m资料'),
      source('https://australian.museum/learn/animals/fishes/humphead-maori-wrasse-cheilinus-undulatus/', 'Australian Museum：成年厚体圆尾及较大个体常见外礁10–100m；全文已读')] }),
  descriptor({ id: 'bluespine-unicornfish', commonName: '青斑鼻鱼（蓝棘独角鱼，描述性中文名）', scientificName: 'Naso unicornis', scientificAuthor: '(Forsskål, 1775)',
    kind: 'fish', guild: 'reef-macroalgal-grazer', lengthM: .475, sizeRangeM: [.40, .55], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端全长；参考70cm为叉长FL而非本模型全长TL，不将二者数值作直接换算。',
    lifeStageSelection: 'horn-bearing-large-form; chosen-size-not-a-maturity-threshold',
    referenceSizeM: { maximum: .70, measure: 'fork-length', directlyConvertedToTotalLength: false }, referenceDepthM: { reportedRange: [1, 80], completeNaturalRange: false },
    colors: ['#788566', '#37658c', '#9d974a'], normalizedEnvelope: envelope([-.54, .54], [-.30, .31], [-.17, .17], .57),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06 },
    morphology: { ...fishForm('grey-green-unicornfish-with-short-forehead-horn-and-blue-peduncle-scalpel-plates'), hornMustNotProjectBeyondMouth: true },
    description: '灰绿侧扁大鱼、短额角、尾柄两侧蓝色骨板和朝前刀棘、黄褐长背臀鳍及蓝边；短角不超过嘴端。',
    diet: '自然以宏藻为食；本版只消费当地已有algae库存选定分量，不宣称库存已区分天然宏藻种类或已逐株啃食。',
    behavior: '真实潟湖及外礁邻近净空内有限巡游；不实现求偶变色、群体社会行为或野外密度。',
    habitat: ['coral-lagoon', 'outer-reef', 'near-reef-freewater'], foodPool: 'resources.algae',
    feedingProxy: food('resources.algae', 'selected-macroalgal-nutrition-component-of-unresolved-algae'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2201', 'Museums Victoria：N.unicornis短角不越吻、蓝尾柄骨板、宏藻食性与70cm FL、1–80m资料；全文已读')] }),
  descriptor({ id: 'clown-triggerfish', commonName: '花斑拟鳞鲀（小丑炮弹鱼）', scientificName: 'Balistoides conspicillum', scientificAuthor: '(Bloch & Schneider, 1801)',
    kind: 'fish', guild: 'reef-benthic-animal-consumer', lengthM: .35, sizeRangeM: [.30, .40], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端全长；采用成年黑底腹侧白大斑、背部黄网纹和橙唇组合，不混用幼体黄背块。',
    lifeStageSelection: 'adult-color-pattern; chosen-size-not-a-maturity-threshold',
    referenceSizeM: { maximum: .50, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 75], completeNaturalRange: false },
    colors: ['#192015', '#d3cfac', '#bc7d26'], normalizedEnvelope: envelope([-.54, .54], [-.35, .43], [-.18, .18], .58),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06 }, morphology: fishForm('deep-adult-black-triggerfish-with-large-white-lower-spots-yellow-upper-network-and-orange-lips'),
    description: '厚侧扁黑体、腹侧大白圆斑、背部黄色网纹、眼前浅横带、橙唇、独立扳机棘与完整软背臀鳍，区别于已有红齿鳞鲀。',
    diet: '自然摄取海胆、甲壳动物、软体动物及海鞘等底栖动物；本版仅扣除未解析动物营养选定分量，不模拟实际碎壳或捕杀。',
    behavior: '清澈礁缘实际水层有限巡游与停留；不声称已实现攻击领域、洞穴扳机锁定或完整取食动作。',
    habitat: ['coastal-coral-reef', 'outer-reef-edge', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-invertebrate-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/761', 'Museums Victoria：B.conspicillum成年斑纹与幼体差别、底栖动物食性及50cm TL、1–75m资料；全文已读')] }),
  descriptor({ id: 'shame-faced-crab', commonName: '肝叶馒头蟹（羞面箱蟹，描述性中文名）', scientificName: 'Calappa hepatica', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'crustacean', guild: 'soft-sand-mollusc-consumer', lengthM: .0625, sizeRangeM: [.05, .075], sizeMeasure: 'carapace-width',
    sizeMeasureDefinition: '背甲横向最宽处CW，不含步足或举起的螯；归一化壳横向Z宽为1，身体长度不是1。',
    referenceSizeM: { maximum: .08, measure: 'carapace-width' }, referenceDepthM: { reportedRange: [0, 100], completeNaturalRange: false },
    colors: ['#aa9d75', '#8c8263', '#c1b487'], normalizedEnvelope: envelope([-.44, .72], [0, .48], [-.75, .75], 1.05),
    support: support(true, crabFeet), animationBounds: { footContactsStationary: true, chelaSwingRad: .02 },
    morphology: { form: 'broad-domed-box-carapace-with-paired-front-shield-chelae-and-eight-real-walking-feet', normalizedMeasuredSize: 1,
      shellMeasuredZ: [-.5, .5], sizeAxis: 'transverse-carapace-width-z', walkingPairCount: 4, chelatePairCount: 1,
      clearanceIncludes: ['full-carapace', 'posterolateral-shield', 'eight-walking-legs', 'raised-paired-chelae', 'eyes', 'bounded-animation'] },
    description: '宽圆拱背甲与外展后侧壳盾、脸前折叠的大螯、四对真实步足；右螯切壳齿属于形态参考，不当作支撑足。',
    diet: '自然主要摄取螺等软体动物；本版只消耗未解析动物营养代理，不打碎具体螺壳或减少任何可见螺个体。',
    behavior: '真实裸沙和贝砂底有限慢行，保留八足与全螯净空；不生成假沙洞或宣称实现天然埋沙。',
    substrate: ['real-soft-sand', 'actual-seagrass-associated-sediment'], habitat: ['reef-sand-patch', 'shallow-shelly-sand'],
    foodPool: 'reefGuild.preyOrganicUnits', feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-molluscan-animal-nutrition-component'),
    sources: [source('https://decapoda.nhm.org/pdfs/4113/4113.pdf', 'FAO 1998西中太平洋资源指南，NHM文献库：C.hepatica账户p1097/PDF59，8cm CW、潮间至100m沙贝砂草床及壳盾形态'),
      source('https://churaumi.okinawa/sp/fishbook/1459424511/', '冲绳美丽海水族馆本种记录：浅砂底、自然食螺与常埋沙；全文已读')] }),
  descriptor({ id: 'wedge-sea-hare', commonName: '耳形海兔（楔形海兔，描述性中文名）', scientificName: 'Dolabella auricularia', scientificAuthor: '(Lightfoot, 1786)',
    kind: 'mollusc', guild: 'sheltered-lagoon-macroalgal-grazer', lengthM: .13, sizeRangeM: [.10, .16], sizeMeasure: 'body-total-length', depthSelectionM: [3, 15],
    sizeMeasureDefinition: '未额外伸长的前端身体至后端盘体全长；触角与完整后盾计入空间包络。',
    referenceSizeM: { reportedMaximum: .50, measure: 'body-total-length', source: 'DORIS',
      museumObservedLength: .20, note: '来源对尺寸上限陈述不同；选择10–16cm展示，不将上限作为校准体型分布。' },
    referenceDepthM: { reportedRange: [0, 15], approximate: true, completeNaturalRange: false },
    colors: ['#797e50', '#676347', '#ada474'], normalizedEnvelope: envelope([-.54, .61], [0, .53], [-.36, .36], .72),
    support: support(true, sole(.12)), animationBounds: { footContactsStationary: true, rhinophoreYawRad: .03, bodyPulseUnits: .003 },
    morphology: { form: 'green-brown-wedge-sea-hare-with-flattened-posterior-disc-and-two-siphon-openings', normalizedMeasuredSize: 1,
      bodyMeasuredX: [-.5, .5], sizeAxis: 'body-front-to-posterior-disc-x', continuousMuscularSole: true, oralTentacleCount: 2, rhinophoreCount: 2,
      clearanceIncludes: ['continuous-muscular-foot', 'body', 'rear-disc', 'two-oral-tentacles', 'two-rhinophores', 'bounded-animation'] },
    description: '褐绿斑驳楔体、近竖直扁后盘、融合侧足与两出入水口、两口触角和两嗅角；内部壳不做外露大螺壳。',
    diet: '自然摄取混合红、褐、绿宏藻及部分海生植物；本版仅选择既有algae有机分量，不能当作完整宏藻或海草食谱。',
    behavior: '真实受保护潟湖沙草缘有限慢移；固定腹足采样只用于展示支撑，不声称模拟校准的前伸后收步态、喷墨或夜行节律。',
    substrate: ['real-soft-sand', 'actual-seagrass-associated-sediment'], habitat: ['sheltered-algal-lagoon', 'shallow-reef-sand-margin'],
    foodPool: 'resources.algae', feedingProxy: food('resources.algae', 'selected-mixed-macroalgal-nutrition-component-of-unresolved-algae'),
    sources: [source('https://www.seaslugforum.net/factsheet/dolaauri', 'Australian Museum作者Bill Rudman：D.auricularia楔体后盾、双水口、浅沙泥草潟湖及混合宏藻食性；全文已读'),
      source('https://doris.ffessm.fr/Especes/Dolabella-auricularia-Lievre-de-mer-a-oreille-2104', 'FFESSM DORIS作者物种资料：后盘近90度、融合侧足双口、约15m浅潟湖及伸缩移步；来源尺寸上限不同已标明')] }),
  descriptor({ id: 'varicose-phyllidia', commonName: '疣状叶海蛞蝓（描述性中文名）', scientificName: 'Phyllidia varicosa', scientificAuthor: 'Lamarck, 1801',
    kind: 'mollusc', guild: 'reef-sponge-animal-consumer', lengthM: .065, sizeRangeM: [.05, .08], sizeMeasure: 'body-total-length', depthSelectionM: [5, 18],
    sizeMeasureDefinition: '完整椭圆体前端至后端全长，不以背瘤或嗅角高度作为体长；腹面连续足底为支撑。',
    referenceSizeM: { maximum: .11, measure: 'body-total-length' }, referenceDepthM: { reportedMinimum: 5, museumObservedDepths: [4, 10, 22], completeNaturalRange: false },
    colors: ['#899b9b', '#282d25', '#c4b851'], normalizedEnvelope: envelope([-.54, .54], [0, .33], [-.25, .25], .62),
    support: support(true, sole(.10)), animationBounds: { footContactsStationary: true, rhinophoreYawRad: .03, bodyPulseUnits: .002 },
    morphology: { form: 'blue-grey-longitudinal-ridged-phyllidia-with-yellow-tubercles-and-undermantle-gill-lamellae', normalizedMeasuredSize: 1,
      bodyMeasuredX: [-.5, .5], sizeAxis: 'whole-oval-body-length-x', continuousMuscularSole: true, rhinophoreCount: 2,
      dorsalGillPlumePresent: false, radulaPresent: false, jawPresent: false,
      clearanceIncludes: ['continuous-muscular-foot', 'body', 'longitudinal-ridges', 'yellow-tubercles', 'two-rhinophores', 'undermantle-lamellae', 'bounded-animation'] },
    description: '灰蓝纵脊与黄顶瘤、黑色间纹、两黄嗅角、腹面黑纵线和裙下鳃片；不添加普通裸鳃类的后背羽鳃圈。',
    diet: '自然专食海绵，已报道Halichondria、Hymeniacidon、Axinyssa等属；本版只选择未解析动物营养分量，不把它称为藻食或颗粒滤食。',
    behavior: '真实5米以下礁面有限慢行；不宣称已实现特定海绵库存消化、真实外翻肠摄食、毒性或普通海兔式齿舌刮食。',
    substrate: ['real-stable-hard-reef-surface'], habitat: ['coral-reef-surface', 'reef-sponge-associated'],
    foodPool: 'reefGuild.preyOrganicUnits', feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-sponge-animal-nutrition-component; sponge-species-stock-not-resolved'),
    sources: [source('https://www.seaslugforum.net/factsheet/phylvari', 'Australian Museum作者Bill Rudman/Brunckhorst资料：P.varicosa灰蓝黄纵脊、腹足黑线及4–10m/22m观察；全文已读'),
      source('https://www.seaslugforum.net/find/3051', 'Australian Museum作者Bill Rudman：P.varicosa须食特定海绵，不能以普通漂浮颗粒代替天然食谱'),
      source('https://doris.ffessm.fr/Especes/Phyllidia-varicosa-Phyllidie-verruqueuse-528', 'FFESSM DORIS作者Véronique Lamare/Yves Müller：5m起礁区、110mm体长、海绵食性、无颚无齿舌及裙下鳃片；全文已读')] }),
]);
export const OCEAN_REEF_FAUNA_IDS = freeze(OCEAN_REEF_FAUNA_SPECIES.map(s => s.id));
export const oceanReefFaunaSpeciesById = freeze(Object.fromEntries(OCEAN_REEF_FAUNA_SPECIES.map(s => [s.id, s])));
