// Six finite v2 representatives. Units, rates and admission choices are display
// selections; source ecology does not calibrate density or complete food webs.
const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) {
  Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, horizontalRadiusUnits) => ({ x, y, z, horizontalRadiusUnits,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'conservative-display-whole-form-and-bounded-animation-not-measured-anatomy' });
const support = (bottom = false, footContacts = []) => ({ mode: bottom ? 'whole-foot-supported-reef-margin' : 'whole-freewater-body-near-real-reef',
  rootReference: bottom ? 'neutral-foot-plane' : 'total-length-midpoint', pitchLimitRad: bottom ? 0 : .10,
  minimumNormalY: .92, footContacts, wholeBodyDepthRequired: true, terrainClearanceRequired: true });
const food = (pool, component) => ({ owner: pool.split('.')[0], stock: pool.split('.')[1], resourcePath: `region.${pool}`,
  selectedFoodComponent: component, status: 'existing-selected-organic-proxy-not-complete-natural-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false });
const descriptor = data => freeze({ regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带西太平洋浅珊瑚礁的有限代表组合', coOccurrenceStatus: 'representatives-not-a-local-field-survey',
  ecologicalRateStatus: 'uncalibrated-demonstration', calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  naturalPopulationDensity: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: [3, 18], status: 'chosen-whole-model-depth-not-complete-natural-range' },
  depthSelectionM: [3, 18], depthRangeM: [3, 18],
  limitations: ['程序造型、出生数量、运动及摄食速率未作野外校准；不是完整食物网或种群预测。',
    '只消费当地已存在的选定有机营养代理，不生成食物、不捕杀具体可见动物，也不代表完整自然食谱。'],
  ...data, sourceLinks: data.sources.map(item => ({ ...item })) });
const fishMorphology = form => ({ form, normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5],
  sizeAxis: 'snout-to-farthest-caudal-tip-x', clearanceIncludes: ['body', 'mouth', 'eyes', 'all-fins', 'spines-or-filaments', 'bounded-fin-motion'] });
const starFeet = Array.from({ length: 5 }, (_, i) => [.16, .32].map(radius => ({
  x: radius * Math.cos(i * Math.PI * 2 / 5), y: 0, z: radius * Math.sin(i * Math.PI * 2 / 5) }))).flat();
const cucumberFeet = [-.36, -.18, 0, .18, .36].flatMap(x => [-.09, .09].map(z => ({ x, y: 0, z })));

export const OCEAN_REEF_DIVERSITY_SPECIES = freeze([
  descriptor({ id: 'lionfish', commonName: '蓑鲉（狮子鱼）', scientificName: 'Pterois volitans', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'fish', guild: 'reef-animal-predator', lengthM: .25, sizeRangeM: [.20, .30], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍最远端的全长，长棘和外展胸鳍另计入完整空间包络。',
    referenceSizeM: { maximum: .38, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 128], completeNaturalRange: false },
    colors: ['#a85840', '#dcd0b3', '#3e3029'], normalizedEnvelope: envelope([-.54, .54], [-.34, .78], [-.62, .62], .83),
    support: support(), animationBounds: { tailYawRad: .10, pectoralRollRad: .035 }, morphology: fishMorphology('striped-lionfish-with-radiating-pectoral-rays-and-long-dorsal-spines'),
    description: '红褐与浅色竖带、长背棘、两侧辐射扇形胸鳍、头部皮瓣和完整尾鳍，保留狮子鱼的宽大轮廓。',
    diet: '自然摄食鱼类和甲壳类；本版仅使用当地未解析动物营养代理，不模拟真实可见猎物捕杀。',
    behavior: '真实礁缘净空内有限缓游和停留；夜间伏击食性为参考，未实现完整伏击、喷流或毒棘接触。',
    habitat: ['coral-reef-edge', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'unresolved-fish-and-crustacean-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2113', 'Museums Victoria：P.volitans长背棘、扇形胸鳍、鱼与甲壳类食性及38cm TL、1–128m资料')] }),
  descriptor({ id: 'chinese-trumpetfish', commonName: '中华喇叭鱼（描述性中文名）', scientificName: 'Aulostomus chinensis', scientificAuthor: '(Linnaeus, 1766)',
    kind: 'fish', guild: 'reef-animal-predator', lengthM: .55, sizeRangeM: [.45, .65], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '细长管吻至尾鳍末端的全长；不混用海龙或带尾丝的烟管鱼。',
    referenceSizeM: { maximum: .90, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 125], completeNaturalRange: false },
    colors: ['#aa973a', '#6c774b', '#242c26'], normalizedEnvelope: envelope([-.54, .54], [-.11, .13], [-.10, .10], .56),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .05 }, morphology: fishMorphology('long-tubular-snout-slender-trumpetfish-with-posterior-dorsal-and-anal'),
    description: '长管嘴、细长侧扁身体、短背棘、靠后且上下对应的背臀鳍与小尾鳍，采用黄褐体色代表型。',
    diet: '自然伏击小鱼及甲壳类；本版只消费当地未解析动物营养代理，不宣称具体猎物已被捕杀。',
    behavior: '有限水平缓游和停留；真实物种的头朝下伪装、跟随大型鱼狩猎与快速吸食没有在本版实现。',
    habitat: ['coral-reef-edge', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'unresolved-small-fish-and-crustacean-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/1875', 'Museums Victoria：A.chinensis管吻、后置背臀鳍、短背棘、伏击食性及90cm TL、1–125m资料')] }),
  descriptor({ id: 'moorish-idol', commonName: '镰鱼（角镰鱼）', scientificName: 'Zanclus cornutus', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'fish', guild: 'reef-attached-animal-consumer', lengthM: .19, sizeRangeM: [.16, .22], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '管状吻端至尾鳍末端的全长；背鳍长丝不算身体全长，但完整计入空间包络。',
    referenceSizeM: { maximum: .23, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 182], completeNaturalRange: false },
    colors: ['#e0d7b5', '#202725', '#d8b834'], normalizedEnvelope: envelope([-.65, .54], [-.40, .94], [-.15, .15], .69),
    support: support(), animationBounds: { tailYawRad: .12, pectoralRollRad: .07, dorsalFilamentYawRad: .02 },
    morphology: fishMorphology('black-white-yellow-disc-bodied-moorish-idol-with-long-sickle-dorsal-filament'),
    description: '薄圆盘鱼体、黑白黄宽色带、黄色吻鞍、管状小嘴与向后弯曲的长背鳍丝。',
    diet: '自然主要食附着海绵，也食珊瑚虫、海鞘等底栖无脊椎动物；本版动物营养池只代理未解析海绵等选定分量，不把藻类当作完整食谱。',
    behavior: '在真实礁缘净空内短程缓游和停留；没有真实海绵种群库存、完整咬食过程或必然成对行为。',
    habitat: ['coral-reef-edge', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'unresolved-encrusting-sponge-and-other-attached-animal-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/Home/species/1891', 'Museums Victoria：Z.cornutus圆盘体、长背鳍丝、主要附着海绵食性及23cm TL、1–182m资料')] }),
  descriptor({ id: 'sailfin-tang', commonName: '帆鳍刺尾鱼（描述性中文名）', scientificName: 'Zebrasoma velifer', scientificAuthor: '(Bloch, 1795)',
    taxonomicNote: '采用Eschmeyer种目录有效拼写Z.velifer；Museums Victoria生物资料页沿用Z.veliferum。',
    kind: 'fish', guild: 'reef-algal-grazer', lengthM: .27, sizeRangeM: [.22, .32], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍末端的全长，展开帆形背臀鳍另计入完整空间包络；不把SL参考直接换算为TL。',
    referenceSizeM: { maximum: null, measure: 'not-used-for-display-calibration' },
    referenceDepthM: { reportedMaximum: 45, completeNaturalRange: false }, colors: ['#9a9559', '#474f43', '#d2b946'],
    normalizedEnvelope: envelope([-.54, .54], [-.60, .69], [-.15, .15], .57), support: support(),
    animationBounds: { tailYawRad: .12, pectoralRollRad: .07 }, morphology: fishMorphology('tall-sail-dorsal-and-anal-barred-compressed-surgeonfish'),
    description: '侧扁鱼体、高耸帆形背鳍、宽大臀鳍、深浅竖条带、黄褐尾鳍和尾柄两侧短刺。',
    diet: '自然啃食藻坪和大型叶状藻；本版只消费当地已有藻类有机库存的选定代理，不校准实际藻种或摄食速率。',
    behavior: '真实礁缘净空内有限缓游与觅食；未实现可伸缩尾柄刺防御、繁殖或完整群体关系。',
    habitat: ['coral-reef-edge', 'near-reef-freewater'], foodPool: 'resources.algae', feedingProxy: food('resources.algae', 'selected-algal-organic-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2205', 'Museums Victoria：Z.veliferum生物资料的帆形背鳍、条带、藻坪食性与45m资料'),
      source('https://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?genus=Zebrasoma&tbl=species', 'California Academy of Sciences原作者种目录：当前有效拼写Zebrasoma velifer；读取索引记录')] }),
  descriptor({ id: 'cushion-sea-star', commonName: '新几内亚枕海星（描述性中文名）', scientificName: 'Culcita novaeguineae', scientificAuthor: 'Müller & Troschel, 1842',
    kind: 'echinoderm', guild: 'reef-coral-consumer', lengthM: .25, sizeRangeM: [.20, .30], sizeMeasure: 'body-diameter',
    sizeMeasureDefinition: '水平身体直径，含近五角形边缘；不把海星管足或枕状体高混作全长。',
    referenceSizeM: { maximum: null, measure: 'not-used-for-display-calibration' }, referenceDepthM: { completeNaturalRange: false },
    colors: ['#b5945b', '#806e47', '#d1b57a'], normalizedEnvelope: envelope([-.54, .54], [0, .44], [-.54, .54], .77),
    support: support(true, starFeet), animationBounds: { footContactsStationary: true, papillaPulseUnits: .006 },
    morphology: { form: 'fivefold-inflated-cushion-star-with-ventral-tube-feet', normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5],
      sizeAxis: 'horizontal-body-diameter', clearanceIncludes: ['whole-cushion-body', 'papillae', 'ventral-tube-feet', 'bounded-animation'] },
    description: '近五角的鼓垫身体、短乳突及五条腹面步带管足；口位于腹面中央，不作为脚点。',
    diet: '原始实验显示摄食珊瑚；本版仅使用真实珊瑚附近的既有珊瑚有机库存，未校准珊瑚属偏好或真实胃外翻。',
    behavior: '在真实礁脚支撑面有限慢行与停留；野外夜间摄食和庇护为参考，未实现完整攀礁或胃外翻。',
    substrate: ['stable-hard-reef-margin', 'stable-reef-foot-sediment'], habitat: ['shallow-coral-reef', 'reef-foot'],
    foodPool: 'basicNetwork.coralOrganicUnits', feedingProxy: food('basicNetwork.coralOrganicUnits', 'selected-real-nearby-coral-organic-component'),
    sources: [source('https://doi.org/10.1016/0022-0981(86)90014-6', 'Glynn与Krupp原始摄食研究（1986）：C.novaeguineae珊瑚摄食；读取论文索引摘要'),
      source('https://escholarship.org/uc/item/7b94s417', 'UC Berkeley Hawkins原作者研究（2006）：珊瑚选择、夜间摄食和现场礁体邻近观察；读取作者PDF索引正文')] }),
  descriptor({ id: 'leopard-sea-cucumber', commonName: '豹斑白尼参（描述性中文名）', scientificName: 'Bohadschia argus', scientificAuthor: 'Jaeger, 1833',
    kind: 'echinoderm', guild: 'reef-sediment-deposit-feeder', lengthM: .34, sizeRangeM: [.28, .40], sizeMeasure: 'body-total-length',
    sizeMeasureDefinition: '活体前端至后端的身体长度；不使用加工干制长度，前部摄食触手另计入完整包络。',
    referenceSizeM: { maximumApproximate: .60, commonApproximate: .36, measure: 'fresh-body-length', driedLengthUsed: false },
    referenceDepthM: { regionalRange: [0, 30], region: 'western-central-Pacific', completeNaturalRange: false },
    colors: ['#a69468', '#3a352d', '#cabc94'], normalizedEnvelope: envelope([-.54, .70], [0, .29], [-.18, .18], .73),
    support: support(true, cucumberFeet), animationBounds: { footContactsStationary: true, tentacleYawRad: .025, bodyPulseUnits: .004 },
    morphology: { form: 'arched-flat-bellied-leopard-spotted-cucumber-with-oral-tentacles-and-ventral-podia', normalizedMeasuredSize: 1,
      bodyMeasuredX: [-.5, .5], sizeAxis: 'fresh-body-length-excluding-tentacles-x',
      clearanceIncludes: ['soft-body', 'papillae', 'ventral-tube-feet', 'front-feeding-tentacles', 'bounded-animation'] },
    description: '圆柱形软体、背弓腹平、深色边框的眼状斑点、腹面管足与前端短摄食触手。',
    diet: '沉积摄食选定代理只使用当地碎屑有机库存，不把它称为全部沉积物、细菌或完整微藻食谱。',
    behavior: '真实珊瑚礁旁软沙底的有限慢行与停留；没有真实吞砂排砂、埋藏、居鱼共栖或防御排丝过程。',
    substrate: ['real-soft-sand-near-reef'], habitat: ['shallow-coral-reef', 'reef-foot-sand'], foodPool: 'resources.detritus',
    feedingProxy: food('resources.detritus', 'selected-sediment-associated-detrital-organic-component'),
    sources: [source('https://www.fao.org/4/i1918e/i1918e.pdf', 'Purcell、Samyn、Conand原作者FAO目录（2012），B.argus pp28–29：活体长度、眼状斑、管足、20短触手和西中太平洋0–30m沙礁底；附术语的沉积摄食定义')] }),
]);
export const OCEAN_REEF_DIVERSITY_IDS = freeze(OCEAN_REEF_DIVERSITY_SPECIES.map(species => species.id));
export const oceanReefDiversitySpeciesById = freeze(Object.fromEntries(OCEAN_REEF_DIVERSITY_SPECIES.map(species => [species.id, species])));
