// A finite v6 palette of genuinely absent body and living-layer types. Full
// display bounds are shared with native assets, not calibrated wild anatomy.
const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) {
  Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, horizontalRadiusUnits) => ({ x, y, z, horizontalRadiusUnits,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'conservative-display-whole-form-and-bounded-animation-not-measured-anatomy' });
const support = (contactKind = null, rootReference = 'total-length-midpoint', footContacts = []) => ({
  mode: contactKind ? 'whole-foot-supported-reef-margin' : 'whole-freewater-body-near-real-reef',
  contactKind: contactKind ?? 'none-freewater', rootReference, footContacts,
  pitchLimitRad: contactKind ? 0 : .10, minimumNormalY: .92,
  wholeBodyDepthRequired: true, terrainClearanceRequired: true });
const food = (pool, component) => ({ owner: pool.split('.')[0], stock: pool.split('.')[1], resourcePath: `region.${pool}`,
  selectedFoodComponent: component, status: 'existing-selected-organic-proxy-not-complete-natural-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false });
const descriptor = data => freeze({ regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带西太平洋浅礁、沙礁缘与潟湖的有限代表组合', coOccurrenceStatus: 'representatives-not-a-local-field-survey',
  ecologicalRateStatus: 'uncalibrated-demonstration', calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  naturalPopulationDensity: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM, status: 'chosen-whole-model-depth-not-complete-natural-range' },
  depthRangeM: data.depthSelectionM,
  limitations: ['程序造型、出生数量、运动和摄食速率未作野外校准；不是完整食物网或种群预测。',
    '仅扣除当地已存在的选定营养代理，不出生食物、不捕杀具体动物，也不代表完整天然食谱。'],
  ...data, sourceLinks: data.sources.map(item => ({ ...item })) });
const lengthForm = form => ({ form, normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5],
  sizeAxis: 'snout-to-farthest-caudal-tip-x',
  clearanceIncludes: ['full-body', 'head', 'mouth', 'eyes', 'all-fins', 'bounded-animation'] });
const skin = [-.26, 0, .26].flatMap(x => [-.10, .10].map(z => ({ x, y: 0, z })));
const sole = [-.30, 0, .30].flatMap(x => [-.10, .10].map(z => ({ x, y: 0, z })));
const tubeTips = [[.20, .30, .37], [.22, .34], [.20, .30, .37], [.22, .34], [.22, .34]]
  .flatMap((radii, i) => radii.map(r => ({ x: r * Math.cos(i * Math.PI * 2 / 5), y: 0, z: r * Math.sin(i * Math.PI * 2 / 5) })));

export const OCEAN_REEF_ASSEMBLAGE_SPECIES = freeze([
  descriptor({ id: 'giant-moray', commonName: '爪哇裸胸鳝（巨海鳗）', scientificName: 'Gymnothorax javanicus', scientificAuthor: '(Bleeker, 1859)',
    synonymScientificNames: ['Muraena javanica'], kind: 'fish', guild: 'long-bodied-near-reef-fish-consumer',
    lengthM: 1.1, sizeRangeM: [.9, 1.3], sizeMeasure: 'total-length', depthSelectionM: [3, 18],
    sizeMeasureDefinition: '中性伸直形态吻端至连续尾鳍末端全长；有界局部体波不重新定义全长或改写记录位置。',
    lifeStageSelection: 'large-spotted-representative; selected-size-not-a-maturity-threshold',
    referenceSizeM: { maximum: 3, measure: 'total-length' }, referenceDepthM: { reportedRange: [0, 50], completeNaturalRange: false },
    colors: ['#796b42', '#373624', '#978968'], normalizedEnvelope: envelope([-.52, .52], [-.105, .105], [-.13, .13], .54),
    support: support(), animationBounds: { bodyWaveUnits: .055, jawPitchRad: .035, gillPulseUnits: .001 },
    morphology: { ...lengthForm('long-thick-tapered-spotted-moray-with-continuous-dorsal-caudal-anal-fin'),
      pectoralFinsPresent: false, pelvicFinsPresent: false, pairedFinCount: 0, medianFinContinuous: true,
      clearanceIncludes: ['whole-flexible-body', 'continuous-dorsal-caudal-anal-fin', 'jaw', 'teeth', 'eyes', 'tubular-nostrils', 'bounded-whole-body-wave'] },
    description: '完整长体逐渐收细、褐底黑斑、黑色鳃孔区、大嘴和管状鼻孔，背尾臀鳍连续；没有胸鳍或腹鳍。',
    diet: '自然主要食鱼；本版只取现有未解析动物营养中的选定鱼类分量，不捕杀可见鱼个体。',
    behavior: '仅表现真实近礁净空内有限游动转场及停留；洞隙栖息尚未实现，不生成假洞或将持续开放水层巡游当作完整生活史。',
    habitat: ['actual-reef-margin', 'bounded-near-reef-freewater-transit'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-fish-animal-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2041', 'Museums Victoria：G.javanicus身份、鱼食、300cm TL及0–50m资料；全文已读'),
      source('https://doris.ffessm.fr/Especes/Gymnothorax-javanicus-Murene-javanaise-1564', 'FFESSM DORIS作者资料：洞隙生境、无胸腹鳍、连续背尾臀鳍及管状鼻孔；全文已读')] }),
  descriptor({ id: 'banded-pipefish', commonName: '环纹海龙（描述性中文名）', scientificName: 'Dunckerocampus dactyliophorus', scientificAuthor: '(Bleeker, 1853)',
    synonymScientificNames: ['Doryrhamphus dactyliophorus', 'Syngnathus dactyliophorus'], kind: 'fish', guild: 'slender-reef-zooplankton-consumer',
    lengthM: .145, sizeRangeM: [.12, .17], sizeMeasure: 'total-length', depthSelectionM: [5, 18],
    sizeMeasureDefinition: '管嘴最前端至扇状尾鳍最远端全长，保持直长体，不按海马卷尾缩短测量。',
    referenceSizeM: { maximum: .18, measure: 'total-length', alternateSourceMaximum: .19 },
    referenceDepthM: { reportedRange: [5, 56], usuallyProtectedReefCavesToM: 10, completeNaturalRange: false },
    colors: ['#e0d2b0', '#433626', '#963f2a'], normalizedEnvelope: envelope([-.52, .52], [-.085, .085], [-.065, .065], .53),
    support: support(), animationBounds: { tailYawRad: .07, pectoralRollRad: .07, dorsalYawRad: .05 },
    morphology: { ...lengthForm('rectangular-armoured-ringed-pipefish-with-long-tube-snout-and-red-white-paddle-tail'),
      longTubularSnout: true, rectangularTrunk: true, caudalSpotCount: 1, pairedPectoralFinsPresent: true },
    description: '长直管嘴、矩形骨环细体、浅暗交替环纹，小背鳍臀鳍和胸鳍完整，红色扇尾带白边与中心白点。',
    diet: '自然食桡足类等小型浮游无脊椎动物；本版选择已有动物库存中的未解析甲壳营养分量，不假称已区分浮游甲壳类。',
    behavior: '受保护礁缘5–18米真实净空内有限游移与停留；不宣称已实现天然成对洞栖、清洁互作或抱卵。',
    habitat: ['protected-coral-reef', 'lagoon-reef-margin'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-small-planktonic-crustacean-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/3178', 'Museums Victoria Bray/Thompson2025：接受属名Dunckerocampus、18cm TL、5–56m及扇尾；全文已读'),
      source('https://doris.ffessm.fr/Especes/Dunckerocampus-dactyliophorus-Syngnathe-zebre-2319', 'FFESSM DORIS作者资料：旧组合、矩形体、桡足类食性及西太平洋保护礁生境；全文已读')] }),
  descriptor({ id: 'spot-fin-porcupinefish', commonName: '斑鳍二齿鲀（黑斑刺鲀）', scientificName: 'Diodon hystrix', scientificAuthor: 'Linnaeus, 1758',
    kind: 'fish', guild: 'spined-reef-benthic-animal-consumer', lengthM: .375, sizeRangeM: [.30, .45], sizeMeasure: 'total-length', depthSelectionM: [3, 18],
    sizeMeasureDefinition: '正常未充气吻端至尾鳍末端全长，长棘另纳入空间包络，不将充气直径作为体长。',
    lifeStageSelection: 'ordinary-uninflated-form', referenceSizeM: { maximum: .71, measure: 'total-length' },
    referenceDepthM: { reportedRange: [1, 50], completeNaturalRange: false },
    colors: ['#a59d76', '#d0c8a5', '#474530'], normalizedEnvelope: envelope([-.54, .54], [-.25, .27], [-.235, .235], .60),
    support: support(), animationBounds: { tailYawRad: .07, pectoralRollRad: .07, dorsalYawRad: .05 },
    morphology: { ...lengthForm('normal-uninflated-long-spined-porcupinefish-with-spotted-body-and-spotted-fins'),
      inflationImplemented: false, pelvicFinsPresent: false,
      clearanceIncludes: ['uninflated-body', 'head', 'mouth', 'eyes', 'laid-long-spines', 'all-present-fins', 'bounded-fin-motion'] },
    description: '未充气的厚长体、浅橄榄灰体色、全体和鳍上的黑小斑、向后卧伏的长棘与大眼；不是长期膨胀的球。',
    diet: '自然摄食海胆、腹足类和蟹；本版只扣除现有未解析底栖动物营养，不碎壳、刺伤或捕杀具体动物。',
    behavior: '真实沙礁缘水层有限移动，整套长棘和鳍保持净空；真实洞隙休息与防御充气均未实现。',
    habitat: ['coral-reef-margin', 'rocky-reef-margin'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-urchin-gastropod-crab-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/476', 'Museums Victoria：D.hystrix身份、全体和鳍黑斑、长可立棘、海胆螺蟹食及71cm TL/1–50m；全文已读')] }),
  descriptor({ id: 'peacock-flounder', commonName: '豹纹鲆（孔雀鲽，描述性中文名）', scientificName: 'Bothus mancus', scientificAuthor: '(Broussonet, 1782)',
    synonymScientificNames: ['Pleuronectes mancus', 'Platophrys mancus', 'Rhombus macropterus', 'Pleuronectes barffi'],
    kind: 'fish', guild: 'blind-side-supported-sand-animal-consumer', lengthM: .27, sizeRangeM: [.22, .32], sizeMeasure: 'total-length', depthSelectionM: [3, 18],
    sizeMeasureDefinition: '吻端至尾鳍末端全长；左侧眼面朝上、右盲侧皮肤朝底，以真实皮肤接触采样支撑而非虚构脚。',
    lifeStageSelection: 'ordinary-form-without-male-long-pectoral-filaments; no-age-or-sex-inference',
    referenceSizeM: { maximum: .51, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 150], completeNaturalRange: false },
    colors: ['#9c987a', '#648a93', '#d3ceb3'], normalizedEnvelope: envelope([-.54, .54], [0, .18], [-.38, .38], .67),
    support: support('blind-right-side-skin-samples', 'blind-right-side-contact-plane', skin), animationBounds: { contactSamplesStationary: true, medianFinLiftUnits: .005 },
    morphology: { ...lengthForm('elliptical-left-eyed-flatfish-with-pale-blind-right-skin-and-blue-atoll-spots'),
      leftEyedFaceUp: true, actualContactPlaneY: 0, supportSamplesAreFeet: false, blindSkinSampleCount: 6 },
    description: '扁椭圆完整鱼体、两眼均在左上面、前头凹轮廓和口上凸起，蓝环斑与侧线暗斑，浅色右盲侧实际贴底。',
    diet: '自然摄食底栖无脊椎和小鱼，主要夜猎；本版只扣已有动物营养分量，不宣称模拟全天然夜猎节律。',
    behavior: '实际裸沙面的有限贴底移动与停留摄食，完整鳍尾净空与盲侧接触保持；不假埋沙或给鱼添加步足。',
    substrate: ['real-soft-sand'], habitat: ['reef-associated-bare-sand'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-invertebrate-and-small-fish-nutrition-component'),
    sources: [source('https://doris.ffessm.fr/Especes/Bothus-mancus-Rombou-tropical-5440', 'FFESSM DORIS作者资料：Bothus身份与旧组合、左眼/白盲侧、51cm/1–150m沙底及食性；全文已读')] }),
  descriptor({ id: 'textile-cone', commonName: '织锦芋螺', scientificName: 'Conus textile', scientificAuthor: 'Linnaeus, 1758',
    synonymScientificNames: ['Conus concatenatus', 'Conus scriptus', 'Conus cholmondeleyi', 'Conus sirventi'],
    kind: 'mollusc', guild: 'sand-margin-mollusc-consumer', lengthM: .065, sizeRangeM: [.055, .075], sizeMeasure: 'shell-length', depthSelectionM: [3, 18],
    sizeMeasureDefinition: '壳尖至前壳口的壳长；柔软头足、水管和收缩口吻另计完整包络，不误称为身体全长。',
    referenceSizeM: { usualRange: [.05, .08], maximum: .15, measure: 'shell-length' },
    referenceDepthM: { approximateMaximum: 50, completeNaturalRange: false },
    colors: ['#bf8a43', '#d5c7a7', '#675b3a'], normalizedEnvelope: envelope([-.54, 1.06], [0, .62], [-.35, .35], 1.12),
    support: support('continuous-muscular-sole-samples', 'neutral-sole-contact-plane', sole), animationBounds: { contactSamplesStationary: true, siphonYawRad: .02 },
    morphology: { form: 'pointed-spire-ovate-cone-shell-with-white-triangle-network-and-continuous-muscular-sole',
      normalizedMeasuredSize: 1, shellMeasuredX: [-.5, .5], sizeAxis: 'posterior-shell-apex-to-anterior-aperture-x',
      continuousMuscularSole: true, respiratorySiphonSeparateFromProboscis: true, proboscisSelection: 'short-retracted-no-prey-strike',
      clearanceIncludes: ['whole-shell', 'muscular-sole', 'head', 'tentacles', 'respiratory-siphon', 'short-retracted-proboscis', 'bounded-animation'] },
    description: '尖螺塔与圆肩锥壳、黄褐底白三角织纹、长前壳口、真实连续腹足，呼吸水管与短收缩口吻分开。',
    diet: '本种天然严格食软体动物，不能用芋螺属中其他种的鱼食或虫食替代；本版只选未解析软体动物营养，不执行射毒齿捕杀。',
    behavior: '实际沙礁缘有限慢移，全壳、足和水管保持净空；不模拟埋沙、假洞或两倍壳长的伸展捕食。',
    substrate: ['real-soft-sand'], habitat: ['reef-associated-sand-margin'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-molluscan-animal-nutrition-component'),
    sources: [source('https://doris.ffessm.fr/Especes/Conus-textile-Cone-drap-d-or-1184', 'FFESSM DORIS作者资料：C.textile身份、50–80mm常见壳长、约50m沙礁缘及严格软体动物食性；全文已读')] }),
  descriptor({ id: 'collector-urchin', commonName: '白棘三列海胆（集物海胆，描述性中文名）', scientificName: 'Tripneustes gratilla', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'echinoderm', guild: 'short-spined-algal-reef-grazer', lengthM: .075, sizeRangeM: [.065, .085], sizeMeasure: 'test-diameter-excluding-spines', depthSelectionM: [3, 15],
    sizeMeasureDefinition: '硬壳test横径，不含短棘或伸出管足；完整棘、管足和软附器另纳入包络。',
    lifeStageSelection: 'tropical-T.gratilla-form; no-mixed-subtropical-kermadecensis',
    referenceSizeM: { reportedMaximumDiameter: .16, measure: 'diameter-source-does-not-separate-spines',
      selectedStudyTestDiameterRange: [.065, .085] }, referenceDepthM: { reportedRange: [0, 75], moreAbundantAboveM: 15, completeNaturalRange: false },
    colors: ['#726244', '#c0b18b', '#a55937'], normalizedEnvelope: envelope([-.72, .72], [0, 1.03], [-.72, .72], 1.02),
    support: support('ambulacral-tube-foot-tips', 'neutral-tube-foot-contact-plane', tubeTips), animationBounds: { contactSamplesStationary: true, spineSwayRad: .02 },
    morphology: { form: 'globular-short-spined-collector-urchin-with-ten-spine-bands-and-five-tube-foot-sectors',
      normalizedMeasuredSize: 1, testMeasuredX: [-.5, .5], testMeasuredZ: [-.5, .5], sizeAxis: 'test-diameter-excluding-spines-x-z',
      actualTubeFootTipCount: 12, collectedSceneryImplemented: false, mouthIsSupportPoint: false, spinesAreSupportPoints: false,
      clearanceIncludes: ['whole-test', 'all-short-spines', 'real-tube-feet', 'pedicellariae', 'bounded-animation'] },
    description: '圆拱硬壳、十列短棘带与间隔步带、真实管足和短软附器，区别于已有长刺Diadema；不把中央口或棘尖当脚。',
    diet: '自然摄食宏藻与海草；本版只使用既有algae选定分量，不宣称逐株草食或已完成集物遮盖行为。',
    behavior: '真实稳定裸露硬质藻礁缘有限慢移，十二个真实管足尖采样支撑；不凭物种名称携带场景垃圾。',
    substrate: ['real-stable-hard-algal-reef-surface'], habitat: ['lagoon-algal-reef-margin'], foodPool: 'resources.algae',
    feedingProxy: food('resources.algae', 'selected-macroalgal-nutrition-component-of-unresolved-algae'),
    sources: [source('https://doris.ffessm.fr/Especes/Tripneustes-gratilla-Oursin-bonnet-de-pretre-3045', 'FFESSM DORIS作者资料：热带T.gratilla短棘步带、0–75m及主要浅15m、宏藻和海草食性；全文已读'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC4830529/', '原研究Tripneustes gratilla选取6.5–8.5cm test diameter；作为本版展示选择而非野外体型分布')] }),
]);
export const OCEAN_REEF_ASSEMBLAGE_IDS = freeze(OCEAN_REEF_ASSEMBLAGE_SPECIES.map(s => s.id));
export const oceanReefAssemblageSpeciesById = freeze(Object.fromEntries(OCEAN_REEF_ASSEMBLAGE_SPECIES.map(s => [s.id, s])));
