// A finite tropical Indo-Pacific reef-water package. Chosen size, admission
// depth, school size, geometry and ecological rates are display selections.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = shark => ({
  x: [-.55, .55], y: shark ? [-.20, .35] : [-.25, .25],
  z: shark ? [-.40, .40] : [-.25, .25],
  horizontalRadiusUnits: shark ? .69 : .61,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-conservative-whole-form-and-bounded-fin-motion-clearance',
});
const proxy = animal => ({
  owner: animal ? 'openWaterLife' : 'livingNetwork',
  stock: animal ? 'preyOrganicUnits' : 'plankton',
  resourcePath: animal ? 'region.openWaterLife.preyOrganicUnits' : 'region.resources.plankton',
  selectedDietComponent: animal ? 'unresolved-swimming-animal-organic-nutrition' : 'unresolved-plankton-organic-nutrition',
  status: 'selected-natural-diet-component-in-existing-relative-stock-not-complete-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false,
});
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带印度—西太平洋的浅礁水层有限代表组合',
  coOccurrenceStatus: 'regional-representatives-not-a-single-field-survey-reconstruction',
  individualStatus: 'independent-simulated-individual-with-own-organic-stock-and-clock-not-a-render-clone',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  calibratedPopulationRates: null, populationDensityPerM2: null, naturalSchoolSize: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  calibratedCurrentMPerS: null, calibratedAgeSec: null,
  temperatureRangeC: null, salinityRangePSU: null, oxygenRangeMgPerL: null,
  environmentToleranceStatus: 'unknown-not-a-species-tolerance-calibration',
  sizeMeasure: 'total-length',
  sizeMeasureDefinition: '吻端至尾鳍最远端的完整全长TL；不使用尾叉长FL或吻端至尾鳍基部的标准体长SL作换算。',
  displaySizeM: { range: data.sizeRangeM, measure: 'total-length', status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM,
    status: 'chosen-whole-individual-water-depth-not-seabed-depth-or-complete-species-range' },
  support: { mode: 'whole-freewater-body-above-native-reef', rootReference: 'total-length-midpoint',
    wholeBodyDepthRequired: true, terrainClearanceRequired: true, pitchClearanceRequired: true },
  foodProxyStatus: 'selected-diet-component-in-existing-relative-stock-not-complete-natural-diet',
  renderEmissionEnabled: false,
  limitations: [
    '原生水层中逐个检查全身含尾鳍、胸鳍与有界动作；床深不直接代表游动物的水深，不改地形保证出现。',
    '同种鱼群由独立模拟个体构成；5–7条等展示数量不是自然密度、完整大群或当地普查结果。',
    '程序比例、运动与生态速率未校准；温度、盐度、溶氧、流速、年龄未知项保留null。',
    '消费已有浮游库存或未分辨游泳动物营养代理；未实现捕杀可见动物、完整食物网或物种分辨食物密度。',
  ],
  ...data,
  sourceLinks: data.sources.map(item => item.url),
});

export const oceanShoalLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'blue-and-gold-fusilier', commonName: '黄蓝背乌尾鮗',
    scientificName: 'Caesio teres', scientificAuthor: 'Seale, 1906', family: 'Caesionidae',
    kind: 'fish', modelRole: 'fusilier', guild: 'water-column-planktivore',
    lengthM: .26, sizeRangeM: [.22, .30], depthSelectionM: [5, 15],
    taxonomicNote: '使用C. teres命名形态；与已有Caesio cuning为不同物种，但不宣称新增了独立食物网功能。',
    referenceSizeM: { maximum: .40, measure: 'total-length',
      note: 'Museums Victoria/Fishes of Australia的40cm TL账户；22–30cm为展示选择。' },
    referenceDepthM: { reportedRange: [5, 50],
      note: 'Fishes of Australia报道5–50米；本版仅选择完整身体位于5–15米的水层。' },
    normalizedEnvelope: envelope(false), colors: ['#3d90b1', '#d8ca52', '#cadcdb'],
    description: '较高的纺锤形鱼体，蓝背银白腹，后上背、后段背鳍及深叉尾为黄色；天然种群颜色可变。',
    diet: '自然在礁上中层成群摄食浮游生物；本版选择现有plankton营养代理，不宣称复原全部自然食物。',
    feedingProxy: proxy(false),
    schooling: { naturalBehavior: 'large-schools-in-midwater-above-reef', enabled: true,
      naturalCount: null, displayGroupSizeStatus: 'finite-individual-demonstration-not-field-density' },
    behavior: '独立个体在礁上水层趋同、分离和转向；群体大小与动作是展示参数，不是实测野外轨迹。',
    habitat: ['coral-reef-water-column', 'midwater-above-reef'],
    morphology: { form: 'moderately-deep-fusiform-fusilier-with-deeply-forked-yellow-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5],
      clearanceIncludes: ['head', 'body', 'dorsal-fin', 'anal-fin', 'paired-fins', 'forked-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://fishesofaustralia.net.au/Home/species/1233',
        location: 'labelled live Caesio teres photo, Queensland/Great Barrier Reef; Graham Edgar/Reef Life Survey' } },
    sources: [
      source('https://fishesofaustralia.net.au/Home/species/1233', 'Museums Victoria/Fishes of Australia：C. teres完整活体形态、40cm TL、5–50米、印太分布与礁上群游食浮游生物'),
      source('https://churaumi.okinawa/sp/sc/fishbook/1489653956/', '冲绳美丽海水族馆官方中文图鉴：黄蓝背乌尾鮗学名、颜色与浮游食物分量'),
    ],
  }),
  descriptor({
    id: 'bigeye-trevally', commonName: '六带鲹',
    scientificName: 'Caranx sexfasciatus', scientificAuthor: 'Quoy & Gaimard, 1825', family: 'Carangidae',
    kind: 'fish', modelRole: 'trevally', guild: 'water-column-animal-predator',
    lengthM: .45, sizeRangeM: [.35, .55], depthSelectionM: [3, 15],
    taxonomicNote: '中文采用台湾鱼类资料库六带鲹；英文Bigeye Trevally与ID保留。六道条纹不是所有成体的固定外观。',
    referenceSizeM: { maximum: .80, measure: 'total-length',
      separateReportedForkLengthMaximum: .78, separateReportedForkLengthCommon: .60,
      note: 'TL采用日本国立科学博物馆Lombok原创指南80cm全长；Museums Victoria的78cm/60cm明确为FL，单列保留，未换算。' },
    referenceDepthM: { reportedRange: [0, 100],
      note: '台湾鱼类资料库0–100米，Museums Victoria成体珊瑚礁至约100米；本版选择3–15米，未借幼体河口生境扩展成体配置。' },
    normalizedEnvelope: envelope(false), colors: ['#8aa6a5', '#d4dcda', '#425d60'],
    description: '压扁的长椭圆体、大眼、两段背鳍、长镰状胸鳍和深叉尾；银灰腹、暗背，小鳃盖黑点和背臀鳍叶白端。',
    diet: '自然食鱼、头足类及甲壳动物；本版仅取已有未分辨游泳动物有机库存的选定动物营养分量，不逐个捕杀可见鱼群。',
    feedingProxy: proxy(true),
    schooling: { naturalBehavior: 'large-slow-moving-daytime-schools', enabled: true,
      naturalCount: null, displayGroupSizeStatus: 'finite-independent-individuals-not-a-natural-large-school' },
    activity: { naturalFeedingEvidence: 'night-or-twilight-activity-in-Museums-Victoria-account',
      enforcedNaturalSchedule: false, scheduleStatus: 'no-calibrated-hour-gate-or-claimed-local-night-school-pattern' },
    behavior: '有限同种群游个体相互靠近并保持距离；自然昼间群游有依据，夜间活动和分群未校准为固定小时规则。',
    habitat: ['coral-reef-water-column', 'seaward-reef', 'rocky-reef-edge'],
    morphology: { form: 'compressed-elongate-oval-bigeye-jack-with-long-pectoral-and-deep-fork',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5],
      adultSixBarsRequired: false,
      clearanceIncludes: ['head', 'body', 'two-dorsal-fins', 'anal-fin', 'paired-fins', 'long-pectoral-fins', 'forked-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://www.kahaku.go.jp/research/db/zoology/FishGuide/data/fish207.html',
        location: 'labelled complete C. sexfasciatus specimen and adult/juvenile diagnostic account; pictured specimen has separate13.2cm SL label' },
      wholeSchoolReference: 'https://lifg.australian.museum/HotShot.html?resourceId=CMhpffGR' },
    sources: [
      source('https://www.kahaku.go.jp/research/db/zoology/FishGuide/data/fish207.html', '日本国立科学博物馆原创Lombok鱼类指南：明确80cm TL、完整形态、成幼颜色区别与礁生境'),
      source('https://fishesofaustralia.net.au/home/species/1654', 'Museums Victoria：昼间慢速大群、成体礁生境与鱼/头足/甲壳食性；78cm FL未标作TL'),
      source('https://fishdb.sinica.edu.tw/chi/species.php?gen=Caranx&spe=sexfasciatus', '中央研究院台湾鱼类资料库：六带鲹学名、印太区域与0–100米；未采用未注明口径的120cm最大体长'),
      source('https://lifg.australian.museum/HotShot.html?resourceId=CMhpffGR', '澳大利亚博物馆Lizard Island现场命名鱼群参考：Cobia Hole的C. sexfasciatus'),
    ],
  }),
  descriptor({
    id: 'silver-stripe-herring', commonName: '日本银带鲱',
    scientificName: 'Spratelloides gracilis', scientificAuthor: '(Temminck & Schlegel, 1846)', family: 'Spratelloididae',
    kind: 'fish', modelRole: 'herring', guild: 'water-column-planktivore',
    lengthM: .0675, sizeRangeM: [.06, .075], depthSelectionM: [1, 3],
    taxonomicNote: '中文采用台湾水产试验所；当前科使用Spratelloididae。历史FAO与Smithsonian记录仍可用Clupeidae，不据旧科名改称另一物种。',
    referenceSizeM: { examinedTotalLengthRange: [.0463, .077], measure: 'total-length',
      examinedTotalLengthUpperApproximate: true, separateGuideStandardLengthMaximum: .095,
      note: 'Whitehead等1966原始模式材料复核记录46.3至约77mm全长；6–7.5cm为其中有限TL选择。FAO1985的9.5cm为SL，未转换成TL或当作本版10cm依据。' },
    referenceDepthM: { specimenCollectionRange: [0, 3],
      specimenCollectionRegion: 'Balugan-Bay-Batan-Island-Batanes-Philippines', specimenCollectionDate: '1987-04-23',
      completeNaturalRange: null,
      note: 'Smithsonian菲律宾原始标本记录0–3米；选择全身体位于1–3米，不宣称该单标本是活体鱼群密度或完整分布水深。' },
    normalizedEnvelope: envelope(false), colors: ['#769b9e', '#d3e3df', '#f0f2e5'],
    description: '小型细长近圆柱鱼体、背部微蓝、连续明亮侧银带，完整尾柄接透明深叉尾；与深体鲹分开。',
    diet: '水试所自然食物列矽藻、橈足类及其他小无脊椎浮游生物；本版只取现有plankton营养代理，未分辨每类食物密度。',
    feedingProxy: proxy(false),
    schooling: { naturalBehavior: 'inshore-lagoon-and-seaward-reef-schooling', enabled: true,
      naturalCount: null, displayGroupSizeStatus: 'small-finite-independent-sample-not-a-natural-dense-baitball' },
    behavior: '在原生海面下1–3米的实际水层群游；所有尾尖和有界鳍动作须保留水面与地形净空，不按海床深度生成。',
    habitat: ['shallow-coastal-water-column', 'lagoon-water-column', 'seaward-reef-water-column'],
    morphology: { form: 'slender-round-herring-with-continuous-silver-lateral-stripe-and-forked-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5],
      clearanceIncludes: ['head', 'slender-body', 'dorsal-fin', 'anal-fin', 'paired-fins', 'caudal-peduncle', 'forked-tail', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://www.museum.kagoshima-u.ac.jp/ichthy/INHFJ_2020_003_010.pdf',
        location: 'Hata and Motomura2020 Fig.1, labelled whole fresh S.gracilis NSMT-P136295;71.2mm SL is a separate specimen scale, not our TL' },
      wholeSchoolReference: 'https://fishesofaustralia.net.au/home/species/2069' },
    sources: [
      source('https://repository.naturalis.nl/pub/317728/ZV1966084001.pdf', 'Whitehead、Boeseman、Wheeler1966原创模式材料复核：Clupea argyrotaeniata归S.gracilis、46.3至约77mm全长；非SL→TL换算'),
      source('https://www.fao.org/4/ac482e/ac482e09.pdf', 'Whitehead1985原作者FAO账户：银带完整形态、近岸群游与印太分布；9.5cm是标准体长SL'),
      source('https://www.si.edu/es/object/spratelloides-gracilis%3Anmnhvz_5182417', 'Smithsonian菲律宾1987原始采集标本：Batan岛0–3米；不是活体鱼群普查'),
      source('https://www.tfrin.gov.tw/theme_data.php?id=1322&sub_theme=special_message&theme=book_data', '台湾农业部水产试验所2023原作者研究介绍：日本银带鲱、群游、泻湖与面海礁区及浮游食物'),
      source('https://www.museum.kagoshima-u.ac.jp/ichthy/INHFJ_2020_003_010.pdf', 'Hata和Motomura2020原始科级分类研究：当前Spratelloididae与带比例标签的完整鲜鱼照片'),
      source('https://fishesofaustralia.net.au/home/species/2069', 'Museums Victoria/澳大利亚博物馆Lizard Island命名浅礁银带鱼群形态参考'),
    ],
  }),
  descriptor({
    id: 'blacktip-reef-shark', commonName: '黑鳍礁鲨',
    scientificName: 'Carcharhinus melanopterus', scientificAuthor: '(Quoy & Gaimard, 1824)', family: 'Carcharhinidae',
    kind: 'shark', modelRole: 'shark', guild: 'water-column-animal-predator',
    lengthM: 1, sizeRangeM: [.8, 1.2], depthSelectionM: [3, 15],
    taxonomicNote: '完整形态选黑鳍礁鲨C.melanopterus，不把长尖吻的C.limbatus或既有温带豹纹鲨更名。',
    referenceSizeM: { maximumAtLeast: 1.80, measure: 'total-length',
      note: 'FRDC2023种账户明确至少180cm TL；80–120cm是展示选择，不宣称全是成熟个体、年龄或自然常见长度分布。' },
    referenceDepthM: { reportedRange: [0, 75], usualAboveDepth: 40,
      note: 'Museums Victoria0–75米且通常浅于40米；FAO记录礁浅水及更深水的近底/中层游动。选择完整身体位于3–15米，未模拟30cm潮间带。' },
    normalizedEnvelope: envelope(true), colors: ['#929985', '#d5d9c9', '#252e2c'],
    description: '短钝吻、五对鳃裂、胸鳍与腹鳍、明显第一背鳍、较小第二背鳍及臀鳍；异型尾上叶较长，第一背尖与下尾叶有黑斑及近端白界。',
    diet: '自然食小鱼和多类无脊椎动物；本版选择已有未分辨游泳动物营养代理，不实现追杀可见鱼、实际鲨鱼能量需求或完整食物网。',
    feedingProxy: proxy(true),
    schooling: { naturalBehavior: 'single-or-small-groups-not-strongly-schooling', enabled: false,
      naturalCount: null, displayGroupSizeStatus: 'optional-single-independent-cruiser-not-an-enforced-shark-school' },
    behavior: '在真实礁上净空水层单体持续游弋，可绕开邻近个体和地形；不宣称自然驻留范围、繁殖、洄游或气味追踪已经复原。',
    habitat: ['shallow-coral-reef', 'reef-dropoff', 'reef-midwater'],
    morphology: { form: 'blunt-snouted-reef-shark-with-two-dorsals-five-gill-slits-and-heterocercal-tail',
      sizeAxis: 'snout-to-farthest-caudal-tip-x', normalizedMeasuredSize: 1,
      rootReference: 'total-length-midpoint', neutralMeasuredX: [-.5, .5], gillSlitsPerSide: 5,
      clearanceIncludes: ['head', 'body', 'first-dorsal', 'second-dorsal', 'anal-fin', 'pectoral-fins', 'pelvic-fins', 'upper-and-lower-caudal-lobes', 'bounded-fin-motion'],
      wholeFormReference: { url: 'https://www.fao.org/4/ad123e/ad123e28.pdf',
        location: 'Compagno1984 printedpp488–489 C.melanopterus complete body illustration and species account; preceding page is another taxon' },
      wholeLiveReference: 'https://australian.museum/learn/animals/fishes/blacktip-reef-shark-carcharhinus-melanopterus-quoy-gaimard-1824/' },
    sources: [
      source('https://www.fao.org/4/ad123e/ad123e28.pdf', 'Compagno1984原作者FAOpp488–489：完整短钝吻礁鲨、非强群游、浅礁/更深中层生境及食鱼/无脊椎动物'),
      source('https://fish.gov.au/docs/SharkReport/2023_FRDC_Carcharhinus_melanopterus_final.pdf', 'FRDC2023官方种报告：热带礁与海岸生境及明确至少180cm全长TL'),
      source('https://fishesofaustralia.net.au/home/species/1952', 'Museums Victoria：印太命名完整活体、0–75米且通常浅于40米、黑白鳍尖区别'),
      source('https://australian.museum/learn/animals/fishes/blacktip-reef-shark-carcharhinus-melanopterus-quoy-gaimard-1824/', '澳大利亚博物馆：Fiji命名完整活体、自然浅礁与热带印太分布'),
    ],
  }),
]);

export const oceanShoalLifeSpeciesById = freeze(Object.fromEntries(
  oceanShoalLifeSpeciesCatalog.map(species => [species.id, species]),
));
