const freeze = v => { if (v && typeof v === 'object') { Object.values(v).forEach(freeze); Object.freeze(v); } return v; };
const source = (url, label) => ({ url, label });
function representative(d) {
  return freeze({ regionalOnly: true, referenceRegion: '热带印度—西太平洋浅礁',
    coOccurrenceStatus: 'representatives-not-a-local-field-survey', foodPool: 'resources.plankton',
    depthRangeM: d.depthSelectionM, displaySizeM: { range: d.sizeRangeM, measure: d.sizeMeasure, status: 'illustrative-selection' },
    admissionDepthM: { range: d.depthSelectionM, status: 'selected-whole-model-depth-not-complete-natural-range' },
    ecologicalRateStatus: 'uncalibrated-demonstration', naturalPopulationDensity: null, calibratedMovementMPerS: null,
    calibratedEcologicalRates: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
    feedingProxy: { owner: 'resources', stock: 'plankton', resourcePath: 'region.resources.plankton',
      selectedFoodComponent: 'unresolved-suspended-plankton-nutrition', status: 'existing-local-nutrition-proxy-not-calibrated-filtration',
      visiblePreyKillImplemented: false, speciesResolvedFoodStock: false },
    limitations: ['数量、滤水量、粒径选择和呼吸速率未野外标定。', '未模拟繁殖、共生虾、脱附力学或完整天然食谱。'],
    ...d, sourceLinks: d.sources.map(s => ({ ...s })) });
}
export const OCEAN_REEF_SUSPENSION_SPECIES = freeze([
  representative({ id: 'shallow-feather-star', commonName: '浅海羽星（类群代表）', scientificName: 'Comatulida spp.',
    identityLevel: 'order-morphological-representative', taxonomicLevel: 'order', scientificAuthor: null,
    kind: 'crinoid', guild: 'perched-suspension-feeder', sizeMeasure: 'expanded-fan-diameter', lengthM: .30,
    sizeRangeM: [.24, .36], depthSelectionM: [5, 25], habitat: ['stable-hard-reef-perch'],
    referenceSizeM: { maximum: null, scope: 'no order-wide measured maximum; fan diameter chosen' },
    referenceDepthM: { reportedRange: null, completeNaturalRange: false, scope: 'shallow tropical hard-substrate representative, not all Comatulida' },
    support: { mode: 'whole-perched-crinoid-on-real-hard-surface', contactKind: 'six-basal-cirrus-support-samples-not-walking-feet',
      footContacts: [-.07, 0, .07].flatMap(x => [-.02, .02].map(z => ({ x, y: 0, z }))),
      rootReference: 'basal-cirrus-contact-plane', pitchLimitRad: .04, minimumNormalY: .92,
      wholeBodyDepthRequired: true, terrainClearanceRequired: true },
    normalizedEnvelope: { x: [-.55, .55], y: [0, .62], z: [-.55, .55], horizontalRadiusUnits: .78,
      axes: 'expanded-feeding-fan-in-xz; up-positive-y', status: 'conservative-whole-arms-pinnules-cirri-and-bounded-fan-motion' },
    morphology: { form: 'central-disc-forty-branched-arms-paired-pinnules-and-basal-cirri', normalizedMeasuredSize: 1,
      sizeAxis: 'expanded-fan-diameter-xz', clearanceIncludes: ['central-disc', 'arms', 'pinnules', 'cirri', 'bounded-arm-motion'] },
    animationBounds: { armYawRad: .025, armVerticalScaleFraction: .018 }, colors: ['#bda04d', '#5f492e'],
    description: '无成体长柄，中央体盘向上展开带羽枝的腕，底部卷枝接触礁面；展示停栖阶段。',
    behavior: '随所属生态时钟展臂和有界摆动，实际扣当地浮游营养；羽星能移栖，本版未实现爬移或游泳。',
    adultPermanentlySessile: false, locomotionImplemented: false, observedPhase: 'perched-feeding-only',
    sources: [source('https://lkcnhm.nus.edu.sg/app/uploads/2017/04/63rbz438-445.pdf', 'Mekhova与Britayev 2015：成体无柄、浅海羽星的硬底/软底差异及岩石等宿主'),
      source('https://museum.wa.gov.au/explore/marine-life-dampier-archipelago/explore-marine-life/echinoderms', '西澳博物馆：卷枝停栖、腕与羽枝摄食、成体可移动')] }),
  representative({ id: 'gold-mouth-sea-squirt', commonName: '金口海鞘（描述性中文名）', scientificName: 'Polycarpa aurata',
    identityLevel: 'species-representative', taxonomicLevel: 'species', scientificAuthor: '(Quoy & Gaimard, 1834)',
    kind: 'ascidian', guild: 'attached-benthic-suspension-feeder', sizeMeasure: 'body-height', lengthM: .08,
    sizeRangeM: [.065, .095], depthSelectionM: [5, 20], habitat: ['shallow-reef-hard-attachment'],
    referenceSizeM: { maximum: null, scope: 'display height selected; not claiming a global maximum' },
    referenceDepthM: { reportedRange: [5, 20], completeNaturalRange: false, scope: '2015 Kimbe Bay study sampling transects, not full natural range' },
    support: { mode: 'whole-attached-ascidian-on-real-hard-surface', contactKind: 'six-basal-body-support-samples-not-anatomical-feet',
      footContacts: [-.15, 0, .15].flatMap(x => [-.08, .08].map(z => ({ x, y: 0, z }))),
      rootReference: 'basal-body-contact-plane', pitchLimitRad: .04, minimumNormalY: .92,
      wholeBodyDepthRequired: true, terrainClearanceRequired: true },
    normalizedEnvelope: { x: [-.43, .43], y: [0, 1.08], z: [-.35, .35], horizontalRadiusUnits: .56,
      axes: 'body-height-positive-y; transverse-xz', status: 'conservative-whole-tunic-two-siphons-and-bounded-aperture-motion' },
    morphology: { form: 'leathery-urn-shaped-tunic-with-distinct-oral-and-atrial-siphons', normalizedMeasuredSize: 1,
      sizeAxis: 'body-height-y', clearanceIncludes: ['tunic', 'oral-siphon', 'atrial-siphon', 'bounded-siphon-motion'] },
    animationBounds: { apertureScaleFraction: .06 }, colors: ['#cbbfaa', '#666077', '#c0a044'],
    description: '具皮革状外被和两个分离的水管，顶部入水、侧部出水；水管口呈暖黄色。',
    behavior: '固定于真实稳定礁面，双水管随生态时钟有界收缩，实际扣当地浮游营养；不凭空制造喷水或食物。',
    sources: [source('https://pmc.ncbi.nlm.nih.gov/articles/PMC4370848/', 'Baeza等2015原始研究：金口海鞘礁栖与巴布亚新几内亚5–20米采样'),
      source('https://www.int-res.com/articles/esr2025/57/n057p431.pdf', 'Wainwright等2025原始研究：金口海鞘入水管及滤食，真实滤水量尚不明确'),
      source('https://museum-publications.australian.museum/media/dd/documents/Recno49565_Herdman_1899_lowres.91157d9.pdf', '澳大利亚博物馆Tunicata目录：Polycarpa aurata外被、附着、两水管（含历史变型）')] })
]);
export const OCEAN_REEF_SUSPENSION_IDS = freeze(OCEAN_REEF_SUSPENSION_SPECIES.map(s => s.id));
export const oceanReefSuspensionSpeciesById = freeze(Object.fromEntries(OCEAN_REEF_SUSPENSION_SPECIES.map(s => [s.id, s])));
