// Six additional v3 representatives. Selection sizes, rates and complete
// display envelopes are explicit implementation choices, not field calibration.
const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) {
  Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, horizontalRadiusUnits) => ({ x, y, z, horizontalRadiusUnits,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'conservative-display-whole-form-and-bounded-animation-not-measured-anatomy' });
const support = (bottom = false, footContacts = []) => ({ mode: bottom ? 'whole-foot-supported-reef-margin' : 'whole-freewater-body-near-real-reef',
  rootReference: bottom ? 'neutral-foot-plane' : 'total-length-midpoint', pitchLimitRad: bottom ? 0 : .10,
  minimumNormalY: .92, footContacts, wholeBodyDepthRequired: true, terrainClearanceRequired: true });
const food = (pool, component) => ({ owner: pool.split('.')[0], stock: pool.split('.')[1], resourcePath: `region.${pool}`,
  selectedFoodComponent: component, status: 'existing-selected-organic-proxy-not-complete-natural-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false });
const descriptor = data => freeze({ regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带西太平洋浅珊瑚礁的有限代表组合', coOccurrenceStatus: 'representatives-not-a-local-field-survey',
  ecologicalRateStatus: 'uncalibrated-demonstration', calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  naturalPopulationDensity: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: [3, 18], status: 'chosen-whole-model-depth-not-complete-natural-range' },
  depthSelectionM: [3, 18], depthRangeM: [3, 18],
  limitations: ['程序造型、出生数量、运动及摄食速率未作野外校准；不是完整食物网或种群预测。',
    '只消费当地已存在的选定有机营养代理，不生成食物、不捕杀具体可见动物，也不代表完整自然食谱。'],
  ...data, sourceLinks: data.sources.map(item => ({ ...item })) });
const fishForm = form => ({ form, normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5], sizeAxis: 'snout-to-farthest-caudal-tip-x',
  clearanceIncludes: ['body', 'mouth', 'eyes', 'complete-caudal-fin', 'all-other-fins', 'bounded-fin-motion'] });
const mantisFeet = [.04, -.07, -.18].flatMap(x => [-.22, .22].map(z => ({ x, y: 0, z })));
const snailFeet = [-.38, 0, .38].flatMap(x => [-.15, .15].map(z => ({ x, y: 0, z })));

export const OCEAN_REEF_COMMUNITY_SPECIES = freeze([
  descriptor({ id: 'yellow-boxfish', commonName: '黄色箱鲀（描述性中文名）', scientificName: 'Ostracion cubicus', scientificAuthor: 'Linnaeus, 1758',
    kind: 'fish', guild: 'reef-benthic-omnivore', lengthM: .18, sizeRangeM: [.14, .22], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至尾鳍末端全长；不把硬甲箱形体单独长度当作全长。',
    referenceSizeM: { maximum: .45, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 50], completeNaturalRange: false },
    colors: ['#c6b64c', '#807b4b', '#353c2c'], normalizedEnvelope: envelope([-.54, .54], [-.28, .28], [-.25, .25], .60),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06 }, morphology: fishForm('rigid-rounded-rectangular-carapace-boxfish-with-small-fins'),
    description: '圆角矩形硬甲、黄色散斑代表型、小口、小胸鳍和宽圆尾；较小展示体型的配色不代表大型成鱼的全部配色。',
    diet: '自然杂食藻类及海绵、甲壳、软体等底栖动物，也可食小鱼；本版仅取未解析动物营养分量，不将其简化为完整纯肉食食谱。',
    behavior: '真实礁缘净空内小鳍推动、有限缓游和停留；不模拟皮肤毒素、声音或完整底栖吸食。',
    habitat: ['sheltered-coral-reef', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-animal-component-of-an-omnivore'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2474', 'Museums Victoria：O.cubicus矩形硬甲、圆尾、体色变化、杂食及45cm TL、1–50m资料')] }),
  descriptor({ id: 'red-toothed-triggerfish', commonName: '红齿鳞鲀（描述性中文名）', scientificName: 'Odonus niger', scientificAuthor: '(Rüppell, 1837)',
    kind: 'fish', guild: 'reef-zooplankton-consumer', lengthM: .27, sizeRangeM: [.22, .32], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '吻端至燕尾最远端的全长，所有背棘和尾叶均计入完整空间包络。',
    referenceSizeM: { maximum: null, measure: 'not-used-for-display-calibration' }, referenceDepthM: { completeNaturalRange: false },
    colors: ['#385569', '#527889', '#994b3d'], normalizedEnvelope: envelope([-.54, .54], [-.42, .48], [-.16, .16], .57),
    support: support(), animationBounds: { tailYawRad: .10, pectoralRollRad: .06 }, morphology: fishForm('blue-deep-bodied-triggerfish-with-lyre-tail-and-short-red-teeth'),
    description: '蓝紫侧扁深体、可辨第一背棘、完整软背臀鳍、深叉燕尾及小红齿。',
    diet: '自然主要食浮游动物；本版仅使用既有plankton有机代理，未拆分真实浮游动物与浮游植物，也不代表完整天然食谱。',
    behavior: '真实礁坡水层净空内有限缓游；不模拟天然大群聚集、完整锁棘或礁隙占据。',
    habitat: ['outer-coral-reef-slope', 'near-reef-freewater'], foodPool: 'resources.plankton',
    feedingProxy: food('resources.plankton', 'selected-zooplankton-nutrition-component-of-an-unresolved-plankton-stock'),
    sources: [source('https://australian.museum/learn/animals/fishes/redtooth-triggerfish-odonus-niger/', 'Australian Museum：O.niger真实物种形态、外礁坡水层与主要浮游动物食性；本轮网页成功读取')] }),
  descriptor({ id: 'longfin-batfish', commonName: '圆脸蝙蝠鱼（描述性中文名）', scientificName: 'Platax teira', scientificAuthor: '(Forsskål, 1775)',
    kind: 'fish', guild: 'reef-omnivorous-algal-consumer', lengthM: .525, sizeRangeM: [.45, .60], sizeMeasure: 'total-length',
    lifeStage: 'non-juvenile-adult-form-representative',
    sizeMeasureDefinition: '吻端至尾鳍最远端全长；采用非幼体成鱼轮廓，不把幼体超长背臀鳍套在大型体型上。',
    referenceSizeM: { maximum: .70, measure: 'total-length', adultHumpReference: { threshold: .35, measure: 'standard-length', convertedToDisplayTotalLength: false } },
    referenceDepthM: { reportedRange: [3, 25], reportedPossibleMaximum: 70, completeNaturalRange: false },
    colors: ['#a9ae9b', '#3c4942', '#b5a150'], normalizedEnvelope: envelope([-.54, .54], [-.70, .78], [-.16, .16], .57),
    support: support(), animationBounds: { tailYawRad: .10, pectoralRollRad: .06 }, morphology: fishForm('non-juvenile-rounded-deep-batfish-with-shorter-rounded-fins-eye-bar-and-pectoral-blotch'),
    description: '宽而深的银灰圆盘体、近垂直头缘与低额隆起、眼带、胸鳍基部带和下方暗斑，背臀鳍完整但没有幼体极长丝状延伸。',
    diet: '自然杂食浮游动物、底栖动物和藻类；本版只使用当地藻类有机分量，不把它称为完整纯植食食谱。',
    behavior: '真实礁缘净空内有限缓游与停留；不模拟完整成群社会关系、漂叶幼体阶段或成熟过程。',
    habitat: ['sheltered-coral-reef', 'near-reef-freewater'], foodPool: 'resources.algae', feedingProxy: food('resources.algae', 'selected-algal-component-of-an-omnivore'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2210', 'Museums Victoria：P.teira成鱼与幼体区别、胸鳍下斑、杂食及70cm TL；低额隆起阈值为35cm SL不直接换算')] }),
  descriptor({ id: 'valentini-puffer', commonName: '黑鞍尖鼻鲀（描述性中文名）', scientificName: 'Canthigaster valentini', scientificAuthor: '(Bleeker, 1853)',
    kind: 'fish', guild: 'reef-benthic-omnivore', lengthM: .085, sizeRangeM: [.07, .10], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '尖吻至尾鳍末端全长；保持小型尖鼻鲀尺寸，身体不渲染成膨胀球或大型刺鲀。',
    referenceSizeM: { maximum: .11, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 55], completeNaturalRange: false },
    colors: ['#cecdb2', '#363a2d', '#9d8955'], normalizedEnvelope: envelope([-.54, .54], [-.24, .29], [-.22, .22], .59),
    support: support(), animationBounds: { tailYawRad: .06, pectoralRollRad: .07 }, morphology: fishForm('small-sharpnose-toby-with-four-dark-saddles-and-rounded-uninflated-body'),
    description: '小型圆腹尖鼻体、四道黑鞍带与浅色棕斑、小胸鳍和相对靠后的小背臀鳍；没有长刺。',
    diet: '自然食多种藻类与底栖动物；本版仅取未解析动物营养分量，不代表全部自然杂食菜单。',
    behavior: '真实礁缘净空内小鳍推动和有限缓游；不模拟膨胀、毒素、防御拟态或完整领域繁殖关系。',
    habitat: ['shallow-coral-reef', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-animal-component-of-an-omnivore'),
    sources: [source('https://fishesofaustralia.net.au/home/species/861', 'Museums Victoria：C.valentini四黑鞍、杂食底栖菜单及11cm TL、1–55m资料')] }),
  descriptor({ id: 'peacock-mantis-shrimp', commonName: '孔雀螳螂虾（描述性中文名）', scientificName: 'Odontodactylus scyllarus', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'crustacean', guild: 'reef-benthic-animal-predator', lengthM: .125, sizeRangeM: [.10, .15], sizeMeasure: 'body-total-length-excluding-antennae',
    sizeMeasureDefinition: '前部躯体至尾扇末端身体全长，不计前伸触角；口足目三对步足，不套用龙虾五对步足。',
    referenceSizeM: { maximum: null, measure: 'not-used-for-display-calibration' }, referenceDepthM: { completeNaturalRange: false },
    colors: ['#4a8166', '#b86748', '#427f98'], normalizedEnvelope: envelope([-.56, .78], [0, .38], [-.36, .36], .86),
    support: support(true, mantisFeet), animationBounds: { footContactsStationary: true, antennaYawRad: .025, upperLegBendRad: .02, raptorialSwingRad: .025 },
    morphology: { form: 'stalk-eyed-segmented-peacock-mantis-with-two-folded-smasher-appendages-and-three-pairs-of-walking-legs',
      normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5], sizeAxis: 'body-front-to-tail-fan-x', legPairCount: 3, raptorialAppendageCount: 2,
      clearanceIncludes: ['eyes-on-stalks', 'segmented-body', 'tail-fan', 'six-walking-legs', 'two-folded-raptorial-appendages', 'antennae', 'bounded-animation'] },
    description: '绿蓝与红褐节段体、眼柄、折叠的两只锤击附肢、三对真实步足和尾扇，完整附肢计入空间包络。',
    diet: '自然用锤击附肢捕食动物；本版仅消费当地未解析动物营养代理，不实现真实攻击、壳破裂、可见动物猎杀或空化冲击。',
    behavior: '真实礁旁碎石或沙礁脚支撑面有限爬行；U形碎石底洞穴为参考，未生成或宣称占据真实洞穴。',
    substrate: ['stable-hard-reef-margin', 'stable-reef-foot-sediment'], habitat: ['shallow-coral-reef', 'reef-foot'],
    foodPool: 'reefGuild.preyOrganicUnits', feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-animal-prey-component'),
    sources: [source('https://www2.geo.utexas.edu/specimens/Odontodactylus_scyllarus/whole/', 'University of Texas作者CT样本：O.scyllarus物种身份、颜色、U形碎石底穴及圆跟锤击捕食'),
      source('https://doris.ffessm.fr/Especes/Odontodactylus-scyllarus-Mante-de-mer-paon-1892', 'FFESSM DORIS作者物种资料：三对步足、锤击附肢、腹部游泳足及珊瑚旁沙碎屑底；全文已读')] }),
  descriptor({ id: 'green-turban-snail', commonName: '绿色蝾螺（描述性中文名）', scientificName: 'Turbo marmoratus', scientificAuthor: 'Linnaeus, 1758',
    kind: 'mollusc', guild: 'reef-hard-substrate-algal-grazer', lengthM: .17, sizeRangeM: [.14, .20], sizeMeasure: 'shell-width',
    sizeMeasureDefinition: '螺壳最大宽度作为缩放单位；软体、连续肉足及前部触角另计入完整包络，不混用壳高或软体全长。',
    referenceSizeM: { reachesOrExceeds: .20, measure: 'shell-width', sourceMaximumIsExact: false }, referenceDepthM: { completeNaturalRange: false },
    colors: ['#526a48', '#b7aa78', '#d0c4a4'], normalizedEnvelope: envelope([-.58, .80], [0, 1.08], [-.53, .53], .96),
    support: support(true, snailFeet), animationBounds: { footContactsStationary: true, tentacleYawRad: .025, bodyPulseUnits: .003 },
    morphology: { form: 'large-marbled-turban-shell-with-continuous-muscular-foot-operculum-and-front-tentacles',
      normalizedMeasuredSize: 1, shellMeasuredZ: [-.5, .5], sizeAxis: 'maximum-shell-width-z', supportContactType: 'samples-of-continuous-muscular-foot-not-six-legs',
      clearanceIncludes: ['whole-spiral-shell', 'operculum', 'soft-body', 'continuous-foot', 'front-tentacles', 'bounded-animation'] },
    description: '绿色杂斑厚重螺旋壳、壳口与厣、连续腹面肉足和前部触角；六个支撑样本属于肉足平面而不是六条腿。',
    diet: '自然植食、夜间摄食红绿藻等；本版只使用真实硬底当地已有藻类有机库存，未校准藻种偏好。',
    behavior: '真实稳定礁岩支撑面有限慢行；不模拟厣闭合防御、幼体沉降或完整夜间觅食周期。',
    substrate: ['real-stable-hard-reef-rock'], habitat: ['shallow-coral-reef', 'hard-reef-foot'], foodPool: 'resources.algae',
    feedingProxy: food('resources.algae', 'selected-local-hard-substrate-algal-component'),
    sources: [source('https://www.fao.org/fishery/docs/CDrom/aquaculture/a0845t/volume2/docrep/field/003/ac292e/AC292E01.htm', 'FAO作者移植调查：T.marmoratus植食、大型螺与20cm以上壳宽，不混别种小型蝾螺'),
      source('https://cbfm.spc.int/which-marine-resource/green-snail', 'SPC种资料索引已读：厚壳及厣、夜间红绿藻摄食；打开错误未称阅读全文')] }),
]);
export const OCEAN_REEF_COMMUNITY_IDS = freeze(OCEAN_REEF_COMMUNITY_SPECIES.map(s => s.id));
export const oceanReefCommunitySpeciesById = freeze(Object.fromEntries(OCEAN_REEF_COMMUNITY_SPECIES.map(s => [s.id, s])));
