// Finite Indo-Pacific sand/grass/reef-edge representatives. Admission depths,
// procedural proportions and nutrition proxies are display selections.
const freeze = value => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze); Object.freeze(value);
  }
  return value;
};
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, radius) => ({ x, y, z, horizontalRadiusUnits: radius,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'uncalibrated-conservative-whole-form-display-clearance-not-measured-anatomy' });
const descriptor = data => freeze({
  regionalOnly: true, identityLevel: 'species', taxonomicLevel: 'species',
  referenceRegion: '印度—西太平洋浅海草床、沙底与礁边的有限代表组合',
  coOccurrenceStatus: 'representative-community-not-a-survey-reconstruction',
  ecologicalRateStatus: 'uncalibrated-demonstration',
  calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  populationDensityPerM2: null, calibratedPopulationRates: null,
  calibratedTemperatureC: null, calibratedSalinityPSU: null,
  calibratedOxygenMgPerL: null, calibratedCurrentMPerS: null, calibratedAgeSec: null,
  temperatureRangeC: null, salinityRangePSU: null, oxygenRangeMgPerL: null,
  environmentToleranceStatus: 'unknown-not-a-species-tolerance-calibration',
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM, status: 'illustrative-selection-not-complete-species-range' },
  foodProxyStatus: 'selected-diet-component-in-existing-relative-stock-not-complete-natural-diet',
  renderEmissionEnabled: false,
  limitations: [
    '四类分别经过底质、真实植物或礁体邻近和选定水深筛选；不是同一地点的共同出现调查，也不保证每区齐全。',
    '数量、运动、摄食、代谢与生长系数未校准；温度、盐度、溶氧耐受、流速及年龄资料未知处保持null。',
    '尺寸选择、完整几何包络和动作是程序化展示参数；不是三维扫描、实测身体比例或浏览器整体观感验收。',
  ],
  ...data,
  sourceLinks: data.sources.map(item => item.url),
});

export const oceanMeadowLifeSpeciesCatalog = freeze([
  descriptor({
    id: 'sand-edge-seahorse', commonName: '草床海马（H. kuda复合群代表）',
    scientificName: 'Hippocampus kuda s.l.',
    identityLevel: 'species-complex-representative', taxonomicLevel: 'species-complex',
    taxonomicNote: '使用东南亚旧H. kuda广义复合群的平滑、深体形态代表；不宣称本程序个体经过遗传鉴定，也不把H. taeniopterus改标为同一裸物种。',
    kind: 'fish', modelRole: 'seahorse', guild: 'small-crustacean-predator', lengthM: .13,
    sizeRangeM: [.10, .16], sizeMeasure: 'straightened-height', depthSelectionM: [3, 15],
    sizeMeasureDefinition: '冠顶至未卷曲尾尖的高度；不是卷尾姿态的外观高度，也不是鱼类水平全长。',
    referenceSizeM: { maximum: .17, measure: 'straightened-height',
      note: '2004 Project Seahorse/TRAFFIC鉴定指南的旧H. kuda账户参考上限；不作为复合群所有谱系的统一最大值。' },
    referenceDepthM: { typicalRange: [0, 8], reportedMaximum: 55,
      note: '2004广义账户的典型与最大报道深度分别保留；3–15米为其报道深度内的展示选择，不宣称9–15米是实测当地草床群落或某一谱系范围。' },
    normalizedEnvelope: envelope([-.30, .42], [-.12, .72], [-.14, .14], .46),
    colors: ['#aa9270', '#655f42', '#c0af85'],
    description: '直立深体、弯颈、粗管状吻和低圆冠，卷曲尾抓住实际草叶；小背鳍与胸鳍维持近草活动。',
    diet: '自然取食小型活甲壳动物；本版仅消费未分辨底栖动物库存中的甲壳动物营养代理，不把海草、藻类或碎屑当作它的食物。',
    feedingProxy: { owner: 'reefGuild', stock: 'preyOrganicUnits',
      resourcePath: 'region.reefGuild.preyOrganicUnits', selectedDietComponent: 'unresolved-small-crustacean-organic-nutrition',
      status: 'existing-owner-stock-not-counted-live-prey-or-complete-diet' },
    behavior: '尾端锚在原生静态草叶端点附近，身体和小鳍可摆动；不模拟妊娠、配对、远距离迁移或捕杀可见动物。',
    substrate: ['sand'], habitat: ['seagrass-edge', 'seagrass-bed', 'shallow-lagoon'],
    support: { mode: 'actual-grass-leaf-tip-anchor', anchorPointLocal: { x: 0, y: 0, z: 0 },
      requiredDescriptor: 'native-static-grass-leaf', detachedHostAllowed: false },
    morphology: { form: 'smooth-deep-bodied-seahorse-with-low-coronet-and-prehensile-tail',
      sizeAxis: 'coronet-tip-to-uncurled-tail-tip', normalizedMeasuredSize: 1,
      actualPosedHeightIsMeasure: false, rootReference: 'curled-tail-grip',
      tailGripLocal: { x: 0, y: 0, z: 0 },
      clearanceIncludes: ['head', 'trunk', 'curled-tail', 'bounded-small-fin-motion'],
      wholeFormReference: { url: 'https://projectseahorse.org/wp-content/uploads/2021/06/Seahorse_ID_Guide_2004.pdf',
        location: 'printed pp.8–9 measurement/labelled anatomy; pp.64–65 H. kuda; p.112 colour plate' } },
    sources: [
      source('https://projectseahorse.org/wp-content/uploads/2021/06/Seahorse_ID_Guide_2004.pdf', 'Project Seahorse/TRAFFIC原作者鉴定指南：复合群身份、未卷尾高度、完整形态和浅水生境'),
      source('https://www.si.edu/object/hippocampus-kuda%3Anmnhvz_5294935', 'Smithsonian现场照片记录：菲律宾Mindoro，0–5米，旧H. kuda名称；只用作活体形态参考'),
      source('https://ija.scholasticahq.com/article/20489.pdf', '2008原始海马摄食试验及自然食物背景；不迁移水槽生长或投喂率到本场景'),
    ],
  }),
  descriptor({
    id: 'reef-cuttlefish', commonName: '礁乌贼', scientificName: 'Ascarosepion latimanus',
    synonymScientificNames: ['Sepia latimanus'],
    taxonomicNote: '使用当前接受的属组合；历史FAO账户提示复合群可能性，程序代表形态不是当地遗传鉴定或种群重建。',
    kind: 'cuttlefish', modelRole: 'cuttlefish', guild: 'benthic-predator', lengthM: .20,
    sizeRangeM: [.16, .24], sizeMeasure: 'mantle-length', depthSelectionM: [3, 18],
    sizeMeasureDefinition: '外套膜长轴；独立头部、八条腕和两条可伸触腕不计入该尺度，但全部进入占位包络。',
    referenceSizeM: { maximum: .50, measure: 'mantle-length',
      note: 'FAO历史S. latimanus账户的外套膜长参考上限；展示16–24厘米是有限选择，不代表完整生长阶段。' },
    referenceDepthM: { reportedMaximum: 30,
      note: 'FAO记载热带浅珊瑚礁、水深至30米；不补造完整分布范围的统一下界。' },
    normalizedEnvelope: envelope([-.60, 1.28], [-.32, .32], [-.48, .48], 1.38),
    colors: ['#97866a', '#d3c5a2', '#584c3e'],
    description: '宽卵形外套膜带成对侧鳍、独立头部和大眼，前方八腕与两条棒状触腕分开；褐色浅斑为形态展示。',
    diet: '自然食物包括鱼和甲壳动物；本版选择甲壳动物营养分量，消费旧底栖动物代理库存，不把可见鱼类死亡或完整捕食过程作为已经实现。',
    feedingProxy: { owner: 'reefGuild', stock: 'preyOrganicUnits',
      resourcePath: 'region.reefGuild.preyOrganicUnits', selectedDietComponent: 'unresolved-crustacean-organic-nutrition',
      status: 'selected-natural-diet-component-in-existing-stock' },
    behavior: '在实际礁体或稳定碎石附近近底游动，侧鳍、八腕与两触腕有有限动作；全身含俯仰通过净空检查。繁殖、色素胞控制和偏振视觉未实现。',
    substrate: ['sand', 'stable-rubble'], habitat: ['coral-reef', 'reef-sand-edge'],
    support: { mode: 'whole-freewater-body-near-actual-reef-or-rubble', rootReference: 'mantle-centre',
      requiredDescriptor: 'native-reef-or-stable-rubble', pitchClearanceRequired: true },
    morphology: { form: 'broad-oval-mantle-cuttlefish-with-eight-arms-and-two-clubbed-tentacles',
      sizeAxis: 'mantle-long-axis-x', normalizedMeasuredSize: 1, rootReference: 'mantle-centre',
      armCount: 8, feedingTentacleCount: 2,
      clearanceIncludes: ['mantle', 'paired-lateral-fins', 'head', 'eight-arms', 'two-bounded-tentacles', 'pitch'],
      wholeFormReference: { url: 'https://www.fao.org/4/a0150e/a0150e10.pdf',
        location: 'printed pp.91–92, Fig.148 dorsal/ventral whole form and tentacular club' } },
    sources: [
      source('https://www.marinespecies.org/aphia.php?id=1667002&p=taxdetails', 'WoRMS/MolluscaBase：当前接受名Ascarosepion latimanus，Sepia latimanus为旧属组合'),
      source('https://www.fao.org/4/a0150e/a0150e10.pdf', 'FAO原作者头足类鉴定资料：完整外形、外套膜长、印度—太平洋浅礁与鱼/甲壳动物食性'),
      source('https://lifg.australian.museum/Group.html?groupId=06x7MW0Y&hierarchyId=qBHH2Q3E', '澳大利亚博物馆Lizard Island：当前学名下的标注活体照片与色型参考'),
    ],
  }),
  descriptor({
    id: 'barrel-sea-pen', commonName: '棒状海鳃', scientificName: 'Cavernularia obesa',
    taxonomicNote: '主形态和水深采用2026香港整合分类中核对后的C. obesa；旧名公共序列可与C. solaris混淆，不用旧名序列直接确认本代表。',
    kind: 'sea-pen', modelRole: 'sea-pen', guild: 'suspension-feeder', lengthM: .10,
    sizeRangeM: [.08, .12], sizeMeasure: 'colony-body-length', depthSelectionM: [5, 15],
    sizeMeasureDefinition: '整段轴向群体身体长，包含埋入沉积物的柄部；不称为露出高度或充分展开时的活体高度。',
    referenceSizeM: { examinedRange: [.037, .128], measure: 'colony-body-length',
      preservationStatus: 'examined-collected-specimens-not-live-expanded-height',
      note: '2026香港标本37–128毫米；8–12厘米展示尺度不是自然最大值或露出高度换算。' },
    referenceDepthM: { examinedRange: [4.8, 15],
      note: '2026香港原始研究的采集水深；5–15米是本版选定子集，不宣称物种完整范围。' },
    normalizedEnvelope: envelope([-.25, .25], [-.30, .82], [-.25, .25], .36),
    colors: ['#c2bba6', '#e1dcc5', '#a69b83'],
    description: '无中央硬轴的棒状群体，身体周围伸出摄食水螅体；每个八放类摄食水螅体有八条羽状触手，不使用羽状海鳃的枝叶轴。',
    diet: '采用海鳃类群以触手捕获悬浮食物的依据；本版消费现有plankton相对库存的一部分，不把该库存解释成实测浮游动物数或校准滤水量。',
    feedingProxy: { owner: 'livingNetwork', stock: 'plankton', resourcePath: 'region.resources.plankton',
      selectedDietComponent: 'unresolved-suspended-plankton-organic-nutrition',
      evidenceLevel: 'sea-pen-group-functional-evidence-not-species-resolved-stomach-analysis',
      status: 'existing-relative-suspended-food-proxy', requiresNightAndExpanded: true },
    behavior: '依区域自然昼夜收缩与伸展：白天藏入软底且不摄食，夜间展开时可摄食；不模拟水平地下游走、自然发光或光合供能。',
    substrate: ['soft-sand', 'soft-sediment'], habitat: ['open-soft-bottom', 'sand-meadow-edge'],
    support: { mode: 'soft-sediment-buried-peduncle', rootReference: 'bed-surface',
      displayBuriedBodyFraction: .25, burialFractionStatus: 'uncalibrated-display-selection',
      hardRockAttachmentAllowed: false, grassCrownAttachmentAllowed: false },
    activity: { day: 'contracted-below-bed-no-feeding', night: 'expanded-polyps-may-feed',
      clock: 'native-regional-environment-not-camera-tour-time',
      calibratedExpansionTimeSec: null, undergroundHorizontalLocomotion: false },
    naturalBioluminescence: null, verifiedBioluminescence: null,
    bioluminescenceStatus: 'legacy-name-report-not-verified-for-selected-morphotype',
    morphology: { form: 'clavate-axis-free-sea-pen-with-polyps-around-rachis',
      sizeAxis: 'whole-axial-colony-including-buried-peduncle-y', normalizedMeasuredSize: 1,
      rootReference: 'bed-surface', centralAxisPresent: false,
      autozooidTentacleCount: 8, tentacleBasis: 'Octocorallia-eight-pinnate-tentacles',
      clearanceIncludes: ['buried-peduncle', 'rachis', 'bounded-expanded-polyps'],
      wholeFormReference: { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12971188/',
        location: 'Fig.2B, voucher SCSMBC240208, 30mm scale; C. obesa systematic account' } },
    sources: [
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC12971188/', 'Heung等2026原始整合分类：C. obesa核对标本、棒状无轴形态、37–128毫米身体长与4.8–15米采集深度'),
      source('https://www.mof.go.kr/doc/ko/selectDoc.do?=&bbsSeq=10&docSeq=49396&menuSeq=971', '韩国海洋水产部2023：旧C. obesa名称的沙泥底与昼藏夜食报道；不是本场温度或遗传身份校准'),
      source('https://repository.kulib.kyoto-u.ac.jp/dspace/bitstream/2433/175765/1/fia020_455.pdf', 'Mori与Tanase1973原始昼夜伸缩研究；定性活动依据，不移植实验节律数值'),
      source('https://ukmpa.marinebiodiversity.org/uk_sacs/communities/seapens/sp1_2.htm', '政府委托海洋保护研究：八放类八条羽状触手及海鳃类悬浮摄食；不借英国物种的分布或羽枝形态'),
      source('https://pmc.ncbi.nlm.nih.gov/articles/PMC3884763/', '原始CoGFP研究：旧名称下的荧光蛋白；荧光不能单独证明所选形态的自然生物发光'),
    ],
  }),
  descriptor({
    id: 'spider-conch', commonName: '蜘蛛螺', scientificName: 'Lambis lambis',
    taxonomicNote: '采用传统L. lambis典型六外唇指突形态；2023原始讨论保留隐存种边界疑问，本程序不宣称遗传鉴定，也不使用L. lambis × millepeda杂交型的7–12米记录。',
    kind: 'snail', modelRole: 'conch', guild: 'grazer', lengthM: .15,
    sizeRangeM: [.12, .18], sizeMeasure: 'shell-length', depthSelectionM: [3, 10],
    sizeMeasureDefinition: '壳的最大长轴尺寸含螺塔及前水管沟；外唇指突、足、眼柄和吻全部另纳入完整包络，不把动物总长标作壳长。',
    referenceSizeM: { maximum: .29, common: .18, measure: 'shell-length',
      note: 'FAO肯尼亚/缅甸指南壳长参考；12–18厘米是本版有限选择，不以博物馆23厘米实例反推固定比例。' },
    referenceDepthM: { guideReportedApproximateMaximum: 5, collectedExample: 10,
      collectedExampleRegion: 'Queensland-northeastern-Australia',
      collectedExampleSourceLocation: 'Alf-and-Wieneke-2023-p46-Plate2-Fig1',
      collectedExampleStatus: 'diver-collected-shell-record-not-live-population-census',
      note: 'FAO缅甸近岸账户至约5米；2023原始文章单独列Queensland潜水员10米取得的L. lambis壳。选3–10米，不将单壳记录解释为完整范围或采用同图7–12米杂交型。' },
    normalizedEnvelope: envelope([-.60, .82], [0, .70], [-.70, .70], 1.08),
    colors: ['#c5af89', '#876b49', '#d5bea2'],
    description: '厚重螺壳带高螺塔和扩大外唇，外唇六个细长指突与前端水管沟分开；足、眼柄与吻可伸出壳口。',
    diet: 'FAO自然食性为细红藻；本版仅消费现有algae相对库存，不吞食渲染海草或用碎屑、动物库存替代选定藻食分量。',
    feedingProxy: { owner: 'livingNetwork', stock: 'algae', resourcePath: 'region.resources.algae',
      selectedDietComponent: 'unresolved-algal-organic-nutrition-red-algae-reference',
      renderedSeagrassIsFood: false, status: 'existing-relative-algal-stock-not-species-resolved-red-algae-biomass' },
    behavior: '本版在原生岩石三角面上以完整壳足支持爬行，礁边碎石与藻场为自然生境背景；不保证草床内部出现，也不模拟性别壳形、足盖推进实测速率或毒芋螺捕食。',
    substrate: ['hard-reef', 'stable-rubble', 'algal-reef-flat'], habitat: ['shallow-reef-flat', 'reef-sand-edge'],
    support: { mode: 'whole-shell-and-foot-actual-native-rock-surface', rootReference: 'foot-contact',
      requiredDescriptor: 'native-rock', algalFoodEvidence: 'existing-unresolved-local-algal-stock-not-a-resolved-patch',
      grassCrownAttachmentAllowed: false, detachedShellAllowed: false },
    morphology: { form: 'heavy-spired-shell-with-six-lip-digitations-and-separate-anterior-siphonal-canal',
      sizeAxis: 'maximum-shell-long-axis-x', normalizedMeasuredSize: 1, footRootY: 0,
      rootReference: 'foot-contact', outerLipDigitationCount: 6, siphonalCanalIsLipDigitation: false,
      clearanceIncludes: ['whole-shell', 'six-lip-digitations', 'spire', 'siphonal-canal', 'foot', 'eye-stalks', 'proboscis'],
      wholeFormReference: { url: 'https://www.fao.org/4/i2741e/i2741e05.pdf',
        location: 'printed p.37, labelled Lambis lambis shell and six outer-lip digitations' } },
    sources: [
      source('https://www.fao.org/4/i2741e/i2741e05.pdf', 'FAO肯尼亚原作者鉴定指南：L. lambis完整壳形、六外唇指突、壳长和细红藻食性'),
      source('https://openknowledge.fao.org/server/api/core/bitstreams/f32d004b-6358-44f3-8242-b9d23e5346d0/content', 'FAO缅甸原作者鉴定指南：礁坪、珊瑚碎石或红树林环境至约5米；尺寸仍为壳长'),
      source('https://www.researchgate.net/publication/373113694_Conchylia_54_1-2_Juli_July_2023_43_An_interesting_form_of_Lambis_lambis_LINNAEUS_1758_and_remarks_on_Lambis_vertriesti_DEKKERS_MAXWELL_2022_Caenogastropoda_Littorinimorpha_Strombidae', 'Alf与Wieneke2023作者上传原始文章：p46 Plate2 Fig1的L. lambis，Queensland潜水员10米取得的壳；不采用Fig2杂交型深度'),
      source('https://lifg.australian.museum/Group.html?groupId=PT5tJtG5&hierarchyId=PVWrQCLG', '澳大利亚博物馆Lizard Island：标注蜘蛛螺活体与礁边碎石实例，仅作完整动物参考'),
      source('https://www.int-res.com/articles/meps2011/432/m432p083.pdf', '2011原始Cocos栖息地研究：宏藻/礁体关联与海草生境差异；不迁移当地密度到本场'),
    ],
  }),
]);

export const oceanMeadowLifeSpeciesById = freeze(Object.fromEntries(oceanMeadowLifeSpeciesCatalog.map(row => [row.id, row])));
