// Six additional v4 representatives. Selection sizes, rates and complete
// display envelopes are explicit implementation choices, not field calibration.
const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) {
  Object.values(value).forEach(freeze); Object.freeze(value); } return value; };
const source = (url, label) => ({ url, label });
const envelope = (x, y, z, horizontalRadiusUnits) => ({ x, y, z, horizontalRadiusUnits,
  axes: 'forward-positive-x; up-positive-y; transverse-z',
  status: 'conservative-display-whole-form-and-bounded-animation-not-measured-anatomy' });
const support = (bottom = false, footContacts = []) => ({ mode: bottom ? 'whole-foot-supported-reef-margin' : 'whole-freewater-body-near-real-reef',
  rootReference: bottom ? 'neutral-foot-plane' : 'total-length-midpoint', pitchLimitRad: bottom ? 0 : .10,
  minimumNormalY: .92, footContacts, wholeBodyDepthRequired: true, terrainClearanceRequired: true });
const food = (pool, component) => ({ owner: pool.split('.')[0], stock: pool.split('.')[1], resourcePath: `region.${pool}`,
  selectedFoodComponent: component, status: 'existing-selected-organic-proxy-not-complete-natural-diet',
  visiblePreyKillImplemented: false, speciesResolvedFoodStock: false });
const descriptor = data => freeze({ regionalOnly: true, identityLevel: 'species-representative', taxonomicLevel: 'species',
  referenceRegion: '热带西太平洋浅珊瑚礁的有限代表组合', coOccurrenceStatus: 'representatives-not-a-local-field-survey',
  ecologicalRateStatus: 'uncalibrated-demonstration', calibratedMovementMPerS: null, calibratedEcologicalRates: null,
  naturalPopulationDensity: null, calibratedTemperatureC: null, calibratedSalinityPSU: null, calibratedOxygenMgPerL: null,
  displaySizeM: { range: data.sizeRangeM, measure: data.sizeMeasure, status: 'illustrative-selection' },
  admissionDepthM: { range: data.depthSelectionM ?? [3, 18], status: 'chosen-whole-model-depth-not-complete-natural-range' },
  depthSelectionM: data.depthSelectionM ?? [3, 18], depthRangeM: data.depthSelectionM ?? [3, 18],
  limitations: ['程序造型、出生数量、运动及摄食速率未作野外校准；不是完整食物网或种群预测。',
    '只消费当地已存在的选定有机营养代理，不生成食物、不捕杀具体可见动物，也不代表完整自然食谱。'],
  ...data, sourceLinks: data.sources.map(item => ({ ...item })) });
const fishForm = form => ({ form, normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5], sizeAxis: 'snout-to-farthest-caudal-tip-x',
  clearanceIncludes: ['body', 'mouth', 'eyes', 'complete-caudal-fin', 'all-other-fins', 'bounded-fin-motion'] });
const shrimpFeet = [-.08, .06].flatMap(x => [-.34, .34].map(z => ({ x, y: 0, z })));
const starFeet = Array.from({ length: 5 }, (_, i) => [.18, .34].map(radius => ({
  x: radius * Math.cos(i * Math.PI * 2 / 5), y: 0, z: radius * Math.sin(i * Math.PI * 2 / 5) }))).flat();

export const OCEAN_REEF_LIFE_SPECIES = freeze([
  descriptor({ id: 'copperband-butterflyfish', commonName: '铜带蝴蝶鱼（描述性中文名）', scientificName: 'Chelmon rostratus', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'fish', guild: 'reef-benthic-animal-consumer', lengthM: .165, sizeRangeM: [.14, .19], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '管吻最前端至尾鳍最远端全长；长吻和全部鳍计入完整空间包络。',
    referenceSizeM: { maximum: .20, measure: 'total-length' }, referenceDepthM: { reportedRange: [1, 25], completeNaturalRange: false },
    colors: ['#d7d6b6', '#bd8543', '#34382c'], normalizedEnvelope: envelope([-.54, .54], [-.35, .41], [-.14, .14], .57),
    support: support(), animationBounds: { tailYawRad: .09, pectoralRollRad: .06 }, morphology: fishForm('silver-disc-copper-banded-butterflyfish-with-tubular-snout-and-dorsal-eyespot'),
    description: '银白侧扁深体、橙铜竖带、管状长嘴、近截尾和软背鳍后方黑眼斑，与黄色黑脸镊口鱼区分。',
    diet: '自然取食蟹、蠕虫等无脊椎动物；本版仅消费既有未解析动物营养分量，不宣称完整食谱或已真实从礁缝捕获具体动物。',
    behavior: '真实近礁净空内有限缓游与停留；不模拟完整探缝啄食、领域或必然成对关系。',
    habitat: ['sheltered-coastal-coral-reef', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-benthic-invertebrate-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/422', 'Museums Victoria：C.rostratus铜色条带、后背鳍眼斑、浅沿岸礁及20cm TL、1–25m资料'),
      source('https://www.kahaku.go.jp/research/db/zoology/Fishes_of_Andaman_Sea/contents/chaetodontidae/19.html', '日本国立科学博物馆作者安达曼海鱼种资料：C.rostratus管吻、截尾及蟹、蠕虫等无脊椎食性')] }),
  descriptor({ id: 'longnose-butterflyfish', commonName: '黄色镊口鱼（长吻蝴蝶鱼）', scientificName: 'Forcipiger flavissimus', scientificAuthor: 'Jordan & McGregor, 1898',
    kind: 'fish', guild: 'reef-benthic-animal-consumer', lengthM: .18, sizeRangeM: [.15, .21], sizeMeasure: 'total-length',
    sizeMeasureDefinition: '细长吻端至尾鳍最远端全长；本种为F.flavissimus，不混作嘴更长且胸部带点的F.longirostris。',
    referenceSizeM: { maximum: .22, measure: 'total-length' }, referenceDepthM: { reportedRange: [2, 145], completeNaturalRange: false },
    colors: ['#d3b944', '#252f27', '#d1d2b7'], normalizedEnvelope: envelope([-.54, .54], [-.40, .48], [-.13, .13], .57),
    support: support(), animationBounds: { tailYawRad: .09, pectoralRollRad: .06 }, morphology: fishForm('yellow-forcepsfish-with-black-upper-head-silver-lower-head-and-anal-eyespot'),
    description: '黄色深体、上半黑脸、下半银白脸和细长镊形吻，黑眼斑位于臀鳍后方；吻与黑脸位置不同于铜带蝴蝶鱼。',
    diet: '自然取食多种无脊椎动物及鱼卵；本版只使用既有未解析动物营养的选定分量，不模拟真实珊瑚、管足或鱼卵库存。',
    behavior: '真实礁缘净空内有限缓游和停留；未实现具体礁缝吸食、声音信号或完整配偶关系。',
    habitat: ['coral-reef-edge', 'near-reef-freewater'], foodPool: 'reefGuild.preyOrganicUnits',
    feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-reef-invertebrate-nutrition-component'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2410', 'Museums Victoria：F.flavissimus黄色黑脸、臀鳍眼斑、镊吻与相似种差异、无脊椎食性及22cm TL、2–145m资料')] }),
  descriptor({ id: 'fire-goby', commonName: '红火镖鱼（描述性中文名）', scientificName: 'Nemateleotris magnifica', scientificAuthor: 'Fowler, 1938',
    kind: 'fish', guild: 'reef-zooplankton-consumer', lengthM: .0725, sizeRangeM: [.06, .085], sizeMeasure: 'total-length', depthSelectionM: [6, 18],
    sizeMeasureDefinition: '吻端至圆尾最远端全长；第一背鳍长丝计入空间包络，不将它计作鱼体全长。',
    referenceSizeM: { maximum: .09, measure: 'total-length' }, referenceDepthM: { reportedRange: [6, 70], usualShallowerPreferenceNotMaximum: 28, completeNaturalRange: false },
    colors: ['#d7d0ba', '#b74c3f', '#974236'], normalizedEnvelope: envelope([-.54, .54], [-.17, .77], [-.12, .12], .57),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06, firstDorsalYawRad: .02 },
    morphology: fishForm('small-white-to-red-fire-dartfish-with-very-long-upright-first-dorsal-and-round-tail'),
    description: '小型白至粉色前体、红色后体、直立长第一背鳍、独立长软背臀鳍和圆尾，保持真实小型尺寸。',
    diet: '自然在底面上方悬停取食水流中的浮游动物；本版只使用未解析plankton库存中的选定动物营养分量。',
    behavior: '选择6米及以下的实际水层深度，近礁净空内有限缓游和停留；不宣称已模拟真实洞穴占据、急退洞穴或完整终身配对。',
    habitat: ['upper-outer-reef-slope', 'near-reef-freewater'], foodPool: 'resources.plankton',
    feedingProxy: food('resources.plankton', 'selected-zooplankton-component-of-an-unresolved-plankton-stock'),
    sources: [source('https://fishesofaustralia.net.au/home/species/2943', 'Museums Victoria：N.magnifica长第一背鳍、白红体和圆尾、底面上方浮游动物摄食及9cm TL、6–70m资料')] }),
  descriptor({ id: 'pajama-cardinalfish', commonName: '丝鳍圆天竺鲷（睡衣天竺鲷）', scientificName: 'Sphaeramia nematoptera', scientificAuthor: '(Bleeker, 1856)',
    kind: 'fish', guild: 'sheltered-reef-small-animal-consumer', lengthM: .0725, sizeRangeM: [.06, .085], sizeMeasure: 'total-length', depthSelectionM: [3, 14],
    sizeMeasureDefinition: '吻端至尾鳍最远端全长；双背鳍、眼与完整尾鳍计入包络，不放大成大型礁鱼。',
    referenceSizeM: { maximum: .09, measure: 'total-length', source: 'Museums-Victoria' }, referenceDepthM: { reportedRange: [1, 14], completeNaturalRange: false },
    colors: ['#c9b46e', '#363c30', '#a58087'], normalizedEnvelope: envelope([-.54, .54], [-.32, .40], [-.15, .15], .57),
    support: support(), animationBounds: { tailYawRad: .08, pectoralRollRad: .06 }, morphology: fishForm('large-eyed-pajama-cardinalfish-with-yellow-front-mid-black-bar-and-spotted-rear'),
    description: '大眼红虹膜、黄色前半体、中部宽黑带、后半粉灰散斑和分开的双背鳍，轮廓与火镖鱼不同。',
    diet: '自然食浮游动物及其他底栖无脊椎动物；本版仅选择已有plankton库存分量，不把它称为全部自然食谱。',
    behavior: '受保护的真实近珊瑚水层有限缓游和停留；未实现真实枝珊瑚种专一性、完整群居关系或雄性口孵。',
    habitat: ['sheltered-coral-reef', 'near-reef-freewater'], foodPool: 'resources.plankton',
    feedingProxy: food('resources.plankton', 'selected-zooplankton-component-of-an-unresolved-plankton-stock'),
    sources: [source('https://fishesofaustralia.net.au/Home/species/4237', 'Museums Victoria：S.nematoptera黄头、中黑带、后部紫点、受保护湾枝珊瑚邻近及9cm TL、1–14m资料'),
      source('https://fishdb.sinica.edu.tw/taxon/381387-fishdb', '中央研究院台湾鱼类资料库作者物种记录：大眼红虹膜、双背鳍、浮游动物及底栖无脊椎食性')] }),
  descriptor({ id: 'banded-coral-shrimp', commonName: '红白清洁虾（描述性中文名）', scientificName: 'Stenopus hispidus', scientificAuthor: '(Olivier, 1811)',
    kind: 'crustacean', guild: 'reef-cleaner-animal-consumer', lengthM: .065, sizeRangeM: [.05, .08], sizeMeasure: 'body-total-length-excluding-antennae',
    sizeMeasureDefinition: '前部躯体至尾扇末端的身体全长，不含两对白长触角；触角、大举钳均另计入完整包络。',
    referenceSizeM: { maximum: .09, measure: 'body-total-length-excluding-antennae' }, referenceDepthM: { reportedRange: [1, 40], completeNaturalRange: false },
    colors: ['#bb5143', '#d9d7c7', '#707562'], normalizedEnvelope: envelope([-.58, 2.48], [0, .82], [-1.08, 1.08], 2.71),
    support: support(true, shrimpFeet), animationBounds: { footContactsStationary: true, antennaYawRad: .025, upperLegBendRad: .02, chelaSwingRad: .02 },
    morphology: { form: 'red-white-banded-stenopid-with-three-chelate-front-pairs-two-walking-pairs-and-four-long-white-antennae',
      normalizedMeasuredSize: 1, bodyMeasuredX: [-.5, .5], sizeAxis: 'body-front-to-tail-fan-x',
      chelatePairCount: 3, enlargedChelaPair: 3, groundWalkingPairCount: 2, longAntennaCount: 4,
      clearanceIncludes: ['body', 'tail-fan', 'four-ground-walking-legs', 'three-front-chelate-pairs', 'four-long-white-antennae', 'bounded-animation'] },
    description: '红白节段身体、前三对带钳附肢且第三对明显大举钳、后两对步足、两对白长触角及完整尾扇。',
    diet: '真实物种清理鱼体寄生物及死组织；本版仅使用未解析动物营养代理，没有清除具体鱼体寄生物或真实清洁共生行为。',
    behavior: '真实稳定礁脚有限爬行与停留，前大钳举起不当作支撑足；礁隙庇护与清洁站为参考，未生成假洞或宣称真实清洁站。',
    substrate: ['stable-hard-reef-margin', 'stable-reef-foot-sediment'], habitat: ['shallow-coral-reef', 'reef-foot'],
    foodPool: 'reefGuild.preyOrganicUnits', feedingProxy: food('reefGuild.preyOrganicUnits', 'selected-unresolved-animal-component-for-a-natural-cleaner'),
    sources: [source('https://museum.wa.gov.au/online-collections/names/Stenopus-hispidus', 'Western Australian Museum：S.hispidus红白体、第三大钳、两对长触角及90mm身体全长'),
      source('https://museum.wa.gov.au/explore/blogs/andrew-hosie/creature-feature-banded-boxer-shrimp', 'Western Australian Museum作者Andrew Hosie：前三对螯足与第三大钳、寄生物及死组织清洁食性'),
      source('https://doris.ffessm.fr/Especes/Stenopus-hispidus-Grande-crevette-nettoyeuse-422', 'FFESSM DORIS作者物种资料：两对白触角约两倍身体长、礁隙1–40m及寄生物清洁；全文已读')] }),
  descriptor({ id: 'chocolate-chip-sea-star', commonName: '黑瘤海星（巧克力海星，描述性中文名）', scientificName: 'Protoreaster nodosus', scientificAuthor: '(Linnaeus, 1758)',
    kind: 'echinoderm', guild: 'soft-bottom-film-and-particle-consumer', lengthM: .25, sizeRangeM: [.20, .30], sizeMeasure: 'body-diameter',
    sizeMeasureDefinition: '五臂水平外包圆直径作为展示缩放单位；粗臂、黑色高瘤和真实腹面管足另计完整包络。',
    referenceSizeM: { maximum: .40, measure: 'body-diameter' }, referenceDepthM: { reportedRange: [0, 30], moreFrequentAbove: 5, completeNaturalRange: false },
    colors: ['#b8a170', '#3b372c', '#d0b885'], normalizedEnvelope: envelope([-.54, .54], [0, .32], [-.54, .54], .77),
    support: support(true, starFeet), animationBounds: { footContactsStationary: true, bodyPulseUnits: .003 },
    morphology: { form: 'five-short-thick-arms-with-dark-high-conical-tubercles-and-ten-ventral-tube-tips', normalizedMeasuredSize: 1,
      horizontalCircumscribedBodyDiameter: 1, sizeAxis: 'horizontal-circumscribed-body-diameter',
      clearanceIncludes: ['five-thick-arms', 'central-disc', 'high-dark-conical-tubercles', 'ventral-tube-feet', 'bounded-animation'] },
    description: '厚重中央盘与五条短粗三角截面臂、顶部成列高黑瘤、腹面管足；中央口不作为支撑足，区别于旧蓝长臂海星和枕海星。',
    diet: '自然取食软底上的藻与微生物膜、有机颗粒和碎屑；本版仅选择当地碎屑有机分量，不代表完整藻膜、微生物或自然食谱。',
    behavior: '真实浅潟湖软沙或草缘沉积底上的有限慢行，保留完整支撑检查；不模拟胃外翻、完整底膜消化或自然聚集密度。',
    substrate: ['real-soft-sand', 'actual-seagrass-associated-sediment'], habitat: ['shallow-lagoon-sand', 'reef-foot-sand'],
    foodPool: 'resources.detritus', feedingProxy: food('resources.detritus', 'selected-soft-bottom-organic-particle-and-detrital-component'),
    sources: [source('https://doris.ffessm.fr/Especes/Protoreaster-nodosus-Etoile-de-mer-a-cornes-du-Pacifique-2340', 'FFESSM DORIS作者Sylvain Le Bris/Frédéric Ducarme：西太平洋浅沙草潟湖0–30m、五短粗臂高黑瘤、40cm直径与藻微生物膜及有机碎屑食性；全文已读')] }),
]);
export const OCEAN_REEF_LIFE_IDS = freeze(OCEAN_REEF_LIFE_SPECIES.map(s => s.id));
export const oceanReefLifeSpeciesById = freeze(Object.fromEntries(OCEAN_REEF_LIFE_SPECIES.map(s => [s.id, s])));
