// Representative shallow Indo-Pacific reef community. Sizes are display individuals,
// not record maxima. Links document taxonomy / natural history, not model constants.
export const speciesCatalog = [
  {
    id: 'blue-tang', commonName: '蓝倒吊', scientificName: 'Paracanthurus hepatus', kind: 'fish', guild: 'planktivore', lengthM: 0.23,
    colors: ['#227ce8', '#101b3f', '#ffe567'],
    description: '印度—西太平洋珊瑚礁的蓝色刺尾鱼；本场采用幼成鱼混合小群，不代表自然密度。',
    diet: '浮游动物；本模型采用浮游摄食。', behavior: '在礁体上方活动，遇到捕食者逃向珊瑚庇护区。',
    sources: [{ url: 'https://australian.museum/learn/animals/fishes/blue-tang-paracanthurus-hepatus/', label: '澳大利亚博物馆：蓝倒吊食性与分布' }],
  },
  {
    id: 'butterflyfish', commonName: '条纹蝴蝶鱼', scientificName: 'Chaetodon lineolatus', kind: 'fish', guild: 'benthic-feeder', lengthM: 0.20,
    colors: ['#f4ead1', '#f2c746', '#23384a'],
    description: '侧扁、带黑色眼带与细条纹的热带礁鱼。', diet: '珊瑚虫、海葵及小型底栖无脊椎动物。',
    behavior: '靠近礁面巡游、啄食；夜间在礁隙休息。',
    sources: [{ url: 'https://fishesofaustralia.net.au/home/species/2384', label: 'Museums Victoria：条纹蝴蝶鱼' }],
  },
  {
    id: 'green-chromis', commonName: '绿光鳃雀鲷', scientificName: 'Chromis viridis', kind: 'fish', guild: 'planktivore', lengthM: 0.075,
    colors: ['#74dacb', '#bceee3', '#51a99c'],
    description: '小型蓝绿色雀鲷，在枝状珊瑚上方形成鱼群。', diet: '浮游动物。',
    behavior: '群游摄食，受到威胁时向珊瑚枝间躲避。',
    sources: [{ url: 'https://lifg.australian.museum/Group.html?groupId=bWdTTXD5&hierarchyId=CEJQQmVx', label: '澳大利亚博物馆：丽莎岛绿光鳃雀鲷' }, { url: 'https://fishesofaustralia.net.au/home/species/329', label: 'Museums Victoria：绿光鳃雀鲷浮游食性' }],
  },
  {
    id: 'lined-tang', commonName: '条纹倒吊', scientificName: 'Acanthurus lineatus', kind: 'fish', guild: 'grazer', lengthM: 0.24,
    colors: ['#e5bc46', '#509ed4', '#263d4a'],
    description: '黄蓝相间的刺尾鱼，在浅礁藻面上摄食。', diet: '主要刮食附着藻类。',
    behavior: '沿礁面觅食；本模型简化了自然中的领地竞争。',
    sources: [{ url: 'https://fishesofaustralia.net.au/home/species/2186', label: 'Museums Victoria：条纹倒吊' }],
  },
  {
    id: 'cleaner-wrasse', commonName: '裂唇鱼', scientificName: 'Labroides dimidiatus', kind: 'fish', guild: 'cleaner', lengthM: 0.105,
    colors: ['#97dce7', '#152735', '#e2efdd'],
    description: '以清洁站为中心活动的清洁鱼。', diet: '客户鱼体表的甲壳类外寄生虫，也摄取黏液。',
    behavior: '靠近较大的客户鱼清洁；不是普通藻食鱼。',
    sources: [{ url: 'https://fishesofaustralia.net.au/home/species/250', label: 'Museums Victoria：裂唇鱼清洁行为' }],
  },
  {
    id: 'honeycomb-grouper', commonName: '蜂巢石斑鱼', scientificName: 'Epinephelus merra', kind: 'fish', guild: 'predator', lengthM: 0.28,
    colors: ['#baa984', '#66523e', '#ded2af'],
    description: '带蜂巢状斑纹的小型石斑鱼，浅泻湖和礁区的定居性伏击捕食者。',
    diet: '小鱼及甲壳类。', behavior: '在礁旁停留、伏击和短距离追逐；不会持续高速绕圈。',
    sources: [{ url: 'https://fishesofaustralia.net.au/home/species/3848', label: 'Museums Victoria：蜂巢石斑鱼' }],
  },
  {
    id: 'cleaner-shrimp', commonName: '清洁虾', scientificName: 'Lysmata amboinensis', kind: 'shrimp', guild: 'cleaner', lengthM: 0.055,
    colors: ['#e96c44', '#fff0dc', '#e5b157'],
    description: '具有醒目红白体色和长白触须的印度太平洋清洁虾。', diet: '鱼体表寄生物及小型有机食物。',
    behavior: '在岩隙清洁站附近活动，接近客户鱼并避入岩隙。',
    sources: [{ url: 'https://www.georgiaaquarium.org/animal/hawaiian-cleaner-shrimp/', label: 'Georgia Aquarium：本种红背、白纵带和橙黄附肢' }, { url: 'https://doi.org/10.15560/12.6.2010', label: 'Prakash 等（2016）：本种形态与体色，p.4 / Fig.4；尾扇白斑与尾节断纹' }, { url: 'https://pubmed.ncbi.nlm.nih.gov/31530112/', label: 'Caves 等（2019）：本种清洁与客户风险行为' }],
  },
  {
    id: 'reef-crab', commonName: '黑指珊瑚蟹', scientificName: 'Cymo melanodactylus', kind: 'crab', guild: 'coral-associate', lengthM: 0.025,
    colors: ['#ccb984', '#5b5140', '#e1aa72'],
    description: '栖于鹿角珊瑚属枝间的小蟹；不是在开阔沙地游荡的大型礁蟹。',
    diet: '可摄取宿主珊瑚组织；本版未建珊瑚组织资源池，用局部有机资源代理供能，不能当作完整野外食谱。', behavior: '限制在珊瑚庇护区内，受到威胁时躲入枝间。',
    sources: [{ url: 'https://lifg.australian.museum/Group.html?groupId=EwuDmKJ0', label: '澳大利亚博物馆：黑指珊瑚蟹与 Acropora' }, { url: 'https://eprints.jcu.edu.au/24647/', label: 'Pollock 等（2013）：本种珊瑚组织摄食与宿主关系' }],
  },
  {
    id: 'black-cucumber', commonName: '黑海参', scientificName: 'Holothuria atra', kind: 'cucumber', guild: 'deposit-feeder', lengthM: 0.24,
    colors: ['#292e2d', '#424840', '#91826d'],
    description: '浅热带礁区常见的黑色海参。', diet: '沉积物中的有机颗粒与微生物。',
    behavior: '在沙地缓慢爬行、摄取沉积物；不追逐鱼类。',
    sources: [{ url: 'https://lifg.australian.museum/Group.html?groupId=7UQOQa5x', label: '澳大利亚博物馆：黑海参' }, { url: 'https://www.smujo.id/biodiv/article/download/5653/3879/21795', label: 'Hartati 等（2020）：沉积物有机物与微底栖藻摄食' }],
  },
  {
    id: 'blue-starfish', commonName: '蓝海星', scientificName: 'Linckia laevigata', kind: 'star', guild: 'surface-feeder', lengthM: 0.24,
    colors: ['#297ebe', '#56b4d0', '#256fa1'],
    description: '热带礁面的蓝色海星，以管足缓慢移动。其细节食谱仍有不确定性。',
    diet: '模型合并为礁面生物膜和有机物，不能据此推断完整自然食谱。',
    behavior: '缓慢表面觅食，未模拟追捕鱼类或快速游泳。',
    sources: [{ url: 'https://lifg.australian.museum/Group.html?groupId=RtcVGxAf&hierarchyId=', label: '澳大利亚博物馆：蓝海星' }, { url: 'https://www.nhm.ac.uk/take-part/monitor-and-encourage-nature/project-archive/have-you-seen-this-starfish-wanted-alive-and-in-colour.html', label: '英国自然历史博物馆：蓝海星运动与摄食' }],
  },
  {
    id: 'top-shell', commonName: '马蹄螺', scientificName: 'Rochia nilotica', kind: 'snail', guild: 'grazer', lengthM: 0.11,
    colors: ['#d9c6a7', '#a47d70', '#ece0cd'],
    description: '印度太平洋浅礁的锥形大型海螺，旧名 Trochus niloticus。',
    diet: '附着小型藻类和藻坪。', behavior: '在岩面和珊瑚碎石缓慢爬行，以齿舌刮食。',
    sources: [{ url: 'https://www.fao.org/4/ag150e/ag150e03.htm', label: 'FAO：马蹄螺栖息地与藻食' }],
  },
  {
    id: 'staghorn-coral', commonName: '鹿角珊瑚', scientificName: 'Acropora muricata', kind: 'coral', guild: 'photosymbiotic', lengthM: 0.85,
    colors: ['#c5aa84', '#e6d3ac', '#b89183'],
    description: '印度太平洋枝状造礁石珊瑚；珊瑚是动物。不使用加勒比 Acropora cervicornis 混充本物种。',
    diet: '共生藻光合产物，同时可捕获小型浮游食物。', behavior: '固着生长并提供庇护；本原型不在分钟尺度制造新珊瑚群体。',
    sources: [{ url: 'https://www.aims.gov.au/sites/default/files/Long%20term%20Monitoring%20GBR%20Standard%20Operational%20Procedure%2010.pdf', label: 'AIMS：枝状 Acropora muricata 分类' }, { url: 'https://www.fisheries.noaa.gov/national/habitat-conservation/shallow-coral-reef-habitat', label: 'NOAA：浅海珊瑚礁生境' }, { url: 'https://oceanservice.noaa.gov/education/tutorial_corals/coral01_intro.html', label: 'NOAA：珊瑚虫与浮游动物摄食' }],
  },
  {
    id: 'giant-clam', commonName: '小砗磲', scientificName: 'Tridacna maxima', kind: 'clam', guild: 'photosymbiotic-filter', lengthM: 0.25,
    colors: ['#658cc7', '#d3c1a5', '#457b86'],
    description: '浅礁和环礁泻湖的砗磲，外套膜可呈蓝绿及棕色。', diet: '共生藻光合供能和水中悬浮颗粒。',
    behavior: '固着、滤食；浑浊降低共生光合收益，不随鱼群游动。',
    sources: [{ url: 'https://www.fisheries.noaa.gov/species/small-giant-clam', label: 'NOAA：Tridacna maxima' }, { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7175534/', label: 'Guibert 等（2020）：T. maxima 共生藻与滤食' }],
  },
  {
    id: 'turf-algae', commonName: '礁面藻膜', scientificName: 'Turf algal assemblage', kind: 'algae', guild: 'producer', lengthM: 0.35,
    colors: ['#737e3f', '#4e7443', '#a0a363'],
    description: '附着在岩石上的多物种藻膜功能群，不是一个被命名的物种，也不是海带森林。',
    diet: '依靠光照和可用营养生长。', behavior: '固着，被藻食倒吊和马蹄螺刮食。',
    sources: [{ url: 'https://www.fao.org/4/ag150e/ag150e03.htm', label: 'FAO：浅礁藻坪与马蹄螺摄食' }],
  },
];

export const speciesById = Object.fromEntries(speciesCatalog.map((species) => [species.id, species]));
